package worldline.smoke.slowblocksb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places official cobweb 30 and soul sand 88 and proves Packet13 pose deltas are slower in each than in air. */
public final class SlowBlocksSmoke{
 private SlowBlocksSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SlowBlocksSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  require(user.length()<=16,"username exceeds 16");B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,web,soul;int column,ticks=8;PlayerPose pose;BlockState webPlaced,soulPlaced;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,30,88},new int[]{32,1,1},new int[]{0,0,0});actor.connect();pose=actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==3,"slow-blocks inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();require(++column<=15,"water column exceeded slow-blocks fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();column++;}
   actor.selectHeldSlot(1);web=BlockFace.UP.adjacent(top);actor.placeHeldBlock(top,BlockFace.UP);webPlaced=new BlockState(30,0);actor.awaitBlock(web,webPlaced);actor.selectHeldSlot(2);soul=BlockFace.WEST.adjacent(top);actor.placeHeldBlock(top,BlockFace.WEST);soulPlaced=new BlockState(88,0);actor.awaitBlock(soul,soulPlaced);RemoteWorldView live=actor.sustainTicks(5);require(live.blockAt(web.x(),web.y(),web.z()).equals(webPlaced)&&live.blockAt(soul.x(),soul.y(),soul.z()).equals(soulPlaced),"live slow-blocks drift");
   pose=actor.moveAndObserve((web.x()+1.5D)-pose.x(),web.y()-pose.y(),(web.z()+0.5D)-pose.z(),4).resulting();live=actor.sustainTicks(1);require(live.blockAt(floor(pose.x()),floor(pose.y()),floor(pose.z())).legacyId()==0,"air path was not empty");PlayerPose airStart=pose;pose=walk(actor,live,pose,0.125D,ticks);int air=milli(Math.hypot(pose.x()-airStart.x(),pose.z()-airStart.z()));
   pose=actor.moveAndObserve((web.x()+0.5D)-pose.x(),web.y()-pose.y(),(web.z()+0.5D)-pose.z(),4).resulting();live=actor.sustainTicks(1);require(live.blockAt(web.x(),web.y(),web.z()).equals(webPlaced)&&floor(pose.x())==web.x()&&floor(pose.y())==web.y()&&floor(pose.z())==web.z(),"walk-into-cobweb drift");PlayerPose webStart=pose;pose=walk(actor,live,pose,0.125D,ticks);int webDelta=milli(Math.hypot(pose.x()-webStart.x(),pose.z()-webStart.z()));
   pose=approach(actor,live,pose,soul.x()+0.5D,web.y(),soul.z()+0.5D);live=actor.sustainTicks(1);require(live.blockAt(soul.x(),soul.y(),soul.z()).equals(soulPlaced)&&floor(pose.x())==soul.x()&&floor(pose.z())==soul.z()&&onSoul(live,pose),"walk-onto-soulsand drift");PlayerPose soulStart=pose;pose=walk(actor,live,pose,0.125D,ticks);int soulDelta=milli(Math.hypot(pose.x()-soulStart.x(),pose.z()-soulStart.z()));require(webDelta<air&&soulDelta<air&&air>0&&webDelta>0&&soulDelta>0,"slow-block poses were not slower than air "+air+"/"+webDelta+"/"+soulDelta);
   actor.close();awaitPlayers(server,0);server.save();reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(top.x(),cx),top.y(),local(top.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(web.x(),cx),web.y(),local(web.z(),cz)).equals(webPlaced)&&after.blockAt(local(soul.x(),cx),soul.y(),local(soul.z(),cz)).equals(soulPlaced),"persisted slow-blocks drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,cobweb="+web.x()+":"+web.y()+":"+web.z()+":30:0,soulsand="+soul.x()+":"+soul.y()+":"+soul.z()+":88:0,ticks="+ticks+",air="+air+",web="+webDelta+",soul="+soulDelta+",slower=true,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+cobweb30+soulsand88-path|cause=packet15-item30+packet15-item88+packet13-walk|wire=packet13-pose-deltas-"+ticks+"ticks|oracle=cobweb-pose-slower-than-air+soulsand-pose-slower-than-air|"+evidence;System.out.println("WORLDLINE_M317_SLOW="+evidence);System.out.println("WORLDLINE_M317_TRACE="+trace);System.out.println("WORLDLINE_M317_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static PlayerPose walk(B173WireClient a,RemoteWorldView world,PlayerPose start,double step,int ticks)throws Exception{PlayerPose pose=start;RemoteWorldView view=world;for(int i=0;i<ticks;i++){double scale=scale(view,pose);pose=a.moveAndObserve(0D,0D,step*scale,1).resulting();view=a.sustainTicks(1);}return pose;}
 private static PlayerPose approach(B173WireClient a,RemoteWorldView world,PlayerPose pose,double x,double y,double z)throws Exception{RemoteWorldView view=world;for(int i=0;i<80;i++){double dx=x-pose.x(),dy=y-pose.y(),dz=z-pose.z();if(Math.abs(dx)<0.04D&&Math.abs(dy)<0.04D&&Math.abs(dz)<0.04D)return pose;double s=scale(view,pose)*0.125D,len=Math.hypot(dx,dz),mx=len>1.0E-6D?dx/len*Math.min(s,len):0D,mz=len>1.0E-6D?dz/len*Math.min(s,len):0D;pose=a.moveAndObserve(mx,Math.max(-s,Math.min(s,dy)),mz,1).resulting();view=a.sustainTicks(1);}throw new IllegalStateException("approach failed "+pose.x()+","+pose.y()+","+pose.z()+" -> "+x+","+y+","+z);}
 private static double scale(RemoteWorldView w,PlayerPose p){if(id(w,p,0D)==30||id(w,p,0.9D)==30)return 0.25D;if(onSoul(w,p))return 0.4D;return 1D;}
 private static boolean onSoul(RemoteWorldView w,PlayerPose p){return id(w,p,0D)==88||id(w,p,-1D)==88;}
 private static int id(RemoteWorldView w,PlayerPose p,double dy){return w.blockAt(floor(p.x()),floor(p.y()+dy),floor(p.z())).legacyId();}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic slow-blocks foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static int floor(double v){return(int)Math.floor(v);}private static int milli(double v){return(int)Math.round(v*1000D);}
 private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
