package worldline.smoke.stickypistonb173;

import java.nio.*;import java.nio.charset.*;import java.nio.file.*;import java.security.*;import java.time.*;
import worldline.api.*;import worldline.b173server.*;

/** Retracts one official sticky piston and proves exact stone pullback. */
public final class StickyPistonPullSmoke{
 private StickyPistonPullSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=9)throw new IllegalArgumentException("usage: StickyPistonPullSmoke server.jar workspace port seed username chunkX chunkZ fixtureTicks signalTicks");Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String username=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]),fixture=Integer.parseInt(a[7]),signal=Integer.parseInt(a[8]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient builder=new B173WireClient("127.0.0.1",port,username,timeout),actor=null,reader=null;RemoteChunkSnapshot before,after;BlockPosition top,piston,head,pushed,lever;BlockState leverOn,leverOff,pistonOn,pistonOff,headOn,headOff,pushedOn,pushedOff;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,username,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,29,69},new int[]{16,1,1},new int[]{0,0,0});builder.connect();builder.synchronizePose();builder.look(-90F,0F);require(builder.awaitInventory().occupiedSlots()==3,"sticky fixture inventory drift");RemoteChunkSnapshot initial=builder.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;builder.selectHeldSlot(0);
   while(water(at(initial,BlockFace.UP.adjacent(top),cx,cz).legacyId())){builder.placeHeldBlock(top,BlockFace.UP);top=BlockFace.UP.adjacent(top);builder.awaitBlock(top,new BlockState(1,0));builder.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded fixture stack");}
   builder.placeHeldBlock(top,BlockFace.UP);top=BlockFace.UP.adjacent(top);builder.awaitBlock(top,new BlockState(1,0));builder.moveAndObserve(0D,1D,2D,1);column++;piston=BlockFace.UP.adjacent(top);head=BlockFace.WEST.adjacent(piston);pushed=BlockFace.WEST.adjacent(head);lever=BlockFace.EAST.adjacent(top);
   builder.selectHeldSlot(1);builder.placeHeldBlock(top,BlockFace.UP);require(worldline.test.WorldlineSmokeAwait.observe(builder,5).blockAt(piston.x(),piston.y(),piston.z()).equals(new BlockState(29,4)),"west sticky piston absent");builder.selectHeldSlot(0);builder.placeHeldBlock(piston,BlockFace.WEST);builder.awaitBlock(head,new BlockState(1,0));builder.selectHeldSlot(2);builder.placeHeldBlock(top,BlockFace.EAST);require(worldline.test.WorldlineSmokeAwait.observe(builder,5).blockAt(lever.x(),lever.y(),lever.z()).equals(new BlockState(69,1)),"lever absent");builder.selectHeldSlot(3);worldline.test.WorldlineSmokeAwait.observe(builder,fixture);builder.activateBlock(lever,BlockFace.UP);RemoteWorldView extended=worldline.test.WorldlineSmokeAwait.observe(builder,signal);require(extended.blockAt(piston.x(),piston.y(),piston.z()).equals(new BlockState(29,12))&&extended.blockAt(head.x(),head.y(),head.z()).equals(new BlockState(34,12))&&extended.blockAt(pushed.x(),pushed.y(),pushed.z()).equals(new BlockState(1,0)),"sticky extension prerequisite absent");builder.close();awaitPlayers(server,0);server.save();
   actor=new B173WireClient("127.0.0.1",port,username,timeout);actor.connect();actor.synchronizePose();before=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);leverOn=at(before,lever,cx,cz);pistonOn=at(before,piston,cx,cz);headOn=at(before,head,cx,cz);pushedOn=at(before,pushed,cx,cz);require(leverOn.equals(new BlockState(69,9))&&pistonOn.equals(new BlockState(29,12))&&headOn.equals(new BlockState(34,12))&&pushedOn.equals(new BlockState(1,0)),"fresh sticky prerequisite drift");actor.selectHeldSlot(3);
   actor.activateBlock(lever,BlockFace.UP);RemoteWorldView live=worldline.test.WorldlineSmokeAwait.observe(actor,signal);leverOff=live.blockAt(lever.x(),lever.y(),lever.z());pistonOff=live.blockAt(piston.x(),piston.y(),piston.z());headOff=live.blockAt(head.x(),head.y(),head.z());pushedOff=live.blockAt(pushed.x(),pushed.y(),pushed.z());require(leverOff.equals(new BlockState(69,1))&&pistonOff.equals(new BlockState(29,4))&&headOff.equals(new BlockState(1,0))&&pushedOff.equals(new BlockState(0,0)),"exact sticky pull absent: "+leverOff+"/"+pistonOff+"/"+headOff+"/"+pushedOff);actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,username,timeout);reader.connect();reader.synchronizePose();after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(at(after,lever,cx,cz).equals(leverOff)&&at(after,piston,cx,cz).equals(pistonOff)&&at(after,head,cx,cz).equals(headOff)&&at(after,pushed,cx,cz).equals(pushedOff),"fresh sticky pull state drift");
  }finally{builder.close();if(actor!=null)actor.close();if(reader!=null)reader.close();server.close();}
  Delta delta=delta(before,after,top.y());require(delta.changed==4,"raised sticky pull changed unrelated states: "+delta.cells);String evidence="column="+column+",lever="+lever.x()+":"+lever.y()+":"+lever.z()+":"+leverOn.metadata()+"->"+leverOff.metadata()+",piston="+piston.x()+":"+piston.y()+":"+piston.z()+":"+pistonOn.metadata()+"->"+pistonOff.metadata()+",head="+headOn.legacyId()+":"+headOn.metadata()+"->"+headOff.legacyId()+":"+headOff.metadata()+",pushed="+pushedOn.legacyId()+":"+pushedOn.metadata()+"->"+pushedOff.legacyId()+":"+pushedOff.metadata()+",raised-states="+delta;String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=fresh-extended-sticky-piston29+head34:12+displaced-stone1|settle="+fixture+"+"+signal+"+save+fresh+"+signal+"ticks|cause=packet15-lever-deactivate|effect=official-sticky-retract+stone-pullback|observation=fresh-login-packet51|"+evidence+"|disconnect=clean";System.out.println("WORLDLINE_M144_STICKY="+evidence);System.out.println("WORLDLINE_M144_TRACE="+trace);System.out.println("WORLDLINE_M144_SIGNATURE="+sha(trace));
 }
 private static BlockPosition foundation(RemoteChunkSnapshot c,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(c.blockAt(x,y,z).legacyId()==3&&water(c.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic sticky foundation");}private static BlockState at(RemoteChunkSnapshot c,BlockPosition p,int cx,int cz){return c.blockAt(p.x()-cx*16,p.y(),p.z()-cz*16);}
 private static Delta delta(RemoteChunkSnapshot a,RemoteChunkSnapshot b,int minY)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");ByteBuffer row=ByteBuffer.allocate(10);StringBuilder cells=new StringBuilder();int n=0;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=minY;y<128;y++){BlockState q=a.blockAt(x,y,z),r=b.blockAt(x,y,z);if(!q.equals(r)){if(cells.length()>0)cells.append(';');cells.append(x).append(':').append(y).append(':').append(z).append(':').append(q).append('>').append(r);n++;row.clear();row.putShort((short)x).putShort((short)y).putShort((short)z).put((byte)q.legacyId()).put((byte)q.metadata()).put((byte)r.legacyId()).put((byte)r.metadata());d.update(row.array());}}return new Delta(n,hex(d.digest()),cells.toString());}
 private static boolean water(int id){return id==8||id==9;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{return hex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte v:b)s.append(String.format("%02x",v&255));return s.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static final class Delta{final int changed;final String hash,cells;Delta(int c,String h,String x){changed=c;hash=h;cells=x;}public String toString(){return changed+":"+hash;}}
}
