package worldline.smoke.lavaobsidiansetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Still lava 11 plus water 9 produce obsidian 49 in adjacent and onto geometries. */
public final class LavaObsidianSetSmoke{
 private LavaObsidianSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: LavaObsidianSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("LavaObs414")&&user.length()<=16,"lava-obsidian-set identity drift");
  Duration timeout=Duration.ofSeconds(90);B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;
  BlockPosition top,waterAdjFloor,adjLava,adjWater,southFloor,southWaterFloor,southLava,southWater;int column;PlayerPose pose;
  BlockState air=new BlockState(0,0),stillWater=new BlockState(9,0),stillLava=new BlockState(11,0),obsidian=new BlockState(49,0);
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4},new int[]{1,327,327,326,326},new int[]{64,1,1,1,1},new int[]{0,0,0,0,0});actor.connect();pose=actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==5,"lava-obsidian-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();require(++column<=15,"water column exceeded lava-obsidian-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();column++;}
   waterAdjFloor=place(actor,top,BlockFace.WEST,1);for(BlockFace wall:new BlockFace[]{BlockFace.NORTH,BlockFace.SOUTH,BlockFace.EAST})place(actor,place(actor,top,wall,1),BlockFace.UP,1);place(actor,place(actor,waterAdjFloor,BlockFace.NORTH,1),BlockFace.UP,1);place(actor,place(actor,waterAdjFloor,BlockFace.SOUTH,1),BlockFace.UP,1);place(actor,place(actor,waterAdjFloor,BlockFace.WEST,1),BlockFace.UP,1);
   southFloor=place(actor,place(actor,top,BlockFace.SOUTH,1),BlockFace.SOUTH,1);southWaterFloor=place(actor,southFloor,BlockFace.EAST,1);place(actor,place(actor,southFloor,BlockFace.WEST,1),BlockFace.UP,1);place(actor,place(actor,southFloor,BlockFace.SOUTH,1),BlockFace.UP,1);place(actor,place(actor,southWaterFloor,BlockFace.NORTH,1),BlockFace.UP,1);place(actor,place(actor,southWaterFloor,BlockFace.SOUTH,1),BlockFace.UP,1);place(actor,place(actor,southWaterFloor,BlockFace.EAST,1),BlockFace.UP,1);place(actor,place(actor,top,BlockFace.SOUTH,1),BlockFace.EAST,1);
   while(pose.y()>top.y()+1.01D)pose=actor.moveAndObserve(0D,-1D,0D,1).resulting();
   adjLava=BlockFace.UP.adjacent(top);adjWater=BlockFace.UP.adjacent(waterAdjFloor);southLava=BlockFace.UP.adjacent(southFloor);southWater=BlockFace.UP.adjacent(southWaterFloor);
   RemoteWorldView empty=actor.sustainTicks(5);require(empty.blockAt(adjLava.x(),adjLava.y(),adjLava.z()).equals(air)&&empty.blockAt(adjWater.x(),adjWater.y(),adjWater.z()).equals(air)&&empty.blockAt(southLava.x(),southLava.y(),southLava.z()).equals(air)&&empty.blockAt(southWater.x(),southWater.y(),southWater.z()).equals(air),"empty lava-obsidian-set basins drift");
   pose=actor.moveAndObserve(0D,1D,0D,1).resulting();pose=actor.moveAndObserve(0D,0D,1D,1).resulting();
   actor.selectHeldSlot(1);pour(actor,top,BlockFace.UP,180F,70F,stillLava);require(actor.health()==20,"west lava-bucket place hurt");
   pose=actor.moveAndObserve(-1D,0D,0D,1).resulting();actor.selectHeldSlot(3);pour(actor,waterAdjFloor,BlockFace.UP,180F,70F,stillWater);actor.awaitBlock(adjLava,obsidian);RemoteWorldView west=actor.sustainTicks(5);require(west.blockAt(adjLava.x(),adjLava.y(),adjLava.z()).equals(obsidian)&&water(west.blockAt(adjWater.x(),adjWater.y(),adjWater.z()).legacyId()),"west lava-source obsidian drift");
   pose=actor.moveAndObserve(1D,0D,0D,1).resulting();actor.selectHeldSlot(2);pour(actor,southFloor,BlockFace.UP,0F,70F,stillLava);require(actor.health()==20,"south lava-bucket place hurt");
   pose=actor.moveAndObserve(1D,0D,0D,1).resulting();actor.selectHeldSlot(4);pour(actor,southWaterFloor,BlockFace.UP,0F,70F,stillWater);actor.awaitBlock(southLava,obsidian);RemoteWorldView south=actor.sustainTicks(5);require(south.blockAt(southLava.x(),southLava.y(),southLava.z()).equals(obsidian)&&water(south.blockAt(southWater.x(),southWater.y(),southWater.z()).legacyId())&&actor.health()==20,"south lava-source obsidian drift");
   actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);
   require(after.blockAt(local(adjLava.x(),cx),adjLava.y(),local(adjLava.z(),cz)).equals(obsidian)&&after.blockAt(local(adjWater.x(),cx),adjWater.y(),local(adjWater.z(),cz)).equals(stillWater)&&after.blockAt(local(southLava.x(),cx),southLava.y(),local(southLava.z(),cz)).equals(obsidian)&&after.blockAt(local(southWater.x(),cx),southWater.y(),local(southWater.z(),cz)).equals(stillWater),"persisted lava-obsidian-set drift");
   String evidence="column="+column+",floor="+top.x()+":"+top.y()+":"+top.z()+":1:0,adjacent="+adjLava.x()+":"+adjLava.y()+":"+adjLava.z()+":11:0->49:0,water-adj="+adjWater.x()+":"+adjWater.y()+":"+adjWater.z()+":0:0->9:0,south="+southLava.x()+":"+southLava.y()+":"+southLava.z()+":11:0->49:0,water-south="+southWater.x()+":"+southWater.y()+":"+southWater.z()+":0:0->9:0,held-lava=327,held-water=326,obsidian=2,persisted=true,clients=2,disconnect=clean";
   String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+lava-bucket327+water-bucket326|cause=packet15-dir255-bucket327-west+packet15-dir255-bucket326-west+packet15-dir255-bucket327-south+packet15-dir255-bucket326-south|wire=packet53-lava11+packet53-water9+packet53-obsidian49+packet53-lava11+packet53-water9+packet53-obsidian49|oracle=live-west-11to49+live-south-11to49+fresh-login-two-obsidian|"+evidence;
   System.out.println("WORLDLINE_M414_SET="+evidence);System.out.println("WORLDLINE_M414_TRACE="+trace);System.out.println("WORLDLINE_M414_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static void pour(B173WireClient a,BlockPosition support,BlockFace face,float yaw,float pitch,BlockState expect)throws Exception{a.look(yaw,pitch);a.useHeldItemOnBlock(support,face);a.useSelectedItemInAir();a.awaitBlock(face.adjacent(support),expect);}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic lava-obsidian-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
