package worldline.smoke.sheepshearedpersistenceb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Freezes EntitySheep color/sheared metadata and persisted Sheared mutation against the official server. */
public final class SheepShearedPersistenceSmoke{
 private static final RemoteItemStack RED_WOOL=new RemoteItemStack(35,1,14);private SheepShearedPersistenceSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SheepShearedPersistenceSmoke server.jar workspace port seed username chunkX chunkZ");Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(120);require(seed==17320110707L&&user.equals("Sheared506")&&user.length()<=16,"M506 identity drift");B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top=null,firstSpawner=null,secondSpawner=null;int column=0;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4},new int[]{1,2,52,351,359},new int[]{32,48,2,8,1},new int[]{0,0,0,1,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==5,"M506 setup inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);actor.selectHeldSlot(0);while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded M506 fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}actor.selectHeldSlot(1);for(int x=-2;x<=2;x++)for(int z=-2;z<=2;z++)if(x!=0||z!=0)grass(actor,new BlockPosition(top.x()+x-(x>0?1:0),top.y(),top.z()+z-(z>0?1:0)),x<0?BlockFace.WEST:x>0?BlockFace.EAST:z<0?BlockFace.NORTH:BlockFace.SOUTH);actor.selectHeldSlot(2);firstSpawner=place(actor,top,BlockFace.UP,52);secondSpawner=place(actor,firstSpawner,BlockFace.EAST,52);actor.close();awaitPlayers(server,0);server.save();}finally{actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.twoSheep(workspace,firstSpawner);server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();actor.awaitInventory();RemoteMobSpawn red=actor.awaitMobSpawn(91),control=actor.awaitMobSpawn(91);dye(actor,red,1);require(B173SheepStateAccess.awaitMetadata(actor,red.entityId(),14)==14,"red sheep color metadata absent");RemoteDroppedItem before=actor.peekDroppedItem(RED_WOOL);shear(actor,red);require(B173SheepStateAccess.awaitMetadata(actor,red.entityId(),30)==30,"red sheep sheared metadata absent");RemoteDroppedItem after=worldline.test.WorldlineSmokeAwait.awaitEntity(actor,()->actor.peekDroppedItem(RED_WOOL),value->value!=null&&(before==null||value.entityId()!=before.entityId()),"initial red wool",10);require(after!=null&&B173SheepStateAccess.metadata(actor,control.entityId())==0,"initial red wool or white control absent");actor.close();awaitPlayers(server,0);server.save();}finally{actor.close();server.close();}
  Thread.sleep(1000L);server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();actor.awaitInventory();RemoteMobSpawn a0=actor.awaitMobSpawn(91),a1=actor.awaitMobSpawn(91),red=meta(actor,a0)==30?a0:a1,control=red==a0?a1:a0;require(meta(actor,red)==30&&meta(actor,control)==0,"persisted sheared/control metadata drift");RemoteDroppedItem before=actor.peekDroppedItem(RED_WOOL);shear(actor,red);worldline.test.WorldlineSmokeAwait.observe(actor,20);RemoteDroppedItem after=actor.peekDroppedItem(RED_WOOL);require(meta(actor,red)==30&&same(before,after),"already-sheared sheep emitted second wool");actor.close();awaitPlayers(server,0);server.save();}finally{actor.close();server.close();}
  int changed=B173SheepNbtAccess.unshearRed(workspace,cx,cz);Thread.sleep(1000L);server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();actor.awaitInventory();RemoteMobSpawn a0=actor.awaitMobSpawn(91),a1=actor.awaitMobSpawn(91),red=meta(actor,a0)==14?a0:a1,control=red==a0?a1:a0;require(meta(actor,red)==14&&meta(actor,control)==0,"mutated unsheared/control metadata drift");RemoteDroppedItem before=actor.peekDroppedItem(RED_WOOL);shear(actor,red);require(B173SheepStateAccess.awaitMetadata(actor,red.entityId(),30)==30,"mutated sheep did not shear");RemoteDroppedItem after=worldline.test.WorldlineSmokeAwait.awaitEntity(actor,()->actor.peekDroppedItem(RED_WOOL),value->value!=null&&(before==null||value.entityId()!=before.entityId()),"mutated red wool",10);require(after!=null,"mutated sheep emitted no new red wool");
   String evidence="column="+column+",platform=5x5-grass,spawners="+cell(firstSpawner)+"+"+cell(secondSpawner)+",mobs=type91+type91,red=14->30,persisted=30,control=0,repeat=no-new-wool,nbt.Sheared=1->0,mutated=14->30,changed="+changed+",clients=3,restarts=3";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-grass+two-sheep-spawners|cause=dye351:1+shears359+save-restart+nbt-Sheared-mutation|wire=packet24-index16+packet40-index16+packet21-wool35:14|oracle=red14+sheared30+white0+persistence+mutation|"+evidence;System.out.println("WORLDLINE_M506_SET="+evidence);System.out.println("WORLDLINE_M506_TRACE="+trace);System.out.println("WORLDLINE_M506_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static void dye(B173WireClient a,RemoteMobSpawn mob,int damage){int slot=find(a.inventory(),351,damage);require(slot>=36,"red dye absent");a.selectHeldSlot(slot-36);approach(a,mob);B173ShearsAccess.dyeMob(a,mob.entityId());worldline.test.WorldlineSmokeAwait.observe(a,5);}private static void shear(B173WireClient a,RemoteMobSpawn mob){int slot=find(a.inventory(),359,-1);require(slot>=36,"shears absent");a.selectHeldSlot(slot-36);approach(a,mob);B173ShearsAccess.useOnMob(a,mob.entityId());worldline.test.WorldlineSmokeAwait.observe(a,5);}private static int meta(B173WireClient a,RemoteMobSpawn m){return B173SheepStateAccess.metadata(a,m.entityId());}private static boolean same(RemoteDroppedItem a,RemoteDroppedItem b){return a==null?b==null:b!=null&&a.entityId()==b.entityId();}
 private static int find(RemoteInventoryView view,int id,int damage){for(int slot=36;slot<=44;slot++)if(!view.slot(slot).empty()&&view.slot(slot).item().legacyId()==id&&(damage<0||view.slot(slot).item().damage()==damage))return slot;return -1;}private static void approach(B173WireClient a,RemoteMobSpawn mob){for(int step=0;step<16;step++){PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=mob.x()-here.x(),dy=mob.y()+1D-here.y(),dz=mob.z()-1.5D-here.z(),d=Math.sqrt(dx*dx+dy*dy+dz*dz);if(d<=2.5D)return;double s=Math.min(1D,9D/d);a.moveAndObserve(dx*s,dy*s,dz*s,2);}}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic M506 foundation");}
 private static String cell(BlockPosition p){return p.x()+":"+p.y()+":"+p.z();}private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long end=System.currentTimeMillis()+5000L;while(System.currentTimeMillis()<end){if(s.players().size()==n)return;Thread.sleep(100L);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
