import java.io.*;import java.net.ServerSocket;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.util.*;import java.util.stream.*;
/** Repeats one official chain-boots equip, peer Packet5, and persist. */
public final class ChainBootsCycle{
 private static final String ID="m273-chain-boots";private final Path root=Paths.get("").toAbsolutePath().normalize(),smoke=root.resolve("smokes").resolve(ID),build=root.resolve(".worldline/smokes").resolve(ID);private final Properties config=new Properties(),artifact=new Properties();
 public static void main(String[]a){if(!Arrays.equals(a,new String[]{ID})){System.err.println("usage: java tools/smoke/ChainBootsCycle.java "+ID);System.exit(2);}try{new ChainBootsCycle().execute();}catch(Exception e){System.err.println("chain boots failed: "+e.getMessage());System.exit(1);}}
 private void execute()throws Exception{load(smoke.resolve("smoke.properties"),config);load(root.resolve("artifacts/minecraft-b1.7.3-server.properties"),artifact);require(ID.equals(value(config,"id"))&&value(config,"server.jar.sha256").equals(value(artifact,"expected.sha256")),"descriptor drift");require(value(config,"username").equals("ChainBoot273")&&value(config,"username").length()<=16,"actor username drift");Path official=root.resolve(value(artifact,"local.path")).normalize();verifyArtifact(official);recreate(build);Path classes=compile();Outcome first=run(classes,official,build.resolve("first")),second=run(classes,official,build.resolve("second"));require(first.signal.equals(second.signal)&&first.trace.equals(second.trace)&&first.signature.equals(second.signature),"fresh chain boots results diverged");String expected=value(config,"expected.signature");if(expected.equals("pending")||Boolean.getBoolean("worldline.m273.diagnostic")){System.out.println("FROZEN");System.out.println("  "+first.signal);System.out.println("  signature: "+first.signature);return;}require(first.signal.equals(value(config,"expected.signal"))&&first.signature.equals(expected),"M273 frozen evidence drift");Files.writeString(build.resolve("evidence.txt"),"id="+ID+"\nservers=2\nclients=4\nfirst="+first.signal+"\nsecond="+second.signal+"\ntrace="+first.trace+"\nsignature="+first.signature+"\n",StandardCharsets.UTF_8);System.out.println("FROZEN");System.out.println("  "+first.signal);System.out.println("  signature: "+first.signature);}
 private Outcome run(Path classes,Path official,Path workspace)throws Exception{Exception last=null;for(int attempt=0;attempt<2;attempt++){try{if(Files.exists(workspace))recreate(workspace);String output=capture(root,Arrays.asList("java","-classpath",classes.toString(),"worldline.smoke.chainbootsb173.ChainBootsSmoke",official.toString(),workspace.toString(),Integer.toString(freePort()),value(config,"seed"),value(config,"username"),value(config,"observer")));return new Outcome(line(output,"WORLDLINE_M273_TRACE="),line(output,"WORLDLINE_M273_SIGNATURE="),line(output,"WORLDLINE_M273_BOOTS="));}catch(Exception e){last=e;if(attempt==0&&eof(e)){Thread.sleep(5000L);continue;}throw e;}}throw last;}
 private Path compile()throws Exception{Path output=build.resolve("adapter-classes");Files.createDirectories(output);List<String>command=new ArrayList<>(Arrays.asList("javac","-encoding","UTF-8","--release","8","-Xlint:all,-options","-Werror","-d",output.toString()));command.addAll(javaFiles(root.resolve("modules/api/src/main/java")));command.addAll(javaFiles(root.resolve("adapters/b173-server/src/main/java")));command.addAll(javaFiles(smoke.resolve("src")));capture(root,command);return output;}
 private void verifyArtifact(Path p)throws Exception{SmokeSupport.verifyArtifact(p,artifact);}private List<String>javaFiles(Path s)throws IOException{return SmokeSupport.javaFiles(s);}private String capture(Path d,List<String>c)throws Exception{return SmokeSupport.capture(d,c);}private void recreate(Path t)throws IOException{SmokeSupport.recreate(root,t);}private void load(Path p,Properties t)throws IOException{SmokeSupport.load(p,t);}private String value(Properties p,String k){return SmokeSupport.value(p,k);}private String digest(Path p,String a)throws Exception{return SmokeSupport.digest(p,a);}private int freePort()throws IOException{return SmokeSupport.freePort();}private String line(String o,String p){return SmokeSupport.line(o,p);}private static boolean eof(Exception e){return SmokeSupport.eof(e);}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static final class Outcome{final String trace,signature,signal;Outcome(String t,String s,String l){trace=t;signature=s;signal=l;}}
}
