import java.io.*;
import java.net.ServerSocket;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.util.stream.*;

/** Runs two fresh, same-plan direct renderer/Aero stage timing replicas. */
public final class DirectStageTimingCycle {
    private static final String ID="m77-direct-stage-timing";
    private final Path root=Paths.get("").toAbsolutePath().normalize(),smoke=root.resolve("smokes").resolve(ID),build=root.resolve(".worldline/smokes").resolve(ID);private final Properties config=new Properties();
    public static void main(String[]a){if(!Arrays.equals(a,new String[]{ID})){System.err.println("usage: java tools/smoke/DirectStageTimingCycle.java "+ID);System.exit(2);}try{new DirectStageTimingCycle().execute();}catch(Exception e){System.err.println("Direct stage timing failed: "+e.getMessage());System.exit(1);}}
    private void execute()throws Exception{load(smoke.resolve("smoke.properties"),config);require(value("replicas").equals("2")&&value("warmup.frames").equals("300")&&value("warmup.millis").equals("5000")&&value("minimum.frames").equals("720")&&value("minimum.millis").equals("12000")&&value("fps.limit").equals("0")&&value("aero.frame.pacing").equals("false"),"M77 design drift");
        Path checkout=root.resolve(value("aero.path")).normalize();verifyCheckout(checkout);verifyBoundary();recreate(build);buildAero(checkout);boolean diagnostic=Boolean.getBoolean("worldline.m77.diagnostic");int runs=diagnostic?1:2,nonce=7707701;List<Arm>arms=new ArrayList<>();Plan plan=null;
        for(int i=0;i<runs;i++){verifyCheckout(checkout);Path workspace=build.resolve("replica-"+(i+1));Arm arm=run(checkout,workspace,i,nonce,plan);arms.add(arm);if(plan==null)plan=new Plan(arm.x,arm.y,arm.z);verifyCheckout(checkout);}
        if(diagnostic){System.out.println("M77 diagnostic replica passed; qualification not attempted");System.out.println("  "+arms.get(0).summary());return;}Arm first=arms.get(0),second=arms.get(1);require(first.nonce==second.nonce&&first.x==second.x&&first.y==second.y&&first.z==second.z&&first.raw==second.raw,"replica fixture drift");
        String trace="v1|design=2-fresh-same-plan-nonce-replicas|fixture=constant16-synced-aero+exact-camera|frame-limit=vanilla-max0+aero-pacer-off-runtime-gated"
            +"|timers=renderer+queueAtRest+flush-synchronous-nanoTime-primitive|window=M74-min720intervals+12s|capture=no-retained-allocation-io+post-seal-sidecar"
            +"|per-record=renderer16+queue16+flush2+state16/maskffff|clock=zero-flush-spans-preserved+series-positive|stats=descriptive-direct-spans-dynamic|uninstrumented-cost-causality-regression-historical-lag=not-claimed|shutdown=clean";
        String signature=sha256(trace);require(signature.equals(value("expected.signature")),"M77 signature drift: "+signature);Files.writeString(build.resolve("evidence.txt"),"id="+ID+"\nreplicas=2\nserver.jvm=2\nclient.jvm=2\nfirst="+first.summary()+"\nsecond="+second.summary()+"\ntrace="+trace+"\nsignature="+signature+"\n",StandardCharsets.UTF_8);System.out.println("M77 direct stage timing passed");System.out.println("  first: "+first.summary());System.out.println("  second: "+second.summary());System.out.println("  signature: "+signature);}
    private Arm run(Path checkout,Path workspace,int replica,int nonce,Plan plan)throws Exception{Files.createDirectories(workspace);int port=freePort(),timeout=Integer.parseInt(value("timeout.seconds"));Path base=root.resolve(".worldline/worktrees/m77-"+ProcessHandle.current().pid()+"-"+replica+"-"+System.nanoTime()),serverTree=base.resolve("server"),clientTree=base.resolve("client");Captured server=null;
        try{addWorktree(checkout,serverTree);addWorktree(checkout,clientTree);Path init=root.resolve(value("runner")),serverGame=workspace.resolve("server"),clientGame=workspace.resolve("client"),censusFile=clientGame.resolve("census.bin"),stageFile=clientGame.resolve("stages.bin");server=startServer(serverTree.resolve("stationapi/test-bare"),command(serverTree,init,"server",serverGame,port,nonce,null,null,plan),timeout);String client=runGradle(clientTree.resolve("stationapi/test-bare"),command(clientTree,init,"client",clientGame,port,nonce,censusFile,stageFile,null),timeout);Files.writeString(workspace.resolve("client-output.txt"),client);
            require(client.contains("Loading 46 mods:")&&client.contains("- aero-model-lib 3.0.0")&&client.contains("- worldline-m74-content 1.0.0")&&client.contains("BUILD SUCCESSFUL")&&client.contains("[WorldlineCensus] packet1")&&client.contains("[WorldlineCensus] packet13")&&!client.contains("[Aero_"),"client boundary drift\n"+diagnostic(client));require(count(client,"[WorldlineStage] armed ")==1&&unique(client,"[WorldlineStage] armed ").equals("fpsLimit=0 aeroFramePacing=false")&&count(client,"[WorldlineCensus] plan-ready")==1&&count(client,"[WorldlineCensus] census-start ")==1&&count(client,"[WorldlineCensus] complete ")==1&&count(client,"[WorldlineStage] complete ")==1,"client lifecycle drift");
            Census census=parseCensus(censusFile,nonce);Stage stage=parseStage(stageFile,census,nonce);String complete=unique(client,"[WorldlineStage] complete ");require(marker(complete,"samples")==stage.count&&marker(complete,"bytes")==Files.size(stageFile)&&token(complete,"sha256").equals(sha256(Files.readAllBytes(stageFile))),"stage marker drift");server.write("save-all\nstop\n");server.finish(45);String serverText=server.output();Files.writeString(workspace.resolve("server-output.txt"),serverText);server=null;require((serverText.contains("Loading 39 mods:")||serverText.contains("Loading 40 mods:"))&&serverText.contains("- worldline-m74-content 1.0.0")&&!serverText.contains("- aero-model-lib ")&&serverText.contains("BUILD SUCCESSFUL"),"server boundary drift\n"+diagnostic(serverText));String scene=unique(serverText,"[WorldlineCensus] scene ");require(token(scene,"mode").equals("present")&&marker(scene,"planned")==16&&marker(scene,"placed")==16&&marker(scene,"yaw")==-90&&marker(scene,"pitch")==0&&marker(scene,"nonce")==nonce,"scene drift: "+scene);int x=marker(scene,"x"),y=marker(scene,"baseY"),z=marker(scene,"baseZ"),raw=marker(scene,"raw");require((plan==null||plan.x==x&&plan.y==y&&plan.z==z)&&census.x==x&&census.y==y&&census.z==z,"replica plan drift");require(serverText.indexOf("[WorldlineCensus] activation ")<serverText.indexOf("[WorldlineCensus] tracking-ready ")&&serverText.indexOf("[WorldlineCensus] tracking-ready ")<serverText.indexOf("[WorldlineCensus] scene ")&&serverText.contains(value("username")+" lost connection")&&serverText.contains("Stopping server"),"server lifecycle drift");verifyWorktree(serverTree);verifyWorktree(clientTree);return new Arm(nonce,x,y,z,raw,census,stage,sha256(Files.readAllBytes(censusFile)),sha256(Files.readAllBytes(stageFile)));
        }finally{if(server!=null){try{server.write("stop\n");server.finish(20);}catch(Exception e){server.kill();}finally{Files.writeString(workspace.resolve("server-output.txt"),server.output());}}removeWorktree(checkout,clientTree);removeWorktree(checkout,serverTree);}}
    private Census parseCensus(Path file,int nonce)throws Exception{byte[]bytes=Files.readAllBytes(file);try(DataInputStream in=new DataInputStream(new ByteArrayInputStream(bytes))){require(in.readInt()==0x574c3734&&in.readInt()==1&&in.readInt()==28&&in.readInt()==16&&in.readInt()==nonce,"census schema drift");int x=in.readInt(),y=in.readInt(),z=in.readInt();require(in.readInt()==720&&in.readLong()==12_000_000_000L,"census window drift");int count=in.readInt();long elapsed=in.readLong();require(count>=720&&count<=65536&&bytes.length==56L+count*28L,"census length drift");long sum=0;long[]frames=new long[count];for(int i=0;i<count;i++){long delta=in.readLong();int renders=in.readInt(),lists=in.readInt(),visible=in.readInt(),calls=in.readInt(),state=in.readUnsignedShort(),mask=in.readUnsignedShort();require(delta>0&&renders==16&&lists==16&&visible>0&&calls==16&&state==0x1010&&mask==0xffff,"census record drift at "+i);frames[i]=delta;sum=Math.addExact(sum,delta);}require(in.read()==-1&&sum==elapsed&&elapsed>=12_000_000_000L,"census aggregate drift");return new Census(x,y,z,count,elapsed,frames);}}
    private Stage parseStage(Path file,Census census,int nonce)throws Exception{byte[]bytes=Files.readAllBytes(file);try(DataInputStream in=new DataInputStream(new ByteArrayInputStream(bytes))){require(in.readInt()==0x574c3737&&in.readInt()==1&&in.readInt()==44&&in.readInt()==32&&in.readInt()==nonce,"stage schema drift");int x=in.readInt(),y=in.readInt(),z=in.readInt(),count=in.readInt();long elapsed=in.readLong();require(x==census.x&&y==census.y&&z==census.z&&count==census.count&&elapsed==census.elapsed&&bytes.length==44L+count*32L,"stage/census identity drift");long[]renderer=new long[count],queue=new long[count],flush=new long[count];int minFlush=Integer.MAX_VALUE,maxFlush=0,zeroFlush=0;long flushSum=0;for(int i=0;i<count;i++){renderer[i]=in.readLong();queue[i]=in.readLong();flush[i]=in.readLong();int rc=in.readUnsignedShort(),qc=in.readUnsignedShort(),fc=in.readUnsignedShort(),reserved=in.readUnsignedShort();require(renderer[i]>0&&queue[i]>0&&flush[i]>=0&&renderer[i]>=queue[i]&&rc==16&&qc==16&&fc==2&&reserved==0,"stage record drift at "+i+" values="+renderer[i]+"/"+queue[i]+"/"+flush[i]+" calls="+rc+"/"+qc+"/"+fc);if(flush[i]==0)zeroFlush++;flushSum=Math.addExact(flushSum,flush[i]);minFlush=Math.min(minFlush,fc);maxFlush=Math.max(maxFlush,fc);}require(in.read()==-1&&flushSum>0,"stage aggregate drift");return new Stage(count,renderer,queue,flush,minFlush,maxFlush,zeroFlush);}}
    private List<String>command(Path tree,Path init,String role,Path game,int port,int nonce,Path census,Path stage,Plan plan){String wrapper=System.getProperty("os.name").startsWith("Windows")?"gradlew.bat":"gradlew";List<String>r=new ArrayList<>(Arrays.asList(tree.resolve("stationapi/test-bare").resolve(wrapper).toString(),"--no-daemon","--init-script",init.toString(),role.equals("server")?"runServer":"runClient","-PworldlineRole="+role,"-PworldlineRunDir="+game,"-PworldlinePort="+port,"-PworldlineNonce="+nonce));if(plan!=null)r.addAll(Arrays.asList("-PworldlinePlanX="+plan.x,"-PworldlinePlanY="+plan.y,"-PworldlinePlanZ="+plan.z));if(census!=null)r.addAll(Arrays.asList("-PworldlineArtifact="+census,"-PworldlineStageArtifact="+stage,"-PworldlineUsername="+value("username"),"-PworldlineWarmupFrames="+value("warmup.frames"),"-PworldlineWarmupMillis="+value("warmup.millis"),"-PworldlineMinimumFrames="+value("minimum.frames"),"-PworldlineMinimumMillis="+value("minimum.millis"),"-PworldlineFpsLimit="+value("fps.limit"),"-PworldlineAeroFramePacing="+value("aero.frame.pacing")));return r;}
    private void buildAero(Path checkout)throws Exception{Path tree=root.resolve(".worldline/worktrees/m77-build-"+System.nanoTime());try{addWorktree(checkout,tree);Path stationapi=tree.resolve("stationapi");String wrapper=System.getProperty("os.name").startsWith("Windows")?"gradlew.bat":"gradlew",output=runGradle(stationapi,Arrays.asList(stationapi.resolve(wrapper).toString(),"--no-daemon","remapJar"),Integer.parseInt(value("timeout.seconds")));Path jar=stationapi.resolve("build/libs/aero-model-lib-3.0.0.jar");require(output.contains("BUILD SUCCESSFUL")&&Files.isRegularFile(jar),"Aero build failed");Files.copy(jar,build.resolve("aero-model-lib-3.0.0.jar"),StandardCopyOption.REPLACE_EXISTING);verifyWorktree(tree);}finally{removeWorktree(checkout,tree);}}
    private Captured startServer(Path d,List<String>c,int t)throws Exception{Captured s=Captured.start(d,c);s.awaitText("Done (",t);return s;}private String runGradle(Path d,List<String>c,int t)throws Exception{return Captured.run(d,c,t);}private void verifyBoundary()throws IOException{for(Path base:Arrays.asList(root.resolve("smokes/m74-complete-aero-census/runtime-src/worldline/m74"),smoke.resolve("runtime-src/worldline/m74")))try(Stream<Path>p=Files.walk(base)){for(Path f:p.filter(x->x.toString().endsWith(".java")).filter(x->!x.toString().contains(File.separator+"client"+File.separator)).filter(x->!x.toString().contains(File.separator+"mixin"+File.separator)).collect(Collectors.toList())){String s=Files.readString(f);require(!s.contains("aero.modellib")&&!s.contains("net.minecraft.client")&&!s.contains("org.lwjgl"),"server closure imports client code");}}}
    private void verifyCheckout(Path c)throws Exception{require(git(c,"remote","get-url","origin").trim().equals(value("aero.repository"))&&git(c,"rev-parse","HEAD").trim().equals(value("aero.revision"))&&git(c,"status","--porcelain","--untracked-files=all").trim().isEmpty(),"Aero checkout drift");}private void addWorktree(Path c,Path t)throws Exception{Files.createDirectories(t.getParent());git(c,"worktree","add","--detach",t.toString(),value("aero.revision"));verifyWorktree(t);}private void verifyWorktree(Path t)throws Exception{require(git(t,"rev-parse","HEAD").trim().equals(value("aero.revision"))&&git(t,"status","--porcelain","--untracked-files=all").trim().isEmpty(),"worktree drift");}
    private void removeWorktree(Path c,Path t){try{if(registered(c,t))try{git(c,"worktree","remove","--force",t.toString());}catch(Exception e){if(registered(c,t))throw e;}if(Files.exists(t)){Path allowed=root.resolve(".worldline/worktrees").normalize(),exact=t.toAbsolutePath().normalize();require(exact.startsWith(allowed)&&!exact.equals(allowed),"unsafe remainder");try(Stream<Path>p=Files.walk(exact)){for(Path f:p.sorted(Comparator.reverseOrder()).collect(Collectors.toList()))Files.deleteIfExists(f);}}}catch(Exception e){throw new IllegalStateException("M77 cleanup failed "+t,e);}}private boolean registered(Path c,Path t)throws Exception{return Arrays.stream(git(c,"worktree","list","--porcelain").split("\\R")).anyMatch(x->x.startsWith("worktree ")&&Paths.get(x.substring(9)).toAbsolutePath().normalize().equals(t.toAbsolutePath().normalize()));}private String git(Path d,String...a)throws Exception{List<String>c=new ArrayList<>();c.add("git");c.add("-C");c.add(d.toString());c.addAll(Arrays.asList(a));return Captured.run(root,c,60);}
    private String unique(String s,String p){List<String>r=s.lines().filter(x->x.startsWith(p)).collect(Collectors.toList());require(r.size()==1,"marker drift "+p);return r.get(0).substring(p.length());}private int marker(String r,String n){return Integer.parseInt(token(r,n));}private String token(String r,String n){for(String t:r.split(" +"))if(t.startsWith(n+"="))return t.substring(n.length()+1);throw new IllegalStateException("missing "+n);}private long count(String s,String p){return s.lines().filter(x->x.startsWith(p)).count();}
    private int freePort()throws IOException{return SmokeSupport.freePort();}private void recreate(Path t)throws IOException{if(Files.exists(t))try(Stream<Path>p=Files.walk(t)){for(Path f:p.sorted(Comparator.reverseOrder()).collect(Collectors.toList()))Files.delete(f);}Files.createDirectories(t);}private void load(Path p,Properties v)throws IOException{try(Reader r=Files.newBufferedReader(p)){v.load(r);}}private String value(String k){String r=config.getProperty(k);require(r!=null&&!r.trim().isEmpty(),"missing "+k);return r.trim();}private String diagnostic(String s){return s.lines().filter(x->x.contains("WorldlineCensus")||x.contains("WorldlineStage")||x.contains("Loading ")||x.contains("Exception")||x.contains("BUILD ")).collect(Collectors.joining("\n"));}
    private static String sha256(String v)throws Exception{return sha256(v.getBytes(StandardCharsets.UTF_8));}private static String sha256(byte[]v)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v));}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static long q(long[]v,double q){long[]c=v.clone();Arrays.sort(c);return c[(int)Math.ceil(c.length*q)-1];}
    private static final class Plan{final int x,y,z;Plan(int x,int y,int z){this.x=x;this.y=y;this.z=z;}}private static final class Census{final int x,y,z,count;final long elapsed;final long[]frames;Census(int x,int y,int z,int n,long e,long[]f){this.x=x;this.y=y;this.z=z;count=n;elapsed=e;frames=f;}}
    private static final class Stage{final int count,minFlush,maxFlush,zeroFlush;final long[]renderer,queue,flush;Stage(int n,long[]r,long[]q,long[]f,int min,int max,int zero){count=n;renderer=r;queue=q;flush=f;minFlush=min;maxFlush=max;zeroFlush=zero;}String summary(){return "rendererNs="+q(renderer,.5)+"/"+q(renderer,.95)+"/"+q(renderer,.99)+"/"+Arrays.stream(renderer).max().orElseThrow()+",queueNs="+q(queue,.5)+"/"+q(queue,.95)+"/"+q(queue,.99)+"/"+Arrays.stream(queue).max().orElseThrow()+",flushNs="+q(flush,.5)+"/"+q(flush,.95)+"/"+q(flush,.99)+"/"+Arrays.stream(flush).max().orElseThrow()+",flushCalls="+minFlush+"-"+maxFlush+",flushZero="+zeroFlush;}}
    private static final class Arm{final int nonce,x,y,z,raw;final Census census;final Stage stage;final String censusHash,stageHash;Arm(int n,int x,int y,int z,int raw,Census c,Stage s,String ch,String sh){nonce=n;this.x=x;this.y=y;this.z=z;this.raw=raw;census=c;stage=s;censusHash=ch;stageHash=sh;}String summary(){return "samples="+census.count+","+stage.summary()+",census="+censusHash.substring(0,12)+",stages="+stageHash.substring(0,12);}}
    private static final class Captured{final Process p;final StringBuilder text=new StringBuilder();final Thread reader;int exit=-1;private Captured(Process p){this.p=p;reader=new Thread(()->{try(BufferedReader in=new BufferedReader(new InputStreamReader(p.getInputStream(),StandardCharsets.UTF_8))){String l;while((l=in.readLine())!=null)synchronized(text){text.append(l).append('\n');text.notifyAll();}}catch(IOException e){}});reader.setDaemon(true);reader.start();}static Captured start(Path d,List<String>c)throws IOException{return new Captured(new ProcessBuilder(c).directory(d.toFile()).redirectErrorStream(true).start());}static String run(Path d,List<String>c,int t)throws Exception{Captured v=start(d,c);v.finish(t);require(v.exit==0,"process failed\n"+v.output());return v.output();}void write(String v)throws IOException{p.getOutputStream().write(v.getBytes(StandardCharsets.UTF_8));p.getOutputStream().flush();}void awaitText(String v,int t)throws Exception{long end=System.currentTimeMillis()+t*1000L;synchronized(text){while(!text.toString().contains(v)&&p.isAlive()&&System.currentTimeMillis()<end)text.wait(100);}require(output().contains(v),"missing "+v+"\n"+output());}void finish(int t)throws Exception{if(!p.waitFor(t,TimeUnit.SECONDS)){kill();throw new IllegalStateException("process timeout\n"+output());}exit=p.exitValue();reader.join(5000);require(exit==0,"process exit "+exit+"\n"+output());}void kill(){p.descendants().forEach(ProcessHandle::destroyForcibly);p.destroyForcibly();}String output(){synchronized(text){return text.toString();}}}
}
