import java.io.*;import java.net.ServerSocket;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.util.*;import java.util.stream.*;
/** Repeats three official environmental Packet8 health drops: drowning, suffocation, lava. */
public final class EnvDamageCycle{
 private static final String ID="m307-env-damage";private final Path root=Paths.get("").toAbsolutePath().normalize(),smoke=root.resolve("smokes").resolve(ID),build=root.resolve(".worldline/smokes").resolve(ID);private final Properties config=new Properties(),artifact=new Properties();
 public static void main(String[]a){if(!Arrays.equals(a,new String[]{ID})){System.err.println("usage: java tools/smoke/EnvDamageCycle.java "+ID);System.exit(2);}try{new EnvDamageCycle().execute();}catch(Exception e){System.err.println("env damage failed: "+e.getMessage());System.exit(1);}}
 private void execute()throws Exception{load(smoke.resolve("smoke.properties"),config);load(root.resolve("artifacts/minecraft-b1.7.3-server.properties"),artifact);require(ID.equals(value(config,"id"))&&value(config,"server.jar.sha256").equals(value(artifact,"expected.sha256")),"descriptor drift");require(value(config,"username").equals("EnvDamage307")&&value(config,"username").length()<=16,"actor username drift");Path official=root.resolve(value(artifact,"local.path")).normalize();verifyArtifact(official);recreate(build);Path classes=compile();Outcome first=run(classes,official,build.resolve("first")),second=run(classes,official,build.resolve("second"));require(first.signal.equals(second.signal)&&first.trace.equals(second.trace)&&first.signature.equals(second.signature),"fresh env damage results diverged");require(first.signal.contains("causes=drown+suffocate+lava")&&first.signal.contains("health=20->"),"env-damage signal missing multiple damage causes");String expected=value(config,"expected.signature");if(expected.equals("pending")||Boolean.getBoolean("worldline.m307.diagnostic")){System.out.println("M307 env damage diagnostic passed; qualification not attempted");System.out.println("  "+first.signal);System.out.println("  trace: "+first.trace);System.out.println("  signature: "+first.signature);return;}require(first.signal.equals(value(config,"expected.signal"))&&first.signature.equals(expected),"M307 frozen evidence drift");Files.writeString(build.resolve("evidence.txt"),"id="+ID+"\nservers=2\nclients=4\nfirst="+first.signal+"\nsecond="+second.signal+"\ntrace="+first.trace+"\nsignature="+first.signature+"\n",StandardCharsets.UTF_8);System.out.println("FROZEN");System.out.println("M307 env damage passed");System.out.println("  "+first.signal);System.out.println("  signature: "+first.signature);}
 private Outcome run(Path classes,Path official,Path workspace)throws Exception{Exception last=null;for(int attempt=0;attempt<2;attempt++){if(attempt>0){System.out.println("M307 retrying one official EOF");recreate(workspace);}try{String output=capture(root,Arrays.asList("java","-classpath",classes+separator()+product("api"),"worldline.smoke.envdamageb173.EnvDamageSmoke",official.toString(),workspace.toString(),Integer.toString(freePort()),value(config,"seed"),value(config,"username"),value(config,"chunk.x"),value(config,"chunk.z")));return new Outcome(line(output,"WORLDLINE_M307_TRACE="),line(output,"WORLDLINE_M307_SIGNATURE="),line(output,"WORLDLINE_M307_DAMAGE="));}catch(Exception e){last=e;SmokeRetryBoundary.afterEofFailure(attempt,1,e);throw e;}}throw last;}
 private Path compile()throws Exception{Path output=build.resolve("adapter-classes");Files.createDirectories(output);List<String>command=new ArrayList<>(Arrays.asList("javac","-encoding","UTF-8","--release","8","-Xlint:all,-options","-Werror","-classpath",product("api").toString(),"-d",output.toString()));command.addAll(javaFiles(root.resolve("adapters/b173-server/src/main/java")));command.addAll(javaFiles(smoke.resolve("src")));capture(root,command);return output;}

 private void verifyArtifact(Path p)throws Exception{ExceptionalSmokeSupport.verifyArtifact(p,artifact);}private List<String>javaFiles(Path s)throws IOException{return ExceptionalSmokeSupport.javaFiles(s);}private String capture(Path d,List<String>c)throws Exception{return ExceptionalSmokeSupport.capture(d,c);}private void recreate(Path t)throws IOException{ExceptionalSmokeSupport.recreate(root,t);}private void load(Path p,Properties t)throws IOException{ExceptionalSmokeSupport.load(p,t);}private String value(Properties p,String k){return ExceptionalSmokeSupport.value(p,k);}private String digest(Path p,String a)throws Exception{return ExceptionalSmokeSupport.digest(p,a);}private int freePort()throws IOException{return ExceptionalSmokeSupport.freePort();}private Path product(String n){return ExceptionalSmokeSupport.product(root,n);}private String separator(){return System.getProperty("path.separator");}private String line(String o,String p){return ExceptionalSmokeSupport.line(o,p);}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static final class Outcome{final String trace,signature,signal;Outcome(String t,String s,String l){trace=t;signature=s;signal=l;}}
}
