import java.io.*;import java.net.ServerSocket;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.util.*;import java.util.stream.*;

/** Qualifies deterministic official terrain at one absolute chunk. */
public final class FixedSeedTerrainCycle {
    private static final String ID="m111-fixed-seed-terrain";private final Path root=Paths.get("").toAbsolutePath().normalize(),smoke=root.resolve("smokes").resolve(ID),build=root.resolve(".worldline/smokes").resolve(ID);private final Properties config=new Properties(),artifact=new Properties();
    public static void main(String[]a){if(!Arrays.equals(a,new String[]{ID})){System.err.println("usage: java tools/smoke/FixedSeedTerrainCycle.java "+ID);System.exit(2);}try{new FixedSeedTerrainCycle().execute();}catch(Exception e){System.err.println("fixed seed terrain failed: "+e.getMessage());System.exit(1);}}
    private void execute()throws Exception{load(smoke.resolve("smoke.properties"),config);load(root.resolve("artifacts/minecraft-b1.7.3-server.properties"),artifact);require(ID.equals(value(config,"id"))&&value(config,"server.jar.sha256").equals(value(artifact,"expected.sha256")),"descriptor drift");Path official=root.resolve(value(artifact,"local.path")).normalize();verifyArtifact(official);recreate(build);Path classes=compile();Outcome first=run(classes,official,build.resolve("first")),second=run(classes,official,build.resolve("second"));require(first.terrain.equals(second.terrain)&&first.trace.equals(second.trace)&&first.signature.equals(second.signature),"fresh fixed-seed terrain diverged\n"+first.terrain+"\n"+second.terrain);boolean diagnostic=Boolean.getBoolean("worldline.m111.diagnostic");if(diagnostic){System.out.println("M111 terrain diagnostic passed; qualification not attempted");System.out.println("  "+first.terrain);System.out.println("  "+second.terrain);return;}require(token(first.terrain,"chunk").equals(value(config,"expected.chunk.x")+":"+value(config,"expected.chunk.z"))&&token(first.terrain,"solid").equals(value(config,"expected.solid"))&&token(first.terrain,"terrain").equals(value(config,"expected.terrain.sha256"))&&token(first.terrain,"surface").equals(value(config,"expected.surface.sha256")),"frozen terrain evidence drift");require(first.signature.equals(value(config,"expected.signature")),"M111 signature drift: "+first.signature);String evidence="id="+ID+"\nservers=2\nclients=2\nserver.sha256="+value(artifact,"expected.sha256")+"\nfirst="+first.terrain+"\nsecond="+second.terrain+"\ntrace="+first.trace+"\nsignature="+first.signature+"\n";Files.writeString(build.resolve("evidence.txt"),evidence,StandardCharsets.UTF_8);System.out.println("M111 fixed seed terrain passed");System.out.println("  "+first.terrain);System.out.println("  signature: "+first.signature);}
    private Outcome run(Path classes,Path official,Path workspace)throws Exception{String output=capture(root,Arrays.asList("java","-classpath",classes+separator()+product("api"),"worldline.smoke.terrainb173.FixedSeedTerrainSmoke",official.toString(),workspace.toString(),Integer.toString(freePort()),value(config,"seed"),value(config,"username"),value(config,"target.chunk.x"),value(config,"target.chunk.z")));return new Outcome(line(output,"WORLDLINE_M111_TRACE="),line(output,"WORLDLINE_M111_SIGNATURE="),line(output,"WORLDLINE_M111_TERRAIN="));}
    private Path compile()throws Exception{Path output=build.resolve("adapter-classes");Files.createDirectories(output);List<String>command=new ArrayList<>(Arrays.asList("javac","-encoding","UTF-8","--release","8","-Xlint:all,-options","-Werror","-classpath",product("api").toString(),"-d",output.toString()));command.addAll(javaFiles(root.resolve("adapters/b173-server/src/main/java")));command.addAll(javaFiles(smoke.resolve("src")));capture(root,command);return output;}
    private void verifyArtifact(Path path)throws Exception{require(Files.isRegularFile(path),"server artifact absent; run Acquire.java server");require(Files.size(path)==Long.parseLong(value(artifact,"expected.bytes"))&&digest(path,"SHA-1").equals(value(artifact,"expected.sha1"))&&digest(path,"SHA-256").equals(value(artifact,"expected.sha256")),"server artifact drift");}
    private List<String>javaFiles(Path source)throws IOException{try(Stream<Path>p=Files.walk(source)){return p.filter(x->x.toString().endsWith(".java")).sorted().map(Path::toString).collect(Collectors.toList());}}private String capture(Path d,List<String>c)throws Exception{Process p=new ProcessBuilder(c).directory(d.toFile()).redirectErrorStream(true).start();String output=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);if(p.waitFor()!=0)throw new IllegalStateException(c.get(0)+" failed\n"+output);return output;}
    private void recreate(Path target)throws IOException{if(Files.exists(target)){require(target.startsWith(root.resolve(".worldline"))&&!target.equals(root),"unsafe build path");try(Stream<Path>p=Files.walk(target)){for(Path f:p.sorted(Comparator.reverseOrder()).collect(Collectors.toList()))Files.delete(f);}}Files.createDirectories(target);}private void load(Path path,Properties target)throws IOException{try(Reader r=Files.newBufferedReader(path,StandardCharsets.UTF_8)){target.load(r);}}private String value(Properties p,String k){String v=p.getProperty(k);require(v!=null&&!v.trim().isEmpty(),"missing "+k);return v.trim();}
    private String digest(Path path,String algorithm)throws Exception{MessageDigest d=MessageDigest.getInstance(algorithm);try(InputStream in=Files.newInputStream(path)){byte[]b=new byte[8192];int n;while((n=in.read(b))>=0)d.update(b,0,n);}return HexFormat.of().formatHex(d.digest());}private int freePort()throws IOException{try(ServerSocket s=new ServerSocket(0)){return s.getLocalPort();}}private Path product(String name){return root.resolve(".worldline/build/classes").resolve(name);}private String separator(){return System.getProperty("path.separator");}private String line(String output,String prefix){return output.lines().filter(x->x.startsWith(prefix)).findFirst().orElseThrow(()->new IllegalStateException("missing "+prefix+"\n"+output)).substring(prefix.length());}private String token(String row,String key){for(String item:row.split(","))if(item.startsWith(key+"="))return item.substring(key.length()+1);throw new IllegalStateException("missing "+key);}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static final class Outcome{final String trace,signature,terrain;Outcome(String t,String s,String r){trace=t;signature=s;terrain=r;}}
}
