import java.io.*;import java.net.ServerSocket;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.util.*;import java.util.stream.*;
/** Repeats official 2x2 sticks and workbench painting, sign, and bowl crafts. */
public final class PlaceableItemCraftsCycle{
 private static final String ID="m372-placeable-item-crafts";private final Path root=Paths.get("").toAbsolutePath().normalize(),smoke=root.resolve("smokes").resolve(ID),build=root.resolve(".worldline/smokes").resolve(ID);private final Properties config=new Properties(),artifact=new Properties();
 public static void main(String[]a){if(!Arrays.equals(a,new String[]{ID})){System.err.println("usage: java tools/smoke/PlaceableItemCraftsCycle.java "+ID);System.exit(2);}try{new PlaceableItemCraftsCycle().execute();}catch(Exception e){System.err.println("placeable item crafts failed: "+e.getMessage());System.exit(1);}}
 private void execute()throws Exception{load(smoke.resolve("smoke.properties"),config);load(root.resolve("artifacts/minecraft-b1.7.3-server.properties"),artifact);require(ID.equals(value(config,"id"))&&value(config,"server.jar.sha256").equals(value(artifact,"expected.sha256")),"descriptor drift");require(value(config,"username").equals("PlaceCraft372")&&value(config,"username").length()<=16,"actor username drift");Path official=root.resolve(value(artifact,"local.path")).normalize();verifyArtifact(official);recreate(build);Path classes=compile();Outcome first=run(classes,official,build.resolve("first")),second=run(classes,official,build.resolve("second"));require(first.signal.equals(second.signal)&&first.trace.equals(second.trace)&&first.signature.equals(second.signature),"fresh placeable craft results diverged");require(family(first.signal)>=3&&first.signal.contains("grid=2x2")&&first.trace.contains("workbench")&&!first.trace.contains("dir255")&&!first.trace.contains("packet130")&&!first.trace.contains("itemfood")&&!first.signal.contains("health="),"placeable crafts collapsed to place/orient/text/eat or missing result family");String expected=value(config,"expected.signature");if(expected.equals("pending")||Boolean.getBoolean("worldline.m372.diagnostic")){System.out.println("M372 placeable item crafts diagnostic passed; qualification not attempted");System.out.println("  "+first.signal);System.out.println("  trace: "+first.trace);System.out.println("  signature: "+first.signature);System.out.println("FROZEN");return;}require(first.signal.equals(value(config,"expected.signal"))&&first.signature.equals(expected),"M372 frozen evidence drift");Files.writeString(build.resolve("evidence.txt"),"id="+ID+"\nservers=2\nclients=4\nfirst="+first.signal+"\nsecond="+second.signal+"\ntrace="+first.trace+"\nsignature="+first.signature+"\n",StandardCharsets.UTF_8);System.out.println("M372 placeable item crafts passed");System.out.println("  "+first.signal);System.out.println("  signature: "+first.signature);System.out.println("FROZEN");}
 private Outcome run(Path classes,Path official,Path workspace)throws Exception{Exception last=null;for(int attempt=0;attempt<2;attempt++){try{if(Files.exists(workspace))recreate(workspace);String output=capture(root,Arrays.asList("java","-classpath",classes+separator()+product("api"),"worldline.smoke.placeableitemcraftsb173.PlaceableItemCraftsSmoke",official.toString(),workspace.toString(),Integer.toString(freePort()),value(config,"seed"),value(config,"username"),value(config,"chunk.x"),value(config,"chunk.z")));return new Outcome(line(output,"WORLDLINE_M372_TRACE="),line(output,"WORLDLINE_M372_SIGNATURE="),line(output,"WORLDLINE_M372_CRAFTS="));}catch(Exception e){last=e;SmokeRetryBoundary.afterEofFailure(attempt,1,e);throw e;}}throw last;}
 private Path compile()throws Exception{Path output=build.resolve("adapter-classes");Files.createDirectories(output);List<String>command=new ArrayList<>(Arrays.asList("javac","-encoding","UTF-8","--release","8","-Xlint:all,-options","-Werror","-classpath",product("api").toString(),"-d",output.toString()));command.addAll(javaFiles(root.resolve("modules/smoketest/src/main/java")));command.addAll(javaFiles(root.resolve("adapters/b173-server/src/main/java")));command.addAll(javaFiles(smoke.resolve("src")));capture(root,command);return output;}
 private int family(String signal){int count=0;for(String id:new String[]{"321","323","281"})if(signal.contains(id))count++;return count;}
 private void verifyArtifact(Path p)throws Exception{ExceptionalSmokeSupport.verifyArtifact(p,artifact);}private List<String>javaFiles(Path s)throws IOException{return ExceptionalSmokeSupport.javaFiles(s);}private String capture(Path d,List<String>c)throws Exception{return ExceptionalSmokeSupport.capture(d,c);}private void recreate(Path t)throws IOException{ExceptionalSmokeSupport.recreate(root,t);}private void load(Path p,Properties t)throws IOException{ExceptionalSmokeSupport.load(p,t);}private String value(Properties p,String k){return ExceptionalSmokeSupport.value(p,k);}private String digest(Path p,String a)throws Exception{return ExceptionalSmokeSupport.digest(p,a);}private int freePort()throws IOException{return ExceptionalSmokeSupport.freePort();}private Path product(String n){return ExceptionalSmokeSupport.product(root,n);}private String separator(){return System.getProperty("path.separator");}private String line(String o,String p){return ExceptionalSmokeSupport.line(o,p);}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static final class Outcome{final String trace,signature,signal;Outcome(String t,String s,String l){trace=t;signature=s;signal=l;}}
}
