package worldline.smoke.cakeslicesetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places uneaten cake 92:0, then Packet15-eats three successive BlockCake slices. */
public final class CakeSliceSetSmoke{
 private CakeSliceSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: CakeSliceSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,cake;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1},new int[]{1,354},new int[]{32,1},new int[]{0,0},8);actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==2,"cake-slice inventory drift");require(actor.awaitHealth(8)==8,"seeded cake-slice health drift");RemoteChunkSnapshot initial=chunk(actor,cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded cake-slice fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   cake=BlockFace.UP.adjacent(top);actor.selectHeldSlot(1);actor.useHeldItemOnBlock(top,BlockFace.UP);require(actor.awaitBlock(cake,new BlockState(92,0)).blockAt(cake.x(),cake.y(),cake.z()).equals(new BlockState(92,0)),"placed BlockCake 92:0 absent");require(actor.health()<14,"pre-bite health "+actor.health()+" cannot take three slices");actor.selectHeldSlot(2);bite(actor,cake,1);bite(actor,cake,2);bite(actor,cake,3);actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=chunk(reader,cx,cz);require(after.blockAt(local(cake.x(),cx),cake.y(),local(cake.z(),cz)).equals(new BlockState(92,3)),"persisted cake-slice drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,cake="+cake.x()+":"+cake.y()+":"+cake.z()+":92:0->1->2->3,slices=3,bites=6,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+blockcake92|cause=packet15-item354-place+empty-hand-packet15-three-slices|wire=packet53-cake92:0->1->2->3|oracle=blockcake-three-slice-metadata+fresh-login|"+evidence;System.out.println("WORLDLINE_M335_SET="+evidence);System.out.println("WORLDLINE_M335_TRACE="+trace);System.out.println("WORLDLINE_M335_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static RemoteChunkSnapshot chunk(B173WireClient a,int cx,int cz)throws Exception{RemoteWorldView w=a.sustainTicks(5);for(int n=0;n<120&&!w.containsChunk(cx,cz);n++)w=a.sustainTicks(5);require(w.containsChunk(cx,cz),"cake-slice chunk absent");return w.chunkAt(cx,cz);}
 private static void bite(B173WireClient a,BlockPosition cake,int meta)throws Exception{require(a.health()<20,"cake-slice health capped before 92:"+meta);a.activateBlock(cake,BlockFace.UP);require(a.awaitBlock(cake,new BlockState(92,meta)).blockAt(cake.x(),cake.y(),cake.z()).equals(new BlockState(92,meta)),"BlockCake bite 92:"+meta+" absent");a.sustainTicks(5);}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic cake-slice foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
