package worldline.smoke.netherloginb173;

import java.nio.ByteBuffer;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;
import worldline.api.*;import worldline.b173server.*;

/** Logs one dimension-seeded player into the official Nether and hashes its first chunk. */
public final class NetherLoginSmoke{
 private NetherLoginSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=5)throw new IllegalArgumentException("usage: NetherLoginSmoke server.jar workspace port seed username");Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];Duration timeout=Duration.ofSeconds(90);B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true,true);B173WireClient client=new B173WireClient("127.0.0.1",port,user,timeout);RemoteChunkSnapshot chunk;PlayerPose pose;
  try{server.boot();B173PlayerSeed.writeDimension(workspace,user,0.5D,64D,0.5D,-1);client.connect();pose=client.synchronizePose();chunk=client.awaitChunkSnapshot();client.sustainTicks(20);client.close();awaitPlayers(server,0);server.save();ServerPlayerState saved=server.player(user);require(saved.dimension()==-1,"official player dimension drift: "+saved.dimension());}finally{client.close();server.close();}
  MessageDigest md=MessageDigest.getInstance("SHA-256");ByteBuffer row=ByteBuffer.allocate(5);int netherrack=0,bedrock=0,lava=0;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=0;y<128;y++){BlockState state=chunk.blockAt(x,y,z);int id=state.legacyId()==39||state.legacyId()==40?0:state.legacyId();if(state.legacyId()==87)netherrack++;if(state.legacyId()==7)bedrock++;if(state.legacyId()==10||state.legacyId()==11)lava++;row.clear();row.put((byte)x).put((byte)y).put((byte)z).put((byte)id).put((byte)(id==0?0:state.metadata()));md.update(row.array());}require(netherrack>0&&bedrock>0&&lava>0,"first chunk is not Nether terrain");String evidence="dimension=-1,origin="+(chunk.observation().x()>>4)+":"+(chunk.observation().z()>>4)+",pose="+floor(pose.x())+":"+floor(pose.y())+":"+floor(pose.z())+",netherrack="+netherrack+",bedrock="+bedrock+",lava="+lava+",structural="+(netherrack+bedrock+lava)+",terrain="+hex(md.digest());String trace="v1|server=official-b1.7.3|seed="+seed+"|profile=allow-nether-true|entry=prelogin-player-nbt-dimension-minus-one|wire=packet1+packet13+packet51|observation=decoded-nether-chunk+normalized-structural-terrain-hash+saved-player-dimension-minus-one|"+evidence+"|disconnect=clean";System.out.println("WORLDLINE_M130_NETHER="+evidence);System.out.println("WORLDLINE_M130_TRACE="+trace);System.out.println("WORLDLINE_M130_SIGNATURE="+sha(trace));
 }
 private static int floor(double v){return (int)Math.floor(v);}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long end=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<end){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{return hex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte v:b)s.append(String.format("%02x",v&255));return s.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
