id=calamus-intermediary-gen2-b1.7.3
coordinate=net.ornithemc:calamus-intermediary-gen2:b1.7.3:v2
url=https://maven.ornithemc.net/releases/net/ornithemc/calamus-intermediary-gen2/b1.7.3/calamus-intermediary-gen2-b1.7.3-v2.jar
expected.bytes=60180
expected.sha256=534b5afd5e53f1cfb9cdd40265eccd18915b959cbb4495271b6243553a9c3dd7
output=calamus-intermediary-gen2-b1.7.3-v2.jar
mapping.entry=mappings/mappings.tiny
namespaces=intermediary,clientOfficial,serverOfficial
license.url=https://github.com/OrnitheMC/calamus-intermediary-gen2/blob/main/LICENSE
source.url=https://github.com/OrnitheMC/calamus-intermediary-gen2
