id=feather-gen2-b1.7.3-build.1
coordinate=net.ornithemc:feather-gen2:b1.7.3+build.1:v2
url=https://maven.ornithemc.net/releases/net/ornithemc/feather-gen2/b1.7.3+build.1/feather-gen2-b1.7.3+build.1-v2.jar
expected.bytes=106268
expected.sha256=b538eb6f852cb4c206110c53878f680cd531aa653040f9ce5b9cbdddd33bd586
output=feather-gen2-b1.7.3-build.1-v2.jar
mapping.entry=mappings/mappings.tiny
namespaces=intermediary,named
license=CC0-1.0
license.url=https://github.com/OrnitheMC/feather/blob/main/LICENSE
source.url=https://github.com/OrnitheMC/feather
