id=nostalgia-b1.7.3-build.60
coordinate=me.alphamode:nostalgia:b1.7.3+build.60:v2
url=https://mvn.devos.one/releases/me/alphamode/nostalgia/b1.7.3+build.60/nostalgia-b1.7.3+build.60-v2.jar
expected.bytes=104824
expected.sha256=6ea6496be70018e36e47af4af63b32c654af5d71806069b3c6084f97f1aa83c8
output=nostalgia-b1.7.3-build.60-v2.jar
mapping.entry=mappings/mappings.tiny
namespaces=intermediary,named
license=CC0-1.0
license.url=https://github.com/AlphaMode/Nostalgia/blob/7e60ac33973c21553b5e40e94ad2773453b9153d/LICENSE
source.url=https://github.com/AlphaMode/Nostalgia
source.revision=7e60ac33973c21553b5e40e94ad2773453b9153d
