id=retromcp-java-b1.7.3-generated
format=tiny-v2
namespaces=named,client,server
expected.bytes=272515
expected.sha256=c170d1fde77fccc36649fb2e09066e04670c835e00c0b46fcf6312c9560453a5
output=retromcp-b1.7.3.tiny
generator.url=https://github.com/MCPHackers/RetroMCP-Java
generator.revision=9ece383d9bfe993d763d75b503e913f0dfbd8852
license.url=https://github.com/MCPHackers/RetroMCP-Java/blob/9ece383d9bfe993d763d75b503e913f0dfbd8852/LICENSE
credits.url=https://github.com/MCPHackers/RetroMCP-Java/blob/9ece383d9bfe993d763d75b503e913f0dfbd8852/MCP-CREDITS.TXT
