id=retromcp-java
repository=https://github.com/MCPHackers/RetroMCP-Java.git
revision=9ece383d9bfe993d763d75b503e913f0dfbd8852
local.path=local/toolchains/retromcp-java
build.task=:cli:shadowJar
artifact.path=build/libs/RetroMCP-CLI-all.jar
