package worldline.smoke.waterlavab173;

import java.nio.ByteBuffer;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import java.util.*;
import worldline.api.*;import worldline.b173server.*;

/** Qualifies one confined official still-water/still-lava reaction. */
public final class WaterLavaReactionSmoke{
 private WaterLavaReactionSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=9)throw new IllegalArgumentException("usage: WaterLavaReactionSmoke server.jar workspace port seed username chunkX chunkZ fixtureTicks reactionTicks");Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]),fixtureTicks=Integer.parseInt(a[7]),reactionTicks=Integer.parseInt(a[8]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),treatment=null,reader=null;RemoteChunkSnapshot before,after;BlockPosition foundation,top,lavaFloor,waterFloor,lavaCell,waterCell;BlockState waterState,stoneState;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,11,9},new int[]{64,1,1},new int[]{0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==3,"reaction inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);foundation=foundation(initial,cx,cz);top=foundation;column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP);actor.moveAndObserve(0D,1D,0D,1);column++;require(column<=15,"water column exceeded fixture stack");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP);actor.moveAndObserve(0D,1D,0D,1);column++;}
   lavaFloor=top;waterFloor=place(actor,lavaFloor,BlockFace.WEST);List<BlockPosition>walls=Arrays.asList(place(actor,waterFloor,BlockFace.WEST),place(actor,lavaFloor,BlockFace.EAST),place(actor,waterFloor,BlockFace.NORTH),place(actor,waterFloor,BlockFace.SOUTH),place(actor,lavaFloor,BlockFace.NORTH),place(actor,lavaFloor,BlockFace.SOUTH));for(BlockPosition p:walls)place(actor,p,BlockFace.UP);lavaCell=BlockFace.UP.adjacent(lavaFloor);waterCell=BlockFace.UP.adjacent(waterFloor);
   actor.selectHeldSlot(1);actor.placeHeldBlock(lavaFloor,BlockFace.UP);actor.awaitBlock(lavaCell,new BlockState(11,0));RemoteWorldView filled=worldline.test.WorldlineSmokeAwait.observe(actor,fixtureTicks);require(filled.blockAt(lavaCell.x(),lavaCell.y(),lavaCell.z()).equals(new BlockState(11,0))&&filled.blockAt(waterCell.x(),waterCell.y(),waterCell.z()).equals(new BlockState(0,0)),"confined reaction baseline drift");actor.close();awaitPlayers(server,0);server.save();
   treatment=new B173WireClient("127.0.0.1",port,user,timeout);treatment.connect();treatment.synchronizePose();before=treatment.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);treatment.selectHeldSlot(2);treatment.placeHeldBlock(waterFloor,BlockFace.UP);treatment.awaitBlock(waterCell,new BlockState(9,0));treatment.awaitBlock(lavaCell,new BlockState(49,0));RemoteWorldView reacted=worldline.test.WorldlineSmokeAwait.observe(treatment,reactionTicks);waterState=reacted.blockAt(waterCell.x(),waterCell.y(),waterCell.z());stoneState=reacted.blockAt(lavaCell.x(),lavaCell.y(),lavaCell.z());require(waterState.equals(new BlockState(9,0))&&stoneState.equals(new BlockState(49,0)),"water-lava reaction drift: "+waterState+" / "+stoneState);
   treatment.close();awaitPlayers(server,0);server.save();reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(waterCell.x(),cx),waterCell.y(),local(waterCell.z(),cz)).equals(waterState)&&after.blockAt(local(lavaCell.x(),cx),lavaCell.y(),local(lavaCell.z(),cz)).equals(stoneState),"fresh reaction persistence drift");
  }finally{actor.close();if(treatment!=null)treatment.close();if(reader!=null)reader.close();server.close();}
  StateDelta d=delta(before,after,Arrays.asList(waterCell,lavaCell),cx,cz);require(d.changed==2,"reaction fixture delta drift: "+d);String evidence="column="+column+",water="+waterCell.x()+":"+waterCell.y()+":"+waterCell.z()+":0:0->"+waterState.legacyId()+":"+waterState.metadata()+",lava="+lavaCell.x()+":"+lavaCell.y()+":"+lavaCell.z()+":11:0->"+stoneState.legacyId()+":"+stoneState.metadata()+",states="+d;String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-confined-stone-basin+seeded-still-lava11|settle="+fixtureTicks+"+"+reactionTicks+"ticks|cause=place-still-water9-adjacent|effect=official-lava-hardening-to-obsidian49|observation=live-packet53+fresh-login-packet51|oracle=two-cell-causal-scope|"+evidence+"|disconnect=clean";System.out.println("WORLDLINE_M139_REACTION="+evidence);System.out.println("WORLDLINE_M139_TRACE="+trace);System.out.println("WORLDLINE_M139_SIGNATURE="+sha(trace));
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(1,0));return target;}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic reaction foundation");}
 private static StateDelta delta(RemoteChunkSnapshot a,RemoteChunkSnapshot b,List<BlockPosition>cells,int cx,int cz)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");ByteBuffer row=ByteBuffer.allocate(10);int n=0;for(BlockPosition v:cells){int x=local(v.x(),cx),y=v.y(),z=local(v.z(),cz);BlockState p=a.blockAt(x,y,z),q=b.blockAt(x,y,z);if(!p.equals(q)){n++;row.clear();row.putShort((short)v.x()).putShort((short)y).putShort((short)v.z()).put((byte)p.legacyId()).put((byte)p.metadata()).put((byte)q.legacyId()).put((byte)q.metadata());md.update(row.array());}}return new StateDelta(n,hex(md.digest()));}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{return hex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte v:b)s.append(String.format("%02x",v&255));return s.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static final class StateDelta{final int changed;final String hash;StateDelta(int n,String h){changed=n;hash=h;}public String toString(){return changed+":"+hash;}}
}
