package worldline.b173server;

import java.io.*;import java.util.*;import worldline.api.RemoteMobDeath;import worldline.api.RemoteMobMovement;import worldline.api.RemoteMobSpawn;

/** Bounded Packet24 queue with strict protocol-14 entity-metadata decoding. */
final class B173MobTracker {
    private static final int MAX=64;private int observed=-1;private final ArrayList<RemoteMobSpawn> pending=new ArrayList<>();private final ArrayList<RemoteMobMovement> moves=new ArrayList<>();private final ArrayList<RemoteMobDeath> deaths=new ArrayList<>();private final ArrayList<int[]> tames=new ArrayList<>();private final ArrayList<Integer> fuses=new ArrayList<>();private final HashMap<Integer,State> states=new HashMap<>();private final HashMap<Integer,Integer> sizes=new HashMap<>();private final HashSet<Integer> armed=new HashSet<>(),hurt=new HashSet<>(),dying=new HashSet<>(),gone=new HashSet<>();
    void spawn(DataInputStream in)throws IOException{int entity=in.readInt(),type=in.readUnsignedByte(),x=in.readInt(),y=in.readInt(),z=in.readInt(),yaw=in.readUnsignedByte(),pitch=in.readUnsignedByte();Metadata metadata=metadata(in);if(states.containsKey(entity)){if(armed.contains(entity))return;forget(entity);}while((pending.size()==MAX||states.size()==MAX)&&forgetUnarmed()){}if(pending.size()==MAX||states.size()==MAX)throw new IOException("mob spawn queue overflow or duplicate");try{pending.add(new RemoteMobSpawn(entity,type,x,y,z,yaw,pitch,metadata.entries,metadata.flags));states.put(entity,new State(x,y,z,yaw,pitch));if(metadata.size>=0)sizes.put(entity,metadata.size);}catch(IllegalArgumentException e){throw new IOException("invalid mob spawn",e);}}
    private boolean forgetUnarmed(){for(int i=0;i<pending.size();i++){int id=pending.get(i).entityId();if(!armed.contains(id)){forget(id);return true;}}for(Integer id:new ArrayList<Integer>(states.keySet()))if(!armed.contains(id)){forget(id);return true;}return false;}
    private void forget(int id){for(int i=pending.size()-1;i>=0;i--)if(pending.get(i).entityId()==id)pending.remove(i);for(int i=fuses.size()-1;i>=0;i--)if(fuses.get(i).intValue()==id)fuses.remove(i);states.remove(id);sizes.remove(id);hurt.remove(id);dying.remove(id);gone.remove(id);}
    void update(int packet,DataInputStream in)throws IOException{int entity=in.readInt(),x=0,y=0,z=0,yaw=-1,pitch=-1;if(packet==31||packet==33){x=in.readByte();y=in.readByte();z=in.readByte();}if(packet==32||packet==33){yaw=in.readUnsignedByte();pitch=in.readUnsignedByte();}if(packet==34){x=in.readInt();y=in.readInt();z=in.readInt();yaw=in.readUnsignedByte();pitch=in.readUnsignedByte();}State s=states.get(entity);if(s==null||packet==30||!armed.contains(entity))return;int nx=packet==34?x:s.x+x,ny=packet==34?y:s.y+y,nz=packet==34?z:s.z+z,ay=yaw<0?s.yaw:yaw,ap=pitch<0?s.pitch:pitch;if(!dying.contains(entity)&&(nx!=s.x||ny!=s.y||nz!=s.z)){if(moves.size()==MAX)moves.remove(0);try{moves.add(new RemoteMobMovement(entity,packet,s.x,s.y,s.z,nx,ny,nz,ay,ap));}catch(IllegalArgumentException e){throw new IOException("invalid mob movement",e);}}s.x=nx;s.y=ny;s.z=nz;s.yaw=ay;s.pitch=ap;}
    RemoteMobSpawn take(int type){if(type<0||type>127)throw new IllegalArgumentException("invalid expected mob type");for(int i=0;i<pending.size();i++)if(pending.get(i).legacyType()==type){RemoteMobSpawn v=pending.remove(i);armed.add(v.entityId());observed=v.entityId();return v;}return null;}
    RemoteMobSpawn peek(int type){if(type<0||type>127)throw new IllegalArgumentException("invalid expected mob type");for(int i=0;i<pending.size();i++)if(pending.get(i).legacyType()==type)return pending.get(i);return null;}
    int observed(){if(observed<0)throw new IllegalStateException("no adapter-owned mob identity");return observed;}
    RemoteMobMovement takeMovement(int entity){if(entity<0)throw new IllegalArgumentException("invalid expected mob entity");for(int i=0;i<moves.size();i++)if(moves.get(i).entityId()==entity)return moves.remove(i);return null;}
    void status(int entity,int status)throws IOException{if(!armed.contains(entity))return;if(status==2)hurt.add(entity);else if(status==3){dying.add(entity);complete(entity);}else if(status==6||status==7){if(tames.size()==MAX)tames.remove(0);tames.add(new int[]{entity,status});}}
    int takeTame(int entity){if(entity<0)throw new IllegalArgumentException("invalid expected mob entity");for(int i=0;i<tames.size();i++)if(tames.get(i)[0]==entity){int s=tames.get(i)[1];tames.remove(i);return s;}return -1;}
    boolean takeHurt(int entity){if(entity<0)throw new IllegalArgumentException("invalid expected mob entity");return hurt.remove(Integer.valueOf(entity));}
    boolean peekHurt(int entity){if(entity<0)throw new IllegalArgumentException("invalid expected mob entity");return hurt.contains(entity);}
    void watcher(DataInputStream in)throws IOException{int entity=in.readInt(),state=-1;while(true){int header=in.readUnsignedByte();if(header==127)break;int index=header&31,type=header>>5;switch(type){case 0:int value=in.readUnsignedByte();if(index==16){state=value;sizes.put(entity,value);}break;case 1:in.readShort();break;case 2:in.readInt();break;case 3:in.readFloat();break;case 4:B173InboundPacket.string(in,32767);break;case 5:int item=in.readShort();if(item>=0){in.readByte();in.readShort();}break;case 6:in.readInt();in.readInt();in.readInt();break;default:throw new IOException("invalid mob metadata type "+type);}}if(states.containsKey(entity)&&state==1){for(int i=fuses.size()-1;i>=0;i--)if(fuses.get(i).intValue()==entity)fuses.remove(i);if(fuses.size()==MAX)fuses.remove(0);fuses.add(entity);}}
    int takeFuse(int entity){if(entity<0)throw new IllegalArgumentException("invalid expected mob entity");for(int i=0;i<fuses.size();i++)if(fuses.get(i).intValue()==entity){fuses.remove(i);return entity;}return -1;}
    int size(int entity){Integer value=sizes.get(entity);return value==null?0:value.intValue();}
    void destroy(int entity)throws IOException{if(!armed.contains(entity))return;gone.add(entity);complete(entity);}
    RemoteMobDeath takeDeath(int entity){if(entity<0)throw new IllegalArgumentException("invalid expected mob entity");for(int i=0;i<deaths.size();i++)if(deaths.get(i).entityId()==entity)return deaths.remove(i);return null;} RemoteMobDeath peekDeath(int entity){if(entity<0)throw new IllegalArgumentException("invalid expected mob entity");for(int i=0;i<deaths.size();i++)if(deaths.get(i).entityId()==entity)return deaths.get(i);return null;}
    private void complete(int entity)throws IOException{if(!dying.contains(entity)||!gone.contains(entity))return;if(deaths.size()==MAX)throw new IOException("mob death queue overflow");try{deaths.add(new RemoteMobDeath(entity,3,hurt.contains(entity)));}catch(IllegalArgumentException e){throw new IOException("invalid mob death",e);}armed.remove(entity);dying.remove(entity);gone.remove(entity);}
    private static Metadata metadata(DataInputStream in)throws IOException{int mask=0,entries=0,flags=-1,size=-1;while(true){int header=in.readUnsignedByte();if(header==127)break;int index=header&31,type=header>>5,bit=1<<index;if((mask&bit)!=0)throw new IOException("duplicate mob metadata index "+index);mask|=bit;entries++;switch(type){case 0:int value=in.readUnsignedByte();if(index==0)flags=value;else if(index==16)size=value;break;case 1:in.readShort();break;case 2:in.readInt();break;case 3:in.readFloat();break;case 4:B173InboundPacket.string(in,32767);break;case 5:int item=in.readShort();if(item>=0){in.readByte();in.readShort();}break;case 6:in.readInt();in.readInt();in.readInt();break;default:throw new IOException("invalid mob metadata type "+type);}}if(entries<1||flags<0)throw new IOException("mob flags metadata absent");return new Metadata(entries,flags,size);}
    private static final class Metadata{final int entries,flags,size;Metadata(int e,int f,int s){entries=e;flags=f;size=s;}}
    private static final class State{int x,y,z,yaw,pitch;State(int a,int b,int c,int d,int e){x=a;y=b;z=c;yaw=d;pitch=e;}}
}
