package worldline.smoke.swordhurtsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** One Packet7 diamond-sword 276 hit each on zombie 54 and skeleton 51, freezing Packet38 status 2 without death. */
public final class SwordHurtSetSmoke{
 private SwordHurtSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SwordHurtSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("SwordHurt463")&&user.length()<=16,"sword-hurt identity drift");
  Duration timeout=Duration.ofSeconds(180);B173DedicatedServer server=B173DedicatedServer.monsters(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,first,second;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5,6},new int[]{1,2,52,52,276,320,322},new int[]{32,48,1,1,1,8,4},new int[]{0,0,0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==7,"sword-hurt inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded sword-hurt fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);first=place(actor,top,BlockFace.UP,52);actor.selectHeldSlot(3);second=place(actor,first,BlockFace.EAST,52);actor.sustainTicks(5);actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.entity(workspace,first,"Zombie");B173SpawnerSeed.entity(workspace,second,"Skeleton");server=B173DedicatedServer.monsters(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()>=1,"sword-hurt reload inventory drift");B173SwordHurt.station(actor,first.x()+0.5D,first.y()+1.1D,first.z()+0.5D);server.setTime(14000L);
   RemoteMobSpawn zombie=near(actor,54,first),skeleton=near(actor,51,second);require(zombie.legacyType()==54&&zombie.entityId()!=actor.state().entityId()&&zombie.legacyType()!=90,"zombie Packet24 identity drift");require(skeleton.legacyType()==51&&skeleton.entityId()!=actor.state().entityId()&&skeleton.entityId()!=zombie.entityId()&&skeleton.legacyType()!=90,"skeleton Packet24 identity drift");
   B173SwordHurt.oneHit(actor,zombie,false);require(B173SwordHurt.peekHurt(actor,zombie.entityId())&&B173SwordHurt.peekDeath(actor,zombie.entityId())==null,"zombie Packet38 status 2 hurt drift");B173SwordHurt.station(actor,second.x()+0.5D,second.y()+1.1D,second.z()-1.5D);B173SwordHurt.oneHit(actor,skeleton,false);require(B173SwordHurt.peekHurt(actor,skeleton.entityId())&&B173SwordHurt.peekDeath(actor,skeleton.entityId())==null&&actor.health()>0,"skeleton Packet38 status 2 hurt drift");
   actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass,spawners="+cell(first)+"+"+cell(second)+",entityid=Zombie+Skeleton,mobs=type54+type51,night=14000,sword=276,hurt=packet38-status2,death=none,hits=1+1,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+two-spawner52|cause=nbt-entityid-zombie+skeleton+time-14000+diamond-sword-packet7|wire=packet24-type54+packet24-type51+packet38-status2|oracle=zombie-and-skeleton-hurt-not-death-not-drops-not-explode|"+evidence;System.out.println("WORLDLINE_M463_SET="+evidence);System.out.println("WORLDLINE_M463_TRACE="+trace);System.out.println("WORLDLINE_M463_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static RemoteMobSpawn near(B173WireClient a,int type,BlockPosition p){for(int n=0;n<32;n++){RemoteMobSpawn s=a.awaitMobSpawn(type);double dx=s.x()-(p.x()+0.5D),dz=s.z()-(p.z()+0.5D);if(dx*dx+dz*dz<=100D&&Math.abs(s.y()-p.y())<=6D)return s;}throw new IllegalStateException("nearby sword-hurt type "+type+" absent");}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic sword-hurt foundation");}
 private static String cell(BlockPosition p){return p.x()+":"+p.y()+":"+p.z()+":52:0";}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
