package worldline.smoke.portalobsidiansetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import java.util.*;
import worldline.api.*;import worldline.b173server.*;

/** Places fourteen obsidian 49 frame cells and ignites six portal 90 interior cells as one SET. */
public final class PortalObsidianSetSmoke{
 private PortalObsidianSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: PortalObsidianSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("Portal382")&&user.length()<=16,"portal-obsidian-set identity drift");
  Duration timeout=Duration.ofSeconds(90);B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition bottom;List<BlockPosition>frame=new ArrayList<>(),inside=new ArrayList<>();int column,metadata=-1;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,49,259},new int[]{16,14,1},new int[]{0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==3&&actor.dimension()==0,"portal-obsidian-set inventory or dimension drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);BlockPosition anchor=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(anchor.x(),cx),anchor.y()+1,local(anchor.z(),cz)).legacyId())){anchor=place(actor,anchor,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded portal-obsidian-set fixture");}anchor=place(actor,anchor,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;
   actor.selectHeldSlot(1);bottom=place(actor,anchor,BlockFace.UP,49);frame.add(bottom);BlockPosition p=bottom;for(int i=0;i<3;i++){p=place(actor,p,BlockFace.EAST,49);frame.add(p);}BlockPosition left=bottom,right=p;for(int i=0;i<4;i++){left=place(actor,left,BlockFace.UP,49);right=place(actor,right,BlockFace.UP,49);frame.add(left);frame.add(right);}p=left;for(int i=0;i<2;i++){p=place(actor,p,BlockFace.EAST,49);frame.add(p);}
   for(int y=1;y<=3;y++)for(int x=1;x<=2;x++)inside.add(new BlockPosition(bottom.x()+x,bottom.y()+y,bottom.z()));require(frame.size()==14&&inside.size()==6,"portal-obsidian-set geometry drift");
   RemoteWorldView framed=worldline.test.WorldlineSmokeAwait.observe(actor,20);for(BlockPosition q:frame)require(framed.blockAt(q.x(),q.y(),q.z()).equals(new BlockState(49,0)),"obsidian 49 frame drift at "+q);for(BlockPosition q:inside)require(framed.blockAt(q.x(),q.y(),q.z()).equals(new BlockState(0,0)),"portal interior was not empty at "+q);
   actor.selectHeldSlot(2);actor.useHeldItemOnBlock(new BlockPosition(bottom.x()+1,bottom.y(),bottom.z()),BlockFace.UP);RemoteWorldView active=worldline.test.WorldlineSmokeAwait.observe(actor,20);for(BlockPosition q:inside){BlockState s=active.blockAt(q.x(),q.y(),q.z());require(s.legacyId()==90,"portal 90 activation absent at "+q+": "+s);if(metadata<0)metadata=s.metadata();else require(metadata==s.metadata(),"portal metadata drift");}require(actor.dimension()==0,"portal-obsidian-set traveled during activation");
   actor.close();awaitPlayers(server,0);server.save();reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();require(reader.dimension()==0,"fresh login dimension drift");RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);for(BlockPosition q:frame)require(after.blockAt(local(q.x(),cx),q.y(),local(q.z(),cz)).equals(new BlockState(49,0)),"fresh obsidian 49 drift at "+q);for(BlockPosition q:inside)require(after.blockAt(local(q.x(),cx),q.y(),local(q.z(),cz)).equals(new BlockState(90,metadata)),"fresh portal 90 drift at "+q);
   String evidence="column="+column+",frame="+bottom.x()+":"+bottom.y()+":"+bottom.z()+"-"+(bottom.x()+3)+":"+(bottom.y()+4)+":"+bottom.z()+",obsidian=14x49,interior=6x90:"+metadata+",flint=259,dimension=0,persisted=true,clients=2,disconnect=clean";
   String trace="v1|server=official-b1.7.3|seed="+seed+"|profile=allow-nether-true|fixture=stone-column+obsidian49-frame4x5+flintsteel259|construction=packet15-fourteen-obsidian49|baseline=six-air-cells|cause=packet15-flint-and-steel259|effect=official-portal-block90-six-cells|observation=live-packet53+fresh-login-packet51|oracle=fourteen-obsidian49+six-portal90+dimension-zero-no-travel|"+evidence;
   System.out.println("WORLDLINE_M382_SET="+evidence);System.out.println("WORLDLINE_M382_TRACE="+trace);System.out.println("WORLDLINE_M382_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=10;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic portal-obsidian-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
