package worldline.smoke.ladderclimbsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Proves official two-cell ladder 65:5 placement and persistence. */
public final class LadderClimbSetSmoke{
 private LadderClimbSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: LadderClimbSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  require(user.length()<=16,"username exceeds 16");B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,upper,low,high;int column;BlockState placed=new BlockState(65,5);
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1},new int[]{1,65},new int[]{32,8},new int[]{0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==2,"ladder-climb-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded ladder-climb-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}upper=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;low=BlockFace.EAST.adjacent(top);high=BlockFace.EAST.adjacent(upper);
   require(initial.blockAt(local(low.x(),cx),low.y(),local(low.z(),cz)).legacyId()==0&&initial.blockAt(local(high.x(),cx),high.y(),local(high.z(),cz)).legacyId()==0,"ladder column was not initial air");actor.selectHeldSlot(1);actor.placeHeldBlock(top,BlockFace.EAST);actor.awaitBlock(low,placed);actor.placeHeldBlock(upper,BlockFace.EAST);actor.awaitBlock(high,placed);RemoteWorldView live=worldline.test.WorldlineSmokeAwait.observe(actor,5);require(live.blockAt(low.x(),low.y(),low.z()).equals(placed)&&live.blockAt(high.x(),high.y(),high.z()).equals(placed),"live two-cell ladder 65:5 drift");
   actor.close();awaitPlayers(server,0);server.save();reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(top.x(),cx),top.y(),local(top.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(upper.x(),cx),upper.y(),local(upper.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(low.x(),cx),low.y(),local(low.z(),cz)).equals(placed)&&after.blockAt(local(high.x(),cx),high.y(),local(high.z(),cz)).equals(placed),"persisted ladder-climb-set drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,upper="+upper.x()+":"+upper.y()+":"+upper.z()+":1:0,ladder="+low.x()+":"+low.y()+":"+low.z()+":65:5+"+high.x()+":"+high.y()+":"+high.z()+":65:5,face=east,placement=server-authored,persisted=true,clients=2,disconnect=clean";String trace="v2|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+ladder65-east-column2|cause=packet15-item65-place|wire=packet53-ladder65:5|oracle=placement+persistence-only|client-physics=controlled-client-tick|"+evidence;System.out.println("WORLDLINE_M361_SET="+evidence);System.out.println("WORLDLINE_M361_TRACE="+trace);System.out.println("WORLDLINE_M361_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic ladder-climb-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}
 private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
