package worldline.smoke.ladderclimbsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places official two-cell ladder 65 and Packet13-climbs it versus the same air column. */
public final class LadderClimbSetSmoke{
 private LadderClimbSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: LadderClimbSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  require(user.length()<=16,"username exceeds 16");B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,upper,low,high;int column,ticks=10;PlayerPose pose;BlockState placed=new BlockState(65,5);
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1},new int[]{1,65},new int[]{32,8},new int[]{0,0});actor.connect();pose=actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==2,"ladder-climb-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();require(++column<=15,"water column exceeded ladder-climb-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();column++;}
   upper=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();column++;low=BlockFace.EAST.adjacent(top);high=BlockFace.EAST.adjacent(upper);
   require(initial.blockAt(local(low.x(),cx),low.y(),local(low.z(),cz)).legacyId()==0&&initial.blockAt(local(high.x(),cx),high.y(),local(high.z(),cz)).legacyId()==0,"ladder column was not initial air");
   pose=actor.moveAndObserve((low.x()+0.5D)-pose.x(),low.y()-pose.y(),(low.z()+0.5D)-pose.z(),4).resulting();PlayerPose airStart=pose;pose=jump(actor,ticks);int air=milli(pose.y()-airStart.y());require(air<2000,"air column climbed two cells without ladder "+air);
   pose=actor.moveAndObserve((upper.x()+0.5D)-pose.x(),(upper.y()+1.0D)-pose.y(),(upper.z()+0.5D)-pose.z(),4).resulting();actor.selectHeldSlot(1);actor.placeHeldBlock(top,BlockFace.EAST);actor.awaitBlock(low,placed);actor.placeHeldBlock(upper,BlockFace.EAST);actor.awaitBlock(high,placed);RemoteWorldView live=actor.sustainTicks(5);require(live.blockAt(low.x(),low.y(),low.z()).equals(placed)&&live.blockAt(high.x(),high.y(),high.z()).equals(placed),"live two-cell ladder 65 drift");
   pose=actor.moveAndObserve((low.x()+0.5D)-pose.x(),low.y()-pose.y(),(low.z()+0.5D)-pose.z(),4).resulting();live=actor.sustainTicks(1);require(live.blockAt(low.x(),low.y(),low.z()).equals(placed)&&floor(pose.x())==low.x()&&floor(pose.y())==low.y()&&floor(pose.z())==low.z(),"walk-into-ladder drift");PlayerPose climbStart=pose;pose=climb(actor,ticks);int climb=milli(pose.y()-climbStart.y());require(climb>=2000&&climb>air,"ladder Packet13 climb was not two cells above air "+climb+"/"+air);
   actor.close();awaitPlayers(server,0);server.save();reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(top.x(),cx),top.y(),local(top.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(upper.x(),cx),upper.y(),local(upper.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(low.x(),cx),low.y(),local(low.z(),cz)).equals(placed)&&after.blockAt(local(high.x(),cx),high.y(),local(high.z(),cz)).equals(placed),"persisted ladder-climb-set drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,upper="+upper.x()+":"+upper.y()+":"+upper.z()+":1:0,ladder="+low.x()+":"+low.y()+":"+low.z()+":65:5+"+high.x()+":"+high.y()+":"+high.z()+":65:5,face=east,ticks="+ticks+",air="+air+",climb="+climb+",climbed=true,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+ladder65-east-column2|cause=packet15-item65-place+packet13-climb|wire=packet53-ladder65:5+packet13-pose-delta|oracle=ladder-climb-two-cells-vs-air-column+fresh-login|"+evidence;System.out.println("WORLDLINE_M361_SET="+evidence);System.out.println("WORLDLINE_M361_TRACE="+trace);System.out.println("WORLDLINE_M361_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static PlayerPose jump(B173WireClient a,int ticks)throws Exception{double mot=0.42D;PlayerPose pose=null;for(int i=0;i<ticks;i++){pose=a.moveAndObserve(0D,mot,0D,1).resulting();mot=(mot-0.08D)*0.98D;}return pose;}
 private static PlayerPose climb(B173WireClient a,int ticks)throws Exception{PlayerPose pose=null;for(int i=0;i<ticks;i++)pose=a.moveAndObserve(0D,0.2D,0D,1).resulting();return pose;}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic ladder-climb-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static int floor(double v){return(int)Math.floor(v);}private static int milli(double v){return(int)Math.round(v*1000D);}
 private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
