package worldline.smoke.zombiepigmansetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Nether Packet24 type 57 pigman identity plus official cooked-pork 320 death drop. */
public final class ZombiePigmanSetSmoke{
 private static final RemoteItemStack COOKED=new RemoteItemStack(320,1,0);
 private ZombiePigmanSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: ZombiePigmanSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(180);
  require(user.length()<=16,"username exceeds 16");B173DedicatedServer server=B173PigmanAccess.server(jar,workspace,port,seed,timeout);B173WireClient scout=new B173WireClient("127.0.0.1",port,user,timeout),actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,spawner;
  try{server.boot();B173PlayerSeed.writeDimension(workspace,user,4.5D,64D,4.5D,-1);scout.connect();scout.synchronizePose();require(scout.dimension()==-1&&scout.awaitDimension(-1)==-1,"nether scout dimension drift");RemoteChunkSnapshot initial=scout.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(count(initial,87)>0&&sky(initial)==0,"nether terrain identity drift");top=foundation(initial,cx,cz);scout.close();awaitPlayers(server,0);
   B173PlayerSeed.writeInventory(workspace,user,top.x()+0.5D,top.y()+1.0D,top.z()+0.5D,-1,new int[]{0,1,2,3},new int[]{87,52,276,297},new int[]{32,1,1,8},new int[]{0,0,0,0});actor.connect();require(actor.synchronizePose()!=null&&actor.dimension()==-1&&actor.awaitInventory().occupiedSlots()==4,"nether pigman inventory or dimension drift");actor.awaitRemoteChunk(cx,cz);actor.look(0F,0F);
   actor.selectHeldSlot(0);pad(actor,top);PlayerPose pose=actor.moveAndObserve(0D,0D,-1.5D,4).resulting();require(Math.abs(pose.x()-(top.x()+0.5D))<3D&&Math.abs(pose.y()-(top.y()+1.0D))<4D,"actor missed nether pigman fixture");actor.selectHeldSlot(1);spawner=place(actor,top,BlockFace.UP,52);worldline.test.WorldlineSmokeAwait.observe(actor,5);actor.close();awaitPlayers(server,0);server.save();
  }finally{scout.close();actor.close();server.close();}
  Thread.sleep(1000L);B173PigmanAccess.retarget(workspace,spawner);server=B173PigmanAccess.server(jar,workspace,port,seed,timeout);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.dimension()==-1&&actor.awaitInventory().occupiedSlots()>=1,"nether pigman reload drift");RemoteDroppedItem pork=null;int kills=0;
   while(pork==null){require(++kills<=8,"official pigman cooked-pork drop absent after bounded kills");RemoteMobSpawn spawn=near(actor,57,spawner);require(spawn.legacyType()==57&&spawn.entityId()!=actor.state().entityId()&&spawn.legacyType()!=90&&spawn.legacyType()!=54,"pigman Packet24 identity drift");B173PigmanAccess.kill(actor,spawn);pork=worldline.test.WorldlineSmokeAwait.awaitEntityOrNull(actor,()->actor.peekDroppedItem(COOKED),value->value!=null,"pigman cooked-pork drop",20);}
   require(pork.item().legacyId()==320&&pork.item().legacyId()!=371,"pigman Packet21 drop id drift");actor.close();awaitPlayers(server,0);server.save();
   String evidence="dimension=-1,netherrack=positive,spawner="+cell(spawner)+",entityid=PigZombie,mob=type57,sword=276,drop=packet21-320,kills<=8,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|profile=allow-nether-true|entry=prelogin-player-nbt-dimension-minus-one+item52+item276|fixture=nether-netherrack87+spawner52|cause=nbt-entityid-pigzombie+diamond-sword-packet7|wire=packet24-type57+packet38-status3+packet29+packet21-320|oracle=nether-pigzombie57-cooked-pork-320-not-m388-zombie-feather|"+evidence;System.out.println("WORLDLINE_M411_PIGMAN="+evidence);System.out.println("WORLDLINE_M411_TRACE="+trace);System.out.println("WORLDLINE_M411_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static RemoteMobSpawn near(B173WireClient a,int type,BlockPosition p){for(int n=0;n<32;n++){RemoteMobSpawn s=a.awaitMobSpawn(type);double dx=s.x()-(p.x()+0.5D),dz=s.z()-(p.z()+0.5D);if(dx*dx+dz*dz<=100D&&Math.abs(s.y()-p.y())<=6D)return s;}throw new IllegalStateException("nearby pigman type "+type+" absent");}
 private static void pad(B173WireClient a,BlockPosition c)throws Exception{BlockFace[]faces={BlockFace.NORTH,BlockFace.SOUTH,BlockFace.WEST,BlockFace.EAST};for(BlockFace f:faces){BlockPosition n=f.adjacent(c);if(air(a.awaitRemoteChunk(n.x()>>4,n.z()>>4).blockAt(n.x(),n.y(),n.z()).legacyId()))place(a,c,f,87);}}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=2;x<=13;x++)for(int z=2;z<=13;z++)for(int y=110;y>=8;y--){int id=q.blockAt(x,y,z).legacyId(),up=q.blockAt(x,y+1,z).legacyId(),up2=q.blockAt(x,y+2,z).legacyId(),up3=q.blockAt(x,y+3,z).legacyId();if(id==87&&air(up)&&air(up2)&&air(up3)&&!lava(up)&&!lava(up2))return new BlockPosition(cx*16+x,y,cz*16+z);}throw new IllegalStateException("no deterministic nether pigman foundation");}
 private static String cell(BlockPosition p){return p.x()+":"+p.y()+":"+p.z()+":52:0";}
 private static boolean air(int id){return id==0;}private static boolean lava(int id){return id==10||id==11;}private static int count(RemoteChunkSnapshot q,int id){int n=0;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=0;y<128;y++)if(q.blockAt(x,y,z).legacyId()==id)n++;return n;}private static int sky(RemoteChunkSnapshot q){int n=0;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=0;y<128;y++)if(q.skyLightAt(x,y,z)>0)n++;return n;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
