import java.util.Arrays;
import java.util.List;

/** Canonical --smoke suite extracted so Verify can grow milestones without a packed file. */
final class SmokeSuite {
    public static void main(String[] arguments) {
        if (arguments.length != 0) {
            System.err.println("usage: java tools/harness/SmokeSuite.java");
            System.exit(2);
        }
        try { run(SmokeSuite::execute); }
        catch (Exception error) {
            System.err.println("smoke suite failed: " + error.getMessage());
            System.exit(1);
        }
    }

    private static void execute(List<String> command) throws Exception {
        Process process = new ProcessBuilder(command).inheritIO().start();
        if (process.waitFor() != 0) throw new IllegalStateException(command.get(1) + " failed");
    }

    interface Run { void run(List<String> command) throws Exception; }

    private static final String[][] SMOKES = {
        {"tools/smoke/Run.java", "deterministic-world-tick"},
        {"tools/smoke/ClientCycle.java", "controlled-client-tick"},
        {"tools/smoke/ApiCycle.java", "m3-domain-api"},
        {"tools/smoke/SnapshotCycle.java", "m4-durable-snapshot"},
        {"tools/smoke/BundleCycle.java", "m5-reproduction-bundle"},
        {"tools/smoke/TraceCycle.java", "m6-trace-explorer"},
        {"tools/smoke/ModCycle.java", "m7-mod-loading"},
        {"tools/smoke/VersionCycle.java", "m8-mod-version-diff"},
        {"tools/smoke/MinimizationCycle.java", "m9-scenario-minimization"},
        {"tools/smoke/NativeRenderCycle.java", "m10-native-render"},
        {"tools/smoke/AeroAttributionCycle.java", "m11-aero-attribution"},
        {"tools/smoke/AeroReproductionCycle.java", "m12-aero-reproduction"},
        {"tools/smoke/AeroDifferentialCycle.java", "m13-aero-differential"},
        {"tools/smoke/AeroChunkBacklogCycle.java", "m14-chunk-backlog"},
        {"tools/smoke/AeroChunkContractCycle.java", "m15-chunk-contract"},
        {"tools/smoke/AeroAdaptiveChunkCycle.java", "m16-adaptive-chunks"},
        {"tools/smoke/AeroSchedulerHardeningCycle.java", "m17-scheduler-hardening"},
        {"tools/smoke/AeroSaveAttributionCycle.java", "m18-save-attribution"},
        {"tools/smoke/AeroForcedAutosaveCycle.java", "m19-forced-autosave"},
        {"tools/smoke/ServerBootstrapCycle.java", "m20-server-bootstrap"},
        {"tools/smoke/ServerControlCycle.java", "m21-server-control"},
        {"tools/smoke/MultiplayerWireCycle.java", "m22-multiplayer-wire"},
        {"tools/smoke/PlayerPersistenceCycle.java", "m23-player-persistence"},
        {"tools/smoke/PlayPoseCycle.java", "m24-play-pose"},
        {"tools/smoke/PlayerMovementCycle.java", "m25-player-movement"},
        {"tools/smoke/NativeMultiplayerCycle.java", "m26-native-multiplayer"},
        {"tools/smoke/MultiplayerChatCycle.java", "m27-multiplayer-chat"},
        {"tools/smoke/RemoteChunkCycle.java", "m28-remote-chunk"},
        {"tools/smoke/RemoteChunkSnapshotCycle.java", "m29-remote-chunk-snapshot"},
        {"tools/smoke/RemoteWorldCacheCycle.java", "m30-remote-world-cache"},
        {"tools/smoke/IncrementalWorldCycle.java", "m31-incremental-world"},
        {"tools/smoke/RemoteTerrainRenderCycle.java", "m32-remote-terrain-render"},
        {"tools/smoke/ChunkTraversalCycle.java", "m33-chunk-traversal"},
        {"tools/smoke/PoseCorrectionCycle.java", "m34-pose-correction"},
        {"tools/smoke/MovementOutcomeCycle.java", "m35-movement-outcome"},
        {"tools/smoke/RouteRecoveryCycle.java", "m36-route-recovery"},
        {"tools/smoke/RoutePolicyCycle.java", "m37-route-policy"},
        {"tools/smoke/ExplicitFallbackCycle.java", "m38-explicit-fallback"},
        {"tools/smoke/RouteObservationCycle.java", "m39-route-observation"},
        {"tools/smoke/ObserverControlCycle.java", "m40-observer-control"},
        {"tools/smoke/RouteTerminationCycle.java", "m41-route-termination"},
        {"tools/smoke/RouteCorrelationCycle.java", "m42-route-correlation"},
        {"tools/smoke/CorrelatedBatchCycle.java", "m43-correlated-batch"},
        {"tools/smoke/BatchObservationCycle.java", "m44-batch-observation"},
        {"tools/smoke/EventBatchStopCycle.java", "m45-event-batch-stop"},
        {"tools/smoke/BatchTerminalCycle.java", "m46-batch-terminal"},
        {"tools/smoke/BatchCountsCycle.java", "m47-batch-counts"},
        {"tools/smoke/InventoryObservationCycle.java", "m48-inventory-observation"},
        {"tools/smoke/HeldItemPeerCycle.java", "m49-held-item-peer"},
        {"tools/smoke/DropHeldItemCycle.java", "m50-drop-held-item"},
        {"tools/smoke/DroppedItemSpawnCycle.java", "m51-dropped-item-spawn"},
        {"tools/smoke/ItemCollectionCycle.java", "m52-item-collection"},
        {"tools/smoke/HeldBlockPlacementCycle.java", "m53-held-block-placement"},
        {"tools/smoke/ChestWindowCycle.java", "m54-chest-window"},
        {"tools/smoke/AcceptedPersonalTransactionCycle.java", "m55-accepted-personal-transaction"},
        {"tools/smoke/RejectedTransactionRecoveryCycle.java", "m56-rejected-transaction-recovery"},
        {"tools/smoke/PersonalCraftingCycle.java", "m57-personal-crafting"},
        {"tools/smoke/WindowLifecycleCycle.java", "m58-window-lifecycle"},
        {"tools/smoke/ChestTransferCycle.java", "m59-chest-transfer"},
        {"tools/smoke/FurnaceSmeltCycle.java", "m60-furnace-smelt"},
        {"tools/smoke/FurnaceOutputCycle.java", "m61-furnace-output"},
        {"tools/smoke/WorkbenchWindowCycle.java", "m62-workbench-window"},
        {"tools/smoke/WorkbenchPrepareCycle.java", "m63-workbench-prepare"},
        {"tools/smoke/WorkbenchOutputCycle.java", "m64-workbench-output"},
        {"tools/smoke/PeerArmorCycle.java", "m65-peer-armor"},
        {"tools/smoke/PlayerCombatCycle.java", "m66-player-combat"},
        {"tools/smoke/ChestRetrievalCycle.java", "m67-chest-retrieval"},
        {"tools/smoke/AeroMultiplayerLoginCycle.java", "m68-aero-multiplayer-login"},
        {"tools/smoke/PeerSwingCycle.java", "m69-peer-swing"},
        {"tools/smoke/AeroCombatWindowCycle.java", "m70-aero-combat-window"},
        {"tools/smoke/PairedAeroWindowCycle.java", "m71-paired-aero-window"},
        {"tools/smoke/AeroServerContentCycle.java", "m72-aero-server-content"},
        {"tools/smoke/AeroPairedContentCycle.java", "m73-paired-aero-content"},
        {"tools/smoke/AeroFrameCensusCycle.java", "m74-complete-aero-census"},
        {"tools/smoke/AeroDensityLadderCycle.java", "m75-aero-density-ladder"},
        {"tools/smoke/RendererDecompositionCycle.java", "m76-renderer-decomposition"},
        {"tools/smoke/DirectStageTimingCycle.java", "m77-direct-stage-timing"},
        {"tools/smoke/PagedStageTimingCycle.java", "m78-paged-stage-timing"},
        {"tools/smoke/ColdPageRebuildCycle.java", "m79-cold-page-rebuild"},
        {"tools/smoke/NaturalMembershipRebuildCycle.java", "m80-natural-membership-rebuild"},
        {"tools/smoke/NaturalMultipageRebuildCycle.java", "m81-natural-multipage-rebuild"},
        {"tools/smoke/NaturalWaveLadderCycle.java", "m82-natural-wave-ladder"},
        {"tools/smoke/PageTopologyContrastCycle.java", "m83-page-topology-contrast"},
        {"tools/smoke/FourPageTopologyContrastCycle.java", "m84-four-page-topology-contrast"},
        {"tools/smoke/NaturalMembershipRecoveryCycle.java", "m85-natural-membership-recovery"},
        {"tools/smoke/RepeatedMembershipRecoveryCycle.java", "m86-repeated-membership-recovery"},
        {"tools/smoke/TwoCellMembershipRecoveryCycle.java", "m87-two-cell-membership-recovery"},
        {"tools/smoke/ReverseTwoCellMembershipRecoveryCycle.java", "m88-reverse-two-cell-membership-recovery"},
        {"tools/smoke/SiblingCellMembershipRecoveryCycle.java", "m89-sibling-cell-membership-recovery"},
        {"tools/smoke/LargerPageSiblingRecoveryCycle.java", "m90-larger-page-sibling-recovery"},
        {"tools/smoke/LargerPageDepletionRecoveryCycle.java", "m91-larger-page-depletion-recovery"},
        {"tools/smoke/ThirdMemberDepletionRecoveryCycle.java", "m92-third-member-depletion-recovery"},
        {"tools/smoke/FullPageDepletionRecoveryCycle.java", "m93-full-page-depletion-recovery"},
        {"tools/smoke/DefaultTtlPageRecoveryCycle.java", "m94-default-ttl-page-recovery"},
        {"tools/smoke/PageCapacityThrashCycle.java", "m95-page-capacity-thrash"},
        {"tools/smoke/PageCapacityTwoThrashCycle.java", "m96-page-capacity-two-thrash"},
        {"tools/smoke/PageCapacityOneThrashCycle.java", "m97-page-capacity-one-thrash"},
        {"tools/smoke/ZeroCapacityFloorCycle.java", "m98-zero-capacity-floor"},
        {"tools/smoke/RebuildBudgetFallbackCycle.java", "m99-rebuild-budget-fallback"},
        {"tools/smoke/RebuildBudgetOneFallbackCycle.java", "m100-rebuild-budget-one-fallback"},
        {"tools/smoke/RebuildBudgetZeroDirectCycle.java", "m101-rebuild-budget-zero-direct"},
        {"tools/smoke/UnlimitedRebuildSentinelCycle.java", "m102-unlimited-rebuild-sentinel"},
        {"tools/smoke/PagesDisabledImmediateDirectCycle.java", "m103-pages-disabled-immediate-direct"},
        {"tools/smoke/PairedPagesControlCycle.java", "m104-paired-pages-control"},
        {"tools/smoke/PairedCacheCapacityCycle.java", "m105-paired-cache-capacity"},
        {"tools/smoke/PairedMinimumInstancesCycle.java", "m106-paired-min-instances"},
        {"tools/smoke/PairedSkipIndividualCycle.java", "m107-paired-skip-individual"},
        {"tools/smoke/PairedCellSizeCycle.java", "m108-paired-cell-size"},
        {"tools/smoke/CellSizeFloorCycle.java", "m109-cell-size-floor"},
        {"tools/smoke/CellSizeCeilingCycle.java", "m110-cell-size-ceiling"},
        {"tools/smoke/FixedSeedTerrainCycle.java", "m111-fixed-seed-terrain"},
        {"tools/smoke/FixedSeedLightingCycle.java", "m112-fixed-seed-lighting"},
        {"tools/smoke/CausalLightingCycle.java", "m113-causal-lighting"},
        {"tools/smoke/CausalWaterFlowCycle.java", "m114-causal-water-flow"},
        {"tools/smoke/LeverActivationCycle.java", "m115-lever-activation"},
        {"tools/smoke/RedstoneWirePowerCycle.java", "m116-redstone-wire-power"},
        {"tools/smoke/RedstoneWireDepowerCycle.java", "m117-redstone-wire-depower"},
        {"tools/smoke/IronDoorPowerCycle.java", "m118-redstone-iron-door"},
        {"tools/smoke/FallingSandCycle.java", "m119-falling-sand"},
        {"tools/smoke/HorizontalWaterCycle.java", "m120-horizontal-water"},
        {"tools/smoke/FixedSeedRegionCycle.java", "m121-fixed-seed-region"},
        {"tools/smoke/FixedSeedRegionLightingCycle.java", "m122-fixed-seed-region-lighting"},
        {"tools/smoke/CrossChunkLightingCycle.java", "m123-cross-chunk-lighting"},
        {"tools/smoke/CrossChunkLightRecoveryCycle.java", "m124-cross-chunk-light-recovery"},
        {"tools/smoke/CrossChunkWaterCycle.java", "m125-cross-chunk-water"},
        {"tools/smoke/CrossChunkRedstoneCycle.java", "m126-cross-chunk-redstone"},
        {"tools/smoke/CrossChunkRedstoneRecoveryCycle.java", "m127-cross-chunk-redstone-recovery"},
        {"tools/smoke/CrossChunkIronDoorCycle.java", "m128-cross-chunk-iron-door"},
        {"tools/smoke/CrossChunkIronDoorRecoveryCycle.java", "m129-cross-chunk-iron-door-recovery"},
        {"tools/smoke/NetherLoginCycle.java", "m130-nether-login"},
        {"tools/smoke/DualDimensionSessionCycle.java", "m131-dual-dimension-session"},
        {"tools/smoke/GuiCycle.java", "gui-tree"},
        {"tools/smoke/NetherPortalActivationCycle.java", "m132-nether-portal-activation"},
        {"tools/smoke/NetherPortalTraversalCycle.java", "m133-nether-portal-traversal"},
        {"tools/smoke/NetherPortalRoundtripCycle.java", "m134-nether-portal-roundtrip"},
        {"tools/smoke/PlayerRespawnCycle.java", "m135-player-respawn"},
        {"tools/smoke/NetherDeathRespawnCycle.java", "m136-nether-death-respawn"},
        {"tools/smoke/TntExplosionCycle.java", "m137-tnt-explosion"},
        {"tools/smoke/HorizontalLavaCycle.java", "m138-horizontal-lava"},
        {"tools/smoke/WaterLavaReactionCycle.java", "m139-water-lava-reaction"},
        {"tools/smoke/BonemealTreeGrowthCycle.java", "m140-bonemeal-tree-growth"},
        {"tools/smoke/PigSpawnerCycle.java", "m141-pig-spawner-observation"},
        {"tools/smoke/PistonExtensionCycle.java", "m142-piston-extension"},
        {"tools/smoke/PistonRetractionCycle.java", "m143-piston-retraction"},
        {"tools/smoke/StickyPistonPullCycle.java", "m144-sticky-piston-pull"},
        {"tools/smoke/TwoBlockPistonCycle.java", "m145-two-block-piston"},
        {"tools/smoke/ObsidianPistonCycle.java", "m146-obsidian-piston-rejection"},
        {"tools/smoke/PistonPushLimitCycle.java", "m147-piston-push-limit"},
        {"tools/smoke/PigAiMovementCycle.java", "m148-pig-ai-movement"},
        {"tools/smoke/PigDeathCycle.java", "m149-pig-death"},
        {"tools/smoke/PigPorkDropCycle.java", "m150-pig-pork-drop"},
        {"tools/smoke/NetherrackFireCycle.java", "m151-netherrack-fire"},
        {"tools/smoke/FireWoolConsumptionCycle.java", "m152-fire-wool-consumption"},
        {"tools/smoke/DispenserEjectCycle.java", "m153-dispenser-eject"},
        {"tools/smoke/BoatSpawnCycle.java", "m154-boat-spawn"},
        {"tools/smoke/MinecartSpawnCycle.java", "m155-minecart-spawn"},
        {"tools/smoke/FarmlandHydrationCycle.java", "m156-farmland-hydration"},
        {"tools/smoke/BowArrowCycle.java", "m157-bow-arrow"},
        {"tools/smoke/BedCycle.java", "m158-bed"},
        {"tools/smoke/SugarCaneCycle.java", "m159-sugar-cane"},
        {"tools/smoke/CakeEatCycle.java", "m160-cake-eat"},
        {"tools/smoke/SnowballCycle.java", "m161-snowball"},
        {"tools/smoke/WoodenDoorCycle.java", "m162-wooden-door"},
        {"tools/smoke/TrapdoorCycle.java", "m163-trapdoor"},
        {"tools/smoke/PressurePlateCycle.java", "m164-pressure-plate"},
        {"tools/smoke/StoneButtonCycle.java", "m165-stone-button"},
        {"tools/smoke/NoteBlockCycle.java", "m166-note-block"},
        {"tools/smoke/CactusCycle.java", "m167-cactus"},
        {"tools/smoke/LabCycle.java", "lab-cycle"}
    };

    private SmokeSuite() {}

    static void run(Run run) throws Exception {
        for (String[] smoke : SMOKES) run.run(Arrays.asList("java", smoke[0], smoke[1]));
    }
}
