package worldline.smoke.shearssetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Shears oak leaves 18 and a living sheep, observing Packet21 18 plus Packet21 35 without death. */
public final class ShearsSetSmoke{
 private static final RemoteItemStack LEAF=new RemoteItemStack(18,1,0);private static final BlockState AIR=new BlockState(0,0),PLACED=new BlockState(18,8);
 private ShearsSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: ShearsSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,log,sheared,spawner;int column;RemoteDroppedItem leaf;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5},new int[]{1,2,17,18,359,52},new int[]{32,48,1,1,1,1},new int[]{0,0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==6,"shears-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded shears-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);log=place(actor,new BlockPosition(top.x()+3,top.y(),top.z()),BlockFace.UP,17);actor.selectHeldSlot(3);sheared=BlockFace.UP.adjacent(log);actor.placeHeldBlock(log,BlockFace.UP);actor.awaitBlock(sheared,PLACED);
   RemoteWorldView live=actor.sustainTicks(5);require(live.blockAt(sheared.x(),sheared.y(),sheared.z()).equals(PLACED),"live leaves drift");
   actor.selectHeldSlot(4);harvest(actor,sheared,5);actor.awaitBlock(sheared,AIR);leaf=actor.awaitDroppedItem(LEAF);require(leaf.item().equals(LEAF)&&leaf.item().legacyId()==18&&leaf.item().count()==1,"shears Packet21 leaf drop absent");
   actor.selectHeldSlot(5);spawner=place(actor,top,BlockFace.UP,52);actor.sustainTicks(5);actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.sheep(workspace,spawner);server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()>=1,"shears-set reload inventory drift");RemoteMobSpawn spawn=actor.awaitMobSpawn(91);require(spawn.legacyType()==91&&spawn.entityId()!=actor.state().entityId(),"sheep Packet24 identity drift");int shears=find(actor.inventory(),359);require(shears>=36,"shears absent from hotbar");actor.selectHeldSlot(shears-36);approach(actor,spawn);shears=find(actor.inventory(),359);require(shears>=36,"shears lost before use");actor.selectHeldSlot(shears-36);B173ShearsAccess.useOnMob(actor,spawn.entityId());actor.sustainTicks(20);RemoteDroppedItem drop=wool(actor);require(drop!=null&&drop.item().legacyId()==35&&drop.item().count()==1,"shears Packet21 wool drop absent");require(B173ShearsAccess.peekDeath(actor,spawn.entityId())==null,"Packet38 status 3 death after shears");RemoteMobMovement live=actor.awaitMobMovement(spawn.entityId());require(live.entityId()==spawn.entityId(),"sheared sheep movement identity drift");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass,log="+log.x()+":"+log.y()+":"+log.z()+":17:0,sheared="+sheared.x()+":"+sheared.y()+":"+sheared.z()+":18:8->0:0,spawner=52:0-sheep,mob=type91,shears=359,drops=packet21-18+packet21-35,death=no-packet38-status3,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+oak17+leaves18+sheep-spawner52|cause=packet14-shears359+packet7-interact-shears359|wire=packet53-air+packet21-id18+packet24-type91+packet21-id35+no-packet38-status3|oracle=shears-leaf-and-living-sheep-wool|"+evidence;System.out.println("WORLDLINE_M316_SHEARS="+evidence);System.out.println("WORLDLINE_M316_TRACE="+trace);System.out.println("WORLDLINE_M316_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static RemoteDroppedItem wool(B173WireClient a){for(int color=0;color<16;color++){RemoteDroppedItem item=a.peekDroppedItem(new RemoteItemStack(35,1,color));if(item!=null)return item;}return null;}
 private static int find(RemoteInventoryView view,int id){for(int slot=36;slot<=44;slot++)if(!view.slot(slot).empty()&&view.slot(slot).item().legacyId()==id)return slot;return -1;}
 private static void approach(B173WireClient a,RemoteMobSpawn spawn){for(int step=0;step<8;step++){PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=spawn.x()-here.x(),dy=spawn.y()-here.y(),dz=spawn.z()-here.z(),dist=Math.sqrt(dx*dx+dy*dy+dz*dz);if(dist<=2.5D)return;double s=Math.min(1D,4D/dist);a.moveAndObserve(dx*s,dy*s,dz*s,8);}}
 private static void harvest(B173WireClient a,BlockPosition target,int ticks){a.beginBreak(target);a.sustainTicks(ticks);a.finishBreak(target);}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic shears-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
