package worldline.smoke.squidinksetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Waits for official squid Packet24 type 94 in seed water and observes Packet21 ink sac 351:0. */
public final class SquidInkSetSmoke{
 private SquidInkSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SquidInkSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("SquidInk408")&&user.length()<=16,"squid-ink-set identity drift");
  Duration timeout=Duration.ofSeconds(600);B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,water;int column,fluid;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,276,320},new int[]{32,1,8},new int[]{0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==3,"squid-ink-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);water=new BlockPosition(top.x(),top.y()+1,top.z());fluid=initial.blockAt(local(water.x(),cx),water.y(),local(water.z(),cz)).legacyId();require(water(fluid),"seed water habitat absent");column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded squid-ink-set fixture");}
   require(column>=1&&actor.health()>=8,"surface dock escaped water column");worldline.test.WorldlineSmokeAwait.observe(actor,200);RemoteDroppedItem ink=killUntil(actor);require(ink.item().legacyId()==351&&ink.item().damage()==0,"squid Packet21 ink sac 351:0 absent");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",surface="+top.x()+":"+top.y()+":"+top.z()+":1:0,habitat="+water.x()+":"+water.y()+":"+water.z()+":"+fluid+":0,mob=type94,death=packet7-sword276+packet38-status3+packet29,drop=packet21-351:0,kills<=8,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=seed-water-column+surface-stone-dock|cause=official-diamond-sword-packet7|wire=packet24-type94+packet38-status3+packet29+packet21-351:0|oracle=squid-in-water-plus-ink-sac-drop|"+evidence;System.out.println("WORLDLINE_M408_SET="+evidence);System.out.println("WORLDLINE_M408_TRACE="+trace);System.out.println("WORLDLINE_M408_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static RemoteDroppedItem killUntil(B173WireClient a){RemoteDroppedItem found=null;int kills=0;while(found==null){require(++kills<=8,"official squid ink 351:0 absent after bounded kills");RemoteMobSpawn spawn=a.awaitMobSpawn(94);require(spawn.legacyType()==94&&spawn.entityId()!=a.state().entityId(),"squid Packet24 type 94 identity drift");require(wet(a,spawn),"squid Packet24 spawn escaped water habitat");kill(a,spawn);found=worldline.test.WorldlineSmokeAwait.awaitEntityOrNull(a,()->ink(a),value->value!=null,"squid ink drop",20);}require(found.item().legacyId()==351&&found.item().damage()==0,"squid Packet21 351:0 drift");return found;}
 private static void kill(B173WireClient a,RemoteMobSpawn spawn){int entity=spawn.entityId();close(a,spawn.x(),spawn.y(),spawn.z());for(int hit=0;hit<4;hit++){if(B173ShearsAccess.peekDeath(a,entity)!=null)break;strike(a,entity);}for(int hit=0;hit<8&&B173ShearsAccess.peekDeath(a,entity)==null;hit++){RemoteMobMovement move=a.awaitMobMovement(entity);close(a,move.toX(),move.toY(),move.toZ());strike(a,entity);}RemoteMobDeath death=a.awaitMobDeath(entity);require(death.entityId()==entity&&death.deathStatus()==3&&death.destroyPacket()==29,"squid Packet38/29 death drift");}
 private static void close(B173WireClient a,double x,double y,double z){for(int n=0;n<24;n++){heal(a);PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=x-here.x(),dy=y-here.y(),dz=z-here.z(),dist=Math.sqrt(dx*dx+dy*dy+dz*dz);if(dist<=2.5D)return;double s=Math.min(1D,2.0D/dist);a.moveAndObserve(dx*s,dy*s,dz*s,2);}}
 private static void strike(B173WireClient a,int entity){heal(a);int sword=find(a.inventory(),276);require(sword>=36,"diamond sword lost");a.selectHeldSlot(sword-36);a.attackMob(entity);worldline.test.WorldlineSmokeAwait.observe(a,10);heal(a);}
 private static void heal(B173WireClient a){int h=a.health();if(h==0)throw new IllegalStateException("actor died during squid ink");if(h>=17)return;int food=find(a.inventory(),320);if(food<36)return;a.selectHeldSlot(food-36);a.useSelectedItemInAir();worldline.test.WorldlineSmokeAwait.observe(a,5);}
 private static RemoteDroppedItem ink(B173WireClient a){for(int n=1;n<=3;n++){RemoteDroppedItem item=a.peekDroppedItem(new RemoteItemStack(351,n,0));if(item!=null)return item;}return null;}
 private static boolean wet(B173WireClient a,RemoteMobSpawn spawn){int x=(int)Math.floor(spawn.x()),y=(int)Math.floor(spawn.y()),z=(int)Math.floor(spawn.z());RemoteWorldView view=worldline.test.WorldlineSmokeAwait.observe(a,1);for(int dy=-1;dy<=1;dy++){int at=y+dy;if(at<0||at>127)continue;if(water(view.blockAt(x,at,z).legacyId()))return true;}return false;}
 private static int find(RemoteInventoryView view,int id){for(int slot=36;slot<=44;slot++)if(!view.slot(slot).empty()&&view.slot(slot).item().legacyId()==id)return slot;return -1;}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic squid-ink-set water foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
