package worldline.smoke.storagecartsb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Chest-minecart Packet100 Minecart window plus furnace-minecart type-12 spawn and Packet7 no-window interact. */
public final class StorageCartsSmoke{
 private StorageCartsSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: StorageCartsSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  require(user.length()<=16,"username exceeds 16");B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,rail,east1,east2,furnaceRail;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3},new int[]{1,66,342,343},new int[]{32,2,1,1},new int[]{0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==4,"storage carts inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded storage carts fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);rail=place(actor,top,BlockFace.UP,66);actor.selectHeldSlot(2);actor.useHeldItemOnBlock(rail,BlockFace.UP);RemoteObjectSpawn chest=actor.awaitObjectSpawn(11);
   require(chest.entityId()!=actor.state().entityId()&&chest.type()==11&&chest.type()!=10&&chest.throwerId()==0&&chest.velocityX()==0&&chest.velocityY()==0&&chest.velocityZ()==0&&chest.fixedX()==rail.x()*32+16&&chest.fixedY()==rail.y()*32+27&&chest.fixedZ()==rail.z()*32+16,"chest cart packet bounds drift: type="+chest.type()+",thrower="+chest.throwerId()+",fixed="+chest.fixedX()+":"+chest.fixedY()+":"+chest.fixedZ()+",rail="+rail);
   actor.selectHeldSlot(2);actor.sustainTicks(5);RemoteContainerWindow window=B173ChestCartWindows.open(actor,chest.entityId());RemoteWindowDescriptor d=window.descriptor();int cartItems=0;for(int i=0;i<27;i++)if(!window.inventory().slot(i).empty())cartItems++;
   require(d.kind()==RemoteWindowKind.CHEST&&"Minecart".equals(d.title())&&d.containerSlots()==27&&window.inventory().size()==63&&cartItems==0&&d.windowId()>=1&&d.windowId()<=100,"chest cart window drift: kind="+d.kind()+",title="+d.title()+",slots="+d.containerSlots()+",total="+window.inventory().size()+",cartItems="+cartItems);
   RemoteWindowClosure closed=actor.closeWindow();require(closed.closedWindow().descriptor().windowId()==d.windowId()&&"Minecart".equals(closed.closedWindow().descriptor().title()),"chest cart close drift");
   actor.selectHeldSlot(0);east1=place(actor,top,BlockFace.EAST,1);east2=place(actor,east1,BlockFace.EAST,1);actor.selectHeldSlot(1);furnaceRail=place(actor,east2,BlockFace.UP,66);actor.selectHeldSlot(3);actor.useHeldItemOnBlock(furnaceRail,BlockFace.UP);RemoteObjectSpawn furnace=actor.awaitObjectSpawn(12);
   require(furnace.entityId()!=actor.state().entityId()&&furnace.entityId()!=chest.entityId()&&furnace.type()==12&&furnace.type()!=11&&furnace.type()!=10&&furnace.throwerId()==0&&furnace.velocityX()==0&&furnace.velocityY()==0&&furnace.velocityZ()==0&&furnace.fixedX()==furnaceRail.x()*32+16&&furnace.fixedY()==furnaceRail.y()*32+27&&furnace.fixedZ()==furnaceRail.z()*32+16,"furnace cart packet bounds drift: type="+furnace.type()+",thrower="+furnace.throwerId()+",fixed="+furnace.fixedX()+":"+furnace.fixedY()+":"+furnace.fixedZ()+",rail="+furnaceRail);
   actor.selectHeldSlot(3);actor.sustainTicks(5);B173FurnaceCartInteract.use(actor,furnace.entityId());actor.sustainTicks(5);
   actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",rail="+rail.x()+":"+rail.y()+":"+rail.z()+":66:0,chest=type"+chest.type()+"+thrower0+fixed"+chest.fixedX()+":"+chest.fixedY()+":"+chest.fixedZ()+",window=type0+Minecart+slots"+d.containerSlots()+"+total"+window.inventory().size()+",close=clean,furnaceRail="+furnaceRail.x()+":"+furnaceRail.y()+":"+furnaceRail.z()+":66:0,furnace=type"+furnace.type()+"+thrower0+fixed"+furnace.fixedX()+":"+furnace.fixedY()+":"+furnace.fixedZ()+",interact=packet7+nowindow,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-rail66-pair|cause=packet7-interact-chestminecart+packet15-furnace-minecart343|wire=packet23-type11+packet100-type0-Minecart-27+packet23-type12+packet7-nowindow|oracle=storage-carts-type11-window+type12-spawn-interact|"+evidence;System.out.println("WORLDLINE_M311_CARTS="+evidence);System.out.println("WORLDLINE_M311_TRACE="+trace);System.out.println("WORLDLINE_M311_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic storage carts foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
