package worldline.smoke.farmlandsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Hoes official dirt 3 into farmland 60, then jump-tramples it back to dirt 3. */
public final class FarmlandSetSmoke{
 private FarmlandSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: FarmlandSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,dirt;int column;PlayerPose pose;BlockState farm=new BlockState(60,0),trampled=new BlockState(3,0);
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,3,290},new int[]{64,1,1},new int[]{0,0,0});actor.connect();pose=actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==3,"farmland-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();require(++column<=15,"water column exceeded farmland-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);pose=actor.moveAndObserve(0D,1D,0D,1).resulting();column++;}
   actor.selectHeldSlot(1);dirt=place(actor,top,BlockFace.UP,3);actor.selectHeldSlot(2);till(actor,dirt);pose=actor.moveAndObserve(dirt.x()+0.5D-pose.x(),dirt.y()+1.0D-pose.y(),dirt.z()+0.5D-pose.z(),2).resulting();require(worldline.test.WorldlineSmokeAwait.observe(actor,1).blockAt(dirt.x(),dirt.y(),dirt.z()).equals(farm),"live till 3->60 drift");trample(actor,dirt);require(worldline.test.WorldlineSmokeAwait.observe(actor,2).blockAt(dirt.x(),dirt.y(),dirt.z()).equals(trampled),"live trample 60->3 drift");actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(top.x(),cx),top.y(),local(top.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(dirt.x(),cx),dirt.y(),local(dirt.z(),cz)).equals(trampled),"persisted farmland-set dirt 3:0 drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,cell="+dirt.x()+":"+dirt.y()+":"+dirt.z()+":3:0,hoe=290,till=3->60,trample=60->3,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-dirt3|cause=packet15-wooden-hoe290+packet13-jump-fall|wire=packet53-farmland60+dirt3|oracle=live-till-3->60+live-trample-60->3+fresh-login-dirt3:0|"+evidence;System.out.println("WORLDLINE_M304_SET="+evidence);System.out.println("WORLDLINE_M304_TRACE="+trace);System.out.println("WORLDLINE_M304_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static void till(B173WireClient a,BlockPosition dirt)throws Exception{a.useHeldItemOnBlock(dirt,BlockFace.UP);a.awaitBlock(dirt,new BlockState(60,0));}
 private static void trample(B173WireClient a,BlockPosition farm)throws Exception{int[] step={0};worldline.test.WorldlineSmokeAwait.awaitCheckedEntity(a,()->{a.moveAndObserve(0D,1.25D,0D,1);a.moveAndObserve(0D,-1.25D,0D,1);a.moveAndObserve((step[0]++%2==0)?0.35D:-0.35D,0D,0D,2);return worldline.test.WorldlineSmokeAwait.observe(a,1).blockAt(farm.x(),farm.y(),farm.z());},new BlockState(3,0)::equals,"trampled farmland",80);}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic farmland-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
