package worldline.smoke.squidlanddeathsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places a dry y<63 squid spawner and observes Packet24 type 94 land death Packet38 status 3 plus Packet29. */
public final class SquidLandDeathSetSmoke{
 private SquidLandDeathSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SquidLandDeathSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("SquidLand466")&&user.length()<=16,"squid-land-death-set identity drift");
  Duration timeout=Duration.ofSeconds(180);B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top=null,spawner=null;int column=0;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4},new int[]{1,1,1,52,278},new int[]{64,64,64,1,1},new int[]{0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==5,"squid-land-death-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;held(actor,1);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded squid-land-death-set fixture");}
   held(actor,1);pad(actor,top);for(int ring=2;ring>=1;ring--)for(int dx=-ring;dx<=ring;dx++)for(int dz=-ring;dz<=ring;dz++)if(Math.max(Math.abs(dx),Math.abs(dz))==ring)open(actor,top,dx,dz);spawner=core(actor,top);require(spawner.y()>45&&spawner.y()<63,"squid spawner escaped type-94 land band");worldline.test.WorldlineSmokeAwait.observe(actor,5);actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  require(top!=null&&spawner!=null,"squid land room absent");Thread.sleep(1000L);B173SpawnerSeed.squid(workspace,spawner);B173PlayerSeed.writeInventory(workspace,user,top.x()+1.5D,top.y()-1.0D,top.z()+0.5D,new int[]{0,1,2,3},new int[]{1,276,320,278},new int[]{32,1,8,1},new int[]{0,0,0,0});server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()>=1,"squid-land-death-set reload inventory drift");PlayerPose station=actor.moveAndObserve(0D,0D,0D,2).resulting();require(Math.abs(station.x()-spawner.x()-1.5D)<=0.25D&&Math.abs(station.y()-spawner.y())<=0.25D&&Math.abs(station.z()-spawner.z()-0.5D)<=0.25D,"dry-room station drift "+station.x()+":"+station.y()+":"+station.z());RemoteMobSpawn spawn=land(actor,spawner,station);require(spawn.legacyType()==94&&spawn.entityId()!=actor.state().entityId(),"squid Packet24 type 94 identity drift");kill(actor,spawn);require(!wet(actor,spawn),"selected squid spawn was wet");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",surface="+top.x()+":"+top.y()+":"+top.z()+":1:0,floor=7x7,pen=5x5-open-dry-y"+(top.y()-1)+",spawner="+spawner.x()+":"+spawner.y()+":"+spawner.z()+":52:0,entityid=Squid,land=true,mob=type94,death=land+packet7-sword276+packet38-status3+packet29,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=seed-water-dock+open-dry-y<63-squid-spawner52|cause=nbt-entityid-squid+land-sword276|wire=packet24-type94+packet38-status3+packet29|oracle=squid-type94-land-death-not-m408-ink|"+evidence;System.out.println("WORLDLINE_M466_SET="+evidence);System.out.println("WORLDLINE_M466_TRACE="+trace);System.out.println("WORLDLINE_M466_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static RemoteMobSpawn land(B173WireClient a,BlockPosition target,PlayerPose station){RemoteMobSpawn spawn=null;int n=0;StringBuilder seen=new StringBuilder();while(spawn==null){if(++n>32)throw new IllegalStateException("official close dry squid Packet24 type 94 absent; observed="+seen);RemoteMobSpawn next=a.awaitMobSpawn(94);require(next.legacyType()==94&&next.entityId()!=a.state().entityId(),"squid Packet24 type 94 identity drift");double dx=next.x()-target.x()-0.5D,dy=next.y()-target.y(),dz=next.z()-target.z()-0.5D,distance=dx*dx+dy*dy+dz*dz,rx=next.x()-station.x(),ry=next.y()-station.y(),rz=next.z()-station.z(),range=rx*rx+ry*ry+rz*rz;boolean nearby=distance<=25D&&range<=6.25D,water=nearby&&wet(a,next);if(seen.length()>0)seen.append(';');seen.append(next.entityId()).append('@').append(next.x()).append(',').append(next.y()).append(',').append(next.z()).append(" d2=").append(distance).append(" range2=").append(range).append(" wet=").append(nearby?Boolean.toString(water):"skipped");if(nearby&&!water)spawn=next;}return spawn;}
 private static void kill(B173WireClient a,RemoteMobSpawn spawn){int entity=spawn.entityId();double x=spawn.x(),z=spawn.z();for(int hit=0;hit<8&&B173ShearsAccess.peekDeath(a,entity)==null;hit++){if(hit>0){RemoteMobMovement move;while((move=B173ShearsAccess.pollMovement(a,entity))!=null){x=move.toX();z=move.toZ();}approach(a,x,z);}strike(a,entity);}require(B173ShearsAccess.peekDeath(a,entity)!=null,"squid resisted eight tracked diamond-sword attacks");RemoteMobDeath death=a.awaitMobDeath(entity);require(death.entityId()==entity&&death.deathStatus()==3&&death.destroyPacket()==29,"squid land Packet38/29 death drift");}
 private static void strike(B173WireClient a,int entity){int sword=find(a.inventory(),276);require(sword>=36,"diamond sword lost");a.selectHeldSlot(sword-36);a.attackMob(entity);worldline.test.WorldlineSmokeAwait.observe(a,22);}
 private static void close(B173WireClient a,double x,double y,double z){for(int n=0;n<24;n++){PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=x-here.x(),dy=y-here.y(),dz=z-here.z(),dist=Math.sqrt(dx*dx+dy*dy+dz*dz);if(dist<=2.5D)return;double s=Math.min(1D,2.0D/dist);a.moveAndObserve(dx*s,dy*s,dz*s,2);}PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=x-here.x(),dy=y-here.y(),dz=z-here.z();require(dx*dx+dy*dy+dz*dz<=6.25D,"approach failed");}
 private static void approach(B173WireClient a,double x,double z){PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=x-here.x(),dz=z-here.z(),dist=Math.hypot(dx,dz);if(dist<1D)a.moveAndObserve(2D,0D,0D,4);else if(dist>2.5D){double s=(dist-2D)/dist;a.moveAndObserve(dx*s,0D,dz*s,4);}}
 private static boolean wet(B173WireClient a,RemoteMobSpawn spawn){int x=(int)Math.floor(spawn.x()),y=(int)Math.floor(spawn.y()),z=(int)Math.floor(spawn.z());RemoteWorldView view=a.awaitRemoteChunk(x>>4,z>>4);for(int dy=-1;dy<=1;dy++){int at=y+dy;if(at<0||at>127)continue;if(water(view.blockAt(x,at,z).legacyId()))return true;}return false;}
 private static void pad(B173WireClient a,BlockPosition c)throws Exception{held(a,1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){place(a,new BlockPosition(c.x()-r+1,c.y(),c.z()+z),BlockFace.WEST,1);place(a,new BlockPosition(c.x()+r-1,c.y(),c.z()+z),BlockFace.EAST,1);}for(int x=-r+1;x<r;x++){place(a,new BlockPosition(c.x()+x,c.y(),c.z()-r+1),BlockFace.NORTH,1);place(a,new BlockPosition(c.x()+x,c.y(),c.z()+r-1),BlockFace.SOUTH,1);}place(a,new BlockPosition(c.x()-r,c.y(),c.z()-r+1),BlockFace.NORTH,1);place(a,new BlockPosition(c.x()-r,c.y(),c.z()+r-1),BlockFace.SOUTH,1);place(a,new BlockPosition(c.x()+r,c.y(),c.z()-r+1),BlockFace.NORTH,1);place(a,new BlockPosition(c.x()+r,c.y(),c.z()+r-1),BlockFace.SOUTH,1);}
  for(int dx=-3;dx<=3;dx++)for(int dz=-3;dz<=3;dz++){BlockPosition cell=new BlockPosition(c.x()+dx,c.y(),c.z()+dz);close(a,cell.x()+0.5D,c.y()+1.0D,cell.z()+0.5D);place(a,cell,BlockFace.DOWN,1);}}
 private static void open(B173WireClient a,BlockPosition roof,int dx,int dz)throws Exception{BlockPosition top=new BlockPosition(roof.x()+dx,roof.y(),roof.z()+dz),mid=new BlockPosition(top.x(),top.y()-1,top.z());close(a,top.x()+0.5D,roof.y()+1.0D,top.z()+0.5D);hollow(a,top);place(a,mid,BlockFace.DOWN,1);hollow(a,mid);}
 private static BlockPosition core(B173WireClient a,BlockPosition roof)throws Exception{BlockPosition mid=new BlockPosition(roof.x(),roof.y()-1,roof.z()),floor=new BlockPosition(roof.x(),roof.y()-2,roof.z());close(a,roof.x()+3.5D,roof.y()+1.0D,roof.z()+0.5D);hollow(a,roof);place(a,mid,BlockFace.DOWN,1);hollow(a,mid);held(a,52);BlockPosition spawner=place(a,floor,BlockFace.UP,52);hollow(a,new BlockPosition(roof.x()+1,roof.y(),roof.z()));return spawner;}
 private static void hollow(B173WireClient a,BlockPosition cell)throws Exception{int have=worldline.test.WorldlineSmokeAwait.observe(a,1).blockAt(cell.x(),cell.y(),cell.z()).legacyId();if(have==0)return;int pick=find(a.inventory(),278);require(pick>=36,"diamond pick lost");a.selectHeldSlot(pick-36);a.look(0F,90F);for(int n=0;n<4&&have!=8&&have!=9;n++){a.beginBreak(cell);worldline.test.WorldlineSmokeAwait.observe(a,20);a.finishBreak(cell);RemoteWorldView clear=worldline.test.WorldlineSmokeAwait.awaitBlockOrNull(a,cell,new BlockState(0,0),5);if(clear!=null)return;have=worldline.test.WorldlineSmokeAwait.observe(a,1).blockAt(cell.x(),cell.y(),cell.z()).legacyId();}throw new IllegalStateException("hollow failed "+cell.x()+":"+cell.y()+":"+cell.z()+"="+have);}
 private static void held(B173WireClient a,int id){int slot=find(a.inventory(),id);require(slot>=36,"item "+id+" lost");a.selectHeldSlot(slot-36);}
 private static int find(RemoteInventoryView view,int id){for(int slot=36;slot<=44;slot++)if(!view.slot(slot).empty()&&view.slot(slot).item().legacyId()==id)return slot;return -1;}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);if(worldline.test.WorldlineSmokeAwait.observe(a,1).blockAt(target.x(),target.y(),target.z()).legacyId()==id)return target;held(a,id);a.placeHeldBlock(support,face);RemoteWorldView placed=worldline.test.WorldlineSmokeAwait.awaitBlockOrNull(a,target,new BlockState(id,0),16);if(placed==null){held(a,id);a.placeHeldBlock(support,face);worldline.test.WorldlineSmokeAwait.awaitBlock(a,target,new BlockState(id,0),16);}return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic squid-land-death-set water foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
