package worldline.smoke.bowmobhitsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Air-uses bow 261 so Packet23 type 60 hits Packet24 pig 90 and zombie 54 with Packet38 status 2. */
public final class BowMobHitSetSmoke{
 private BowMobHitSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: BowMobHitSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("BowHit462")&&user.length()<=16,"bow-mob-hit-set identity drift");
  Duration timeout=Duration.ofSeconds(180);B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,spawner;int column;RemoteObjectSpawn pigArrow,zombieArrow;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5,6,7},new int[]{1,2,85,52,261,262,320,322},new int[]{32,48,32,1,1,16,8,4},new int[]{0,0,0,0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==8,"bow-mob-hit-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded bow-mob-hit-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);for(int dx=-3;dx<=3;dx++)for(int dz=-3;dz<=3;dz++)if(dx==-3||dx==3||dz==-3||dz==3)place(actor,new BlockPosition(top.x()+dx,top.y(),top.z()+dz),BlockFace.UP,85);
   actor.selectHeldSlot(3);spawner=place(actor,top,BlockFace.UP,52);RemoteMobSpawn pig=B173BowMobHit.near(actor,90,spawner.x()+0.5D,spawner.y(),spawner.z()+0.5D);require(pig.legacyType()==90&&pig.entityId()!=actor.state().entityId()&&pig.legacyType()!=51,"pig Packet24 identity drift");pigArrow=B173BowMobHit.shoot(actor,pig);require(pigArrow.type()==60&&(pigArrow.throwerId()==0||pigArrow.throwerId()==actor.state().entityId()),"pig arrow Packet23 type 60 drift");actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.entity(workspace,spawner,"Zombie");B173PlayerSeed.writeInventory(workspace,user,top.x()+0.5D,top.y()+1.0D,top.z()+0.5D,new int[]{0,1,2,3},new int[]{261,262,320,322},new int[]{1,16,8,4},new int[]{0,0,0,0});server=B173DedicatedServer.monsters(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==4,"bow-mob-hit-set reload inventory drift");server.setTime(14000L);RemoteMobSpawn zombie=B173BowMobHit.near(actor,54,spawner.x()+0.5D,spawner.y(),spawner.z()+0.5D);require(zombie.legacyType()==54&&zombie.entityId()!=actor.state().entityId()&&zombie.legacyType()!=51&&zombie.legacyType()!=90,"zombie Packet24 identity drift");zombieArrow=B173BowMobHit.shoot(actor,zombie);require(zombieArrow.type()==60&&(zombieArrow.throwerId()==0||zombieArrow.throwerId()==actor.state().entityId()),"zombie arrow Packet23 type 60 drift");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass+fence85,spawner="+spawner.x()+":"+spawner.y()+":"+spawner.z()+":52:0,bow=261,arrow=262,mobs=type90+type54,night=14000,wire=packet23-type60+packet38-status2,thrower=actor,hits=pig90+zombie54,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+fence85-pen+spawner52+bow261+arrow262|cause=packet15-air-bow261+nbt-entityid-zombie+time-14000|wire=packet24-type90+packet24-type54+packet23-type60+packet38-status2|oracle=player-arrow-hit-pig-and-zombie-not-m436-collect-or-m332-craft|"+evidence;System.out.println("WORLDLINE_M462_SET="+evidence);System.out.println("WORLDLINE_M462_TRACE="+trace);System.out.println("WORLDLINE_M462_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic bow-mob-hit-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
