package worldline.smoke.sugarcanedrybreaksetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Plants official sugar cane beside still water, replaces that water, then neighbor-updates the cane so it pops. */
public final class SugarCaneDryBreakSetSmoke{
 private SugarCaneDryBreakSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SugarCaneDryBreakSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  require(seed==17320110707L&&user.equals("CaneDry607")&&user.length()<=16,"sugar-cane-dry-break identity drift");
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,east,dirt,water,cane,neighbor;int column;RemoteDroppedItem drop;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3},new int[]{1,3,9,338},new int[]{32,1,1,8},new int[]{0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==4,"sugar-cane-dry-break inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded sugar-cane-dry-break fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   east=place(actor,top,BlockFace.EAST,1);actor.selectHeldSlot(1);dirt=place(actor,top,BlockFace.UP,3);actor.selectHeldSlot(2);water=place(actor,east,BlockFace.UP,9);require(worldline.test.WorldlineSmokeAwait.observe(actor,5).blockAt(water.x(),water.y(),water.z()).equals(new BlockState(9,0)),"still water 9 drift");
   actor.selectHeldSlot(3);actor.useHeldItemOnBlock(dirt,BlockFace.UP);cane=BlockFace.UP.adjacent(dirt);actor.awaitBlock(cane,new BlockState(83,0));require(worldline.test.WorldlineSmokeAwait.observe(actor,5).blockAt(cane.x(),cane.y(),cane.z()).equals(new BlockState(83,0)),"planted cane popped");
   actor.selectHeldSlot(0);actor.look(-90F,0F);actor.placeHeldBlock(dirt,BlockFace.EAST);actor.awaitBlock(water,new BlockState(1,0));require(worldline.test.WorldlineSmokeAwait.observe(actor,5).blockAt(cane.x(),cane.y(),cane.z()).equals(new BlockState(83,0))&&worldline.test.WorldlineSmokeAwait.observe(actor,1).blockAt(water.x(),water.y(),water.z()).equals(new BlockState(1,0)),"dry cane popped before neighbor update");
   neighbor=BlockFace.EAST.adjacent(cane);actor.placeHeldBlock(cane,BlockFace.EAST);actor.awaitBlock(neighbor,new BlockState(1,0));worldline.test.WorldlineSmokeAwait.awaitBlock(actor,cane,new BlockState(0,0),20);drop=actor.awaitDroppedItem(new RemoteItemStack(338,1,0));require(drop.item().equals(new RemoteItemStack(338,1,0))&&drop.item().legacyId()==338&&drop.item().count()==1,"Packet21 reed 338 drop absent");
   actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(dirt.x(),cx),dirt.y(),local(dirt.z(),cz)).equals(new BlockState(3,0))&&after.blockAt(local(water.x(),cx),water.y(),local(water.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(cane.x(),cx),cane.y(),local(cane.z(),cz)).equals(new BlockState(0,0))&&after.blockAt(local(neighbor.x(),cx),neighbor.y(),local(neighbor.z(),cz)).equals(new BlockState(1,0)),"persisted sugar-cane-dry-break drift");
   String evidence="column="+column+",dirt="+dirt.x()+":"+dirt.y()+":"+dirt.z()+":3:0,water="+water.x()+":"+water.y()+":"+water.z()+":9:0->1:0,cane="+cane.x()+":"+cane.y()+":"+cane.z()+":83:0->0:0,neighbor="+neighbor.x()+":"+neighbor.y()+":"+neighbor.z()+":1:0,drops=packet21-338,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-dirt3+still-water9+reed83|cause=packet15-item1-replace-water9+packet15-item1-east-neighbor|wire=packet53-reed83->0+packet21-338|oracle=dry-break-pop+fresh-login-air|"+evidence;System.out.println("WORLDLINE_M607_SET="+evidence);System.out.println("WORLDLINE_M607_TRACE="+trace);System.out.println("WORLDLINE_M607_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic sugar-cane-dry-break foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
