package worldline.smoke.sworddamagesetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Packet7 wood/iron/diamond hits on living pigs, freezing material-specific death and attacker Packet8 20. */
public final class SwordDamageSetSmoke{
 private SwordDamageSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SwordDamageSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("SwordDmg353")&&user.length()<=16,"sword-damage identity drift");
  Duration timeout=Duration.ofSeconds(180);B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5,6},new int[]{1,2,85,52,268,267,276},new int[]{32,48,32,1,1,1,1},new int[]{0,0,0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==7&&actor.awaitHealth(20)==20,"sword-damage inventory or health drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded sword-damage fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);for(int dx=-3;dx<=3;dx++)for(int dz=-3;dz<=3;dz++)if(dx==-3||dx==3||dz==-3||dz==3)place(actor,new BlockPosition(top.x()+dx,top.y(),top.z()+dz),BlockFace.UP,85);
   actor.selectHeldSlot(3);place(actor,top,BlockFace.UP,52);strike(actor,268,2,top);strike(actor,267,1,top);strike(actor,276,1,top);require(actor.awaitHealth(20)==20,"attacker Packet8 health drift");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass,fence=85-perimeter,spawner=52:0,mob=type90,swords=268:2live+kill+267:1live+kill+276:1live+kill,health=20,hurt=packet38-status2,death=packet38-status3+packet29,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+fence85-pen+default-spawner52|cause=packet7-sword268+packet7-sword267+packet7-sword276|wire=packet38-status2+packet38-status3+packet29+packet8-health20|oracle=wood-iron-diamond-hits-to-kill+attacker-packet8-20|"+evidence;System.out.println("WORLDLINE_M353_DAMAGE="+evidence);System.out.println("WORLDLINE_M353_TRACE="+trace);System.out.println("WORLDLINE_M353_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static void strike(B173WireClient a,int sword,int liveHits,BlockPosition top)throws Exception{RemoteMobSpawn spawn=a.awaitMobSpawn(90);require(spawn.legacyType()==90&&spawn.entityId()!=a.state().entityId(),"pig Packet24 identity drift");int slot=find(a.inventory(),sword);require(slot>=36,"sword "+sword+" absent from hotbar");a.selectHeldSlot(slot-36);for(int hit=0;hit<liveHits;hit++){swing(a,spawn.entityId(),sword,top);require(B173SwordDamage.peekDeath(a,spawn.entityId())==null,"early Packet38 status 3 sword="+sword+" hit="+(hit+1));}int extra=0;while(B173SwordDamage.peekDeath(a,spawn.entityId())==null){require(++extra<=8,"sword "+sword+" failed to kill after live hits");swing(a,spawn.entityId(),sword,top);}RemoteMobDeath death=a.awaitMobDeath(spawn.entityId());require(death.entityId()==spawn.entityId()&&death.deathStatus()==3&&death.hurtObserved()&&death.destroyPacket()==29,"sword "+sword+" death drift");require(a.health()==20,"attacker Packet8 dropped during sword "+sword);}
 private static void swing(B173WireClient a,int entity,int sword,BlockPosition top)throws Exception{station(a,top);B173SwordDamage.attack(a,entity,sword);a.sustainTicks(12);}
 private static int find(RemoteInventoryView view,int id){for(int slot=36;slot<=44;slot++)if(!view.slot(slot).empty()&&view.slot(slot).item().legacyId()==id)return slot;return -1;}
 private static void station(B173WireClient a,BlockPosition top){PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();a.moveAndObserve((top.x()+0.5D)-here.x(),(top.y()+1.1D)-here.y(),(top.z()+0.5D)-here.z(),8);}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic sword-damage foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
