package worldline.smoke.machineblockcraftsb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Workbench-crafts TNT 46, piston 33, and sticky piston 29 on official b1.7.3. */
public final class MachineBlockCraftsSmoke{
 private MachineBlockCraftsSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: MachineBlockCraftsSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  require(user.length()<=16&&B173MachineBlockCrafts.TNT==46&&B173MachineBlockCrafts.PISTON==33&&B173MachineBlockCrafts.STICKY==29,"machine-block identities drifted");
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,bench;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5,6,7,8},new int[]{1,58,12,289,5,4,265,331,341},new int[]{32,1,4,5,6,8,2,2,1},new int[]{0,0,0,0,0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==9,"machine-block inventory seed drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded machine-block fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);bench=BlockFace.UP.adjacent(top);actor.placeHeldBlock(top,BlockFace.UP);actor.awaitBlock(bench,new BlockState(58,0));actor.sustainTicks(5);actor.selectHeldSlot(1);require(actor.inventory().slot(37).empty(),"workbench hand was not consumed");actor.openWorkbench(bench,BlockFace.UP);int[]ids=B173MachineBlockCrafts.apply(actor);require(ids[0]==46&&ids[1]==33&&ids[2]==29&&hasFamily(actor.inventory()),"machine-block craft results drifted");actor.closeWindow();actor.close();awaitPlayers(server,0);server.save();require(server.player(user).inventoryItems()==4,"machine-block persistence count drift");
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();require(hasFamily(reader.awaitInventory()),"persisted machine-block crafts drifted");RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(top.x(),cx),top.y(),local(top.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(bench.x(),cx),bench.y(),local(bench.z(),cz)).equals(new BlockState(58,0)),"persisted workbench 58:0 drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,workbench="+bench.x()+":"+bench.y()+":"+bench.z()+":58:0,crafts=46,33,29,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=workbench58+sand12x4+gunpowder289x5+planks5x6+cobble4x8+ingot265x2+redstone331x2+slime341|cause=packet102-workbench-tnt46+piston33+sticky29|wire=packet106-accepted+packet200-craft-stat|oracle=craft-output-46-33-29+fresh-login+not-place+not-eject|"+evidence;System.out.println("WORLDLINE_M371_CRAFTS="+evidence);System.out.println("WORLDLINE_M371_TRACE="+trace);System.out.println("WORLDLINE_M371_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static boolean hasFamily(RemoteInventoryView view){return has(view,46)&&has(view,33)&&has(view,29)&&!has(view,12)&&!has(view,289)&&!has(view,5)&&!has(view,4)&&!has(view,265)&&!has(view,331)&&!has(view,341);}
 private static boolean has(RemoteInventoryView view,int id){for(int s=9;s<=44;s++)if(!view.slot(s).empty()&&view.slot(s).item().legacyId()==id)return true;return false;}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic machine-block foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
