package worldline.smoke.cropharvestsb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Harvests mature wheat 59, sugar cane 83, and cactus 81; freezes Packet21 296, 338, and 81. */
public final class CropHarvestsSmoke{
 private static final RemoteItemStack WHEAT=new RemoteItemStack(296,1,0),REED=new RemoteItemStack(338,1,0),CACTUS_DROP=new RemoteItemStack(81,1,0);
 private static final BlockState AIR=new BlockState(0,0),YOUNG=new BlockState(59,0),MATURE=new BlockState(59,7),CANE=new BlockState(83,0),DIRT=new BlockState(3,0),WATER=new BlockState(9,0),SAND=new BlockState(12,0);
 private CropHarvestsSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: CropHarvestsSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,east,south,south2,caneSoil,plot,water,crop,cane,sand,cactus;int column;RemoteDroppedItem wheatDrop,caneDrop,cactusDrop;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5,6,7,8},new int[]{1,3,9,290,295,351,338,12,81},new int[]{64,16,8,1,8,8,1,1,1},new int[]{0,0,0,0,0,15,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==9&&actor.awaitHealth(20)==20,"crop-harvest inventory or health drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(waterId(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded crop-harvest fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   place(actor,top,BlockFace.NORTH,1);east=place(actor,top,BlockFace.EAST,1);south=place(actor,top,BlockFace.SOUTH,1);south2=place(actor,south,BlockFace.SOUTH,1);BlockPosition caneSupport=place(actor,east,BlockFace.SOUTH,1);actor.selectHeldSlot(7);sand=place(actor,south2,BlockFace.UP,12);actor.moveAndObserve(0D,0D,-1D,2);
   actor.selectHeldSlot(1);plot=place(actor,top,BlockFace.UP,3);caneSoil=place(actor,caneSupport,BlockFace.UP,3);actor.selectHeldSlot(3);till(actor,plot);actor.selectHeldSlot(2);water=place(actor,east,BlockFace.UP,9);require(actor.sustainTicks(5).blockAt(water.x(),water.y(),water.z()).equals(WATER),"still water 9 drift");actor.selectHeldSlot(4);crop=sow(actor,plot);require(actor.sustainTicks(5).blockAt(crop.x(),crop.y(),crop.z()).equals(YOUNG),"planted wheat drift");
   actor.selectHeldSlot(6);actor.useHeldItemOnBlock(caneSoil,BlockFace.UP);cane=BlockFace.UP.adjacent(caneSoil);actor.awaitBlock(cane,CANE);require(actor.sustainTicks(5).blockAt(cane.x(),cane.y(),cane.z()).equals(CANE),"planted cane popped");
   actor.selectHeldSlot(8);cactus=place(actor,sand,BlockFace.UP,81);require(actor.sustainTicks(5).blockAt(cactus.x(),cactus.y(),cactus.z()).legacyId()==81&&actor.health()==20,"pre-break cactus fixture drift");
   actor.selectHeldSlot(5);actor.useHeldItemOnBlock(crop,BlockFace.UP);actor.awaitBlock(crop,MATURE);require(actor.sustainTicks(5).blockAt(crop.x(),crop.y(),crop.z()).equals(MATURE),"live mature wheat drift");
   harvest(actor,crop,2);actor.awaitBlock(crop,AIR);wheatDrop=actor.awaitDroppedItem(WHEAT);require(wheatDrop.item().equals(WHEAT)&&wheatDrop.item().legacyId()==296&&wheatDrop.item().count()==1,"wheat Packet21 296 absent");
   harvest(actor,cane,1);actor.awaitBlock(cane,AIR);caneDrop=actor.awaitDroppedItem(REED);require(caneDrop.item().equals(REED)&&caneDrop.item().legacyId()==338&&caneDrop.item().count()==1,"cane Packet21 338 absent");
   harvest(actor,cactus,20);actor.awaitBlock(cactus,AIR);cactusDrop=actor.awaitDroppedItem(CACTUS_DROP);require(cactusDrop.item().equals(CACTUS_DROP)&&cactusDrop.item().legacyId()==81&&cactusDrop.item().count()==1&&actor.health()==20,"cactus Packet21 81 absent");
   RemoteWorldView live=actor.sustainTicks(5);require(live.blockAt(crop.x(),crop.y(),crop.z()).equals(AIR)&&live.blockAt(cane.x(),cane.y(),cane.z()).equals(AIR)&&live.blockAt(cactus.x(),cactus.y(),cactus.z()).equals(AIR)&&live.blockAt(plot.x(),plot.y(),plot.z()).legacyId()==60&&live.blockAt(caneSoil.x(),caneSoil.y(),caneSoil.z()).equals(DIRT)&&live.blockAt(sand.x(),sand.y(),sand.z()).equals(SAND)&&live.blockAt(water.x(),water.y(),water.z()).equals(WATER)&&actor.health()==20,"crop-harvest fixture drift");
   String evidence="column="+column+",wheat="+crop.x()+":"+crop.y()+":"+crop.z()+":59:0->59:7->0:0,seeds=295,cane="+cane.x()+":"+cane.y()+":"+cane.z()+":83:0->0:0,cactus="+cactus.x()+":"+cactus.y()+":"+cactus.z()+":81:0->0:0,drops=packet21-296:1:0+338:1:0+81:1:0,hoe=290,bonemeal=351:15,farmland=60,health=20,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-wheat59+reed83+cactus81|cause=packet15-seeds295+bonemeal351:15+packet14|wire=packet53-air+packet21-296+338+81|oracle=crop-harvest-drops|"+evidence;System.out.println("WORLDLINE_M303_HARVEST="+evidence);System.out.println("WORLDLINE_M303_TRACE="+trace);System.out.println("WORLDLINE_M303_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static void harvest(B173WireClient a,BlockPosition target,int ticks){a.beginBreak(target);a.sustainTicks(ticks);a.finishBreak(target);}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static void till(B173WireClient a,BlockPosition dirt)throws Exception{a.useHeldItemOnBlock(dirt,BlockFace.UP);a.awaitBlock(dirt,new BlockState(60,0));}
 private static BlockPosition sow(B173WireClient a,BlockPosition soil)throws Exception{BlockPosition crop=BlockFace.UP.adjacent(soil);a.useHeldItemOnBlock(soil,BlockFace.UP);a.awaitBlock(crop,YOUNG);return crop;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&waterId(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic crop-harvest foundation");}
 private static boolean waterId(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
