package worldline.smoke.ghastfireballsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places a Ghast spawner on a Nether netherrack cavern platform and observes Packet24 56 plus Packet23 fireball. */
public final class GhastFireballSetSmoke{
 private GhastFireballSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: GhastFireballSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(180);
  require(user.length()<=16,"username exceeds 16");B173DedicatedServer server=B173DedicatedServer.netherMonsters(jar,workspace,port,seed,timeout);B173WireClient scout=new B173WireClient("127.0.0.1",port,user,timeout),actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition land,top,spawner;int pads,clients=2;int[] known=new int[]{1,10,11,12,50,60,61,62,70,71,90};
  try{server.boot();B173PlayerSeed.writeDimension(workspace,user,4.5D,64D,4.5D,-1);scout.connect();scout.synchronizePose();require(scout.dimension()==-1&&scout.awaitDimension(-1)==-1,"nether scout dimension drift");RemoteChunkSnapshot initial=scout.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(count(initial,87)>0&&sky(initial)==0,"nether terrain identity drift");land=landing(initial,cx,cz);scout.close();awaitPlayers(server,0);
   B173PlayerSeed.writeInventory(workspace,user,land.x()+0.5D,land.y()+1.0D,land.z()+0.5D,-1,new int[]{0,1},new int[]{87,52},new int[]{64,1},new int[]{0,0});actor.connect();require(actor.synchronizePose()!=null&&actor.dimension()==-1&&actor.awaitInventory().occupiedSlots()==2,"nether ghast inventory or dimension drift");
   top=cavern(load(actor,land));if(top.x()!=land.x()||top.y()!=land.y()||top.z()!=land.z()){actor.close();awaitPlayers(server,0);B173PlayerSeed.writeInventory(workspace,user,top.x()+0.5D,top.y()+1.0D,top.z()+0.5D,-1,new int[]{0,1},new int[]{87,52},new int[]{64,1},new int[]{0,0});actor=new B173WireClient("127.0.0.1",port,user,timeout);actor.connect();require(actor.synchronizePose()!=null&&actor.dimension()==-1&&actor.awaitInventory().occupiedSlots()==2,"nether cavern relog drift");clients++;}
   RemoteWorldView live=actor.awaitRemoteChunk(Math.floorDiv(top.x(),16),Math.floorDiv(top.z(),16));actor.selectHeldSlot(0);pads=pad(actor,live,top);live=actor.sustainTicks(1);actor.look(0F,60F);actor.selectHeldSlot(1);spawner=place(actor,site(live,top),BlockFace.UP,52);actor.close();awaitPlayers(server,0);server.save();
  }finally{scout.close();actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.ghast(workspace,spawner);server=B173DedicatedServer.netherMonsters(jar,workspace,port,seed,timeout);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();require(actor.synchronizePose()!=null&&actor.dimension()==-1,"nether ghast reload dimension drift");actor.awaitRemoteChunk(Math.floorDiv(top.x(),16),Math.floorDiv(top.z(),16));actor.look(0F,0F);actor.moveAndObserve(0D,0D,0D,2);
   RemoteMobSpawn ghast=actor.awaitMobSpawn(56);require(ghast.legacyType()==56&&ghast.entityId()!=actor.state().entityId(),"ghast Packet24 identity drift");
   RemoteObjectSpawn ball=actor.awaitObjectSpawn(63);require(ball.type()==63&&ball.entityId()!=ghast.entityId()&&ball.entityId()!=actor.state().entityId()&&ball.throwerId()==ghast.entityId()&&!known(known,ball.type()),"fireball Packet23 identity drift type="+ball.type()+" thrower="+ball.throwerId());
   actor.close();awaitPlayers(server,0);server.save();
   String evidence="dimension=-1,support="+top.x()+":"+top.y()+":"+top.z()+":87,pads="+pads+",spawner="+spawner.x()+":"+spawner.y()+":"+spawner.z()+":52:0,entityid=Ghast,ghast=type56,fireball=type"+ball.type()+",thrower=ghast,packet23-known=absent,clients="+clients+",disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|profile=allow-nether-true+spawn-monsters-true|entry=prelogin-player-nbt-dimension-minus-one+item87+item52|fixture=nether-netherrack87-platform+spawner52-ghast|cause=nbt-entityid-ghast+ghast-los|wire=packet24-type56+packet23-type"+ball.type()+"-thrower-ghast|oracle=nether-ghast-and-fireball-object|"+evidence;System.out.println("WORLDLINE_M410_GHAST="+evidence);System.out.println("WORLDLINE_M410_TRACE="+trace);System.out.println("WORLDLINE_M410_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition site(RemoteWorldView v,BlockPosition t){BlockFace[] faces={BlockFace.EAST,BlockFace.NORTH,BlockFace.SOUTH,BlockFace.WEST};for(int i=0;i<faces.length;i++){BlockPosition s=faces[i].adjacent(t);int ccx=Math.floorDiv(s.x(),16),ccz=Math.floorDiv(s.z(),16);if(!v.containsChunk(ccx,ccz))continue;if(!air(v.blockAt(s.x(),s.y(),s.z()).legacyId())&&air(v.blockAt(s.x(),s.y()+1,s.z()).legacyId()))return s;}throw new IllegalStateException("no adjacent netherrack spawner support");}
 private static RemoteWorldView load(B173WireClient a,BlockPosition land){int lcx=Math.floorDiv(land.x(),16),lcz=Math.floorDiv(land.z(),16);RemoteWorldView v=a.awaitRemoteChunk(lcx,lcz);a.moveAndObserve(0D,0D,0D,20);return a.awaitRemoteChunk(lcx,lcz);}
 private static int pad(B173WireClient a,RemoteWorldView v,BlockPosition t)throws Exception{int n=0;n+=fill(a,v,t,BlockFace.NORTH);n+=fill(a,v,t,BlockFace.SOUTH);n+=fill(a,v,t,BlockFace.EAST);n+=fill(a,v,t,BlockFace.WEST);return n;}
 private static int fill(B173WireClient a,RemoteWorldView v,BlockPosition t,BlockFace f)throws Exception{BlockPosition p=f.adjacent(t);int ccx=Math.floorDiv(p.x(),16),ccz=Math.floorDiv(p.z(),16);if(!v.containsChunk(ccx,ccz)||!air(v.blockAt(p.x(),p.y(),p.z()).legacyId()))return 0;a.placeHeldBlock(t,f);a.awaitBlock(p,new BlockState(87,0));return 1;}
 private static BlockPosition landing(RemoteChunkSnapshot q,int cx,int cz){for(int x=1;x<=12;x++)for(int z=1;z<=12;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==87&&air(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic nether landing");}
 private static BlockPosition cavern(RemoteWorldView view){BlockPosition best=null;int bestRun=-1;for(RemoteChunkSnapshot q:view.chunks()){int ccx=q.observation().x()>>4,ccz=q.observation().z()>>4;for(int x=2;x<=13;x++)for(int z=2;z<=13;z++){int y=1;while(y<128){if(!air(q.blockAt(x,y,z).legacyId())){y++;continue;}int start=y;while(y<128&&air(q.blockAt(x,y,z).legacyId()))y++;int run=y-start,floor=start-1;if(floor>=1&&q.blockAt(x,floor,z).legacyId()==87&&run>bestRun){bestRun=run;best=new BlockPosition(ccx*16+x,floor,ccz*16+z);}}}}if(best==null||bestRun<6)throw new IllegalStateException("no deterministic nether ghast cavern run="+bestRun+" chunks="+view.loadedChunks());return best;}
 private static boolean air(int id){return id==0;}private static boolean known(int[] skip,int type){for(int v:skip)if(v==type)return true;return false;}private static int count(RemoteChunkSnapshot q,int id){int n=0;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=0;y<128;y++)if(q.blockAt(x,y,z).legacyId()==id)n++;return n;}private static int sky(RemoteChunkSnapshot q){int n=0;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=0;y<128;y++)if(q.skyLightAt(x,y,z)>0)n++;return n;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
