package worldline.smoke.remainingboatbreakb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places two boats on still water 9, correlates Packet23 type 1, then Packet7-attacks each until Packet21. */
public final class RemainingBoatBreakSmoke{
 private RemainingBoatBreakSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=8)throw new IllegalArgumentException("usage: RemainingBoatBreakSmoke server.jar workspace port seed actor observer chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String actorName=a[4],observerName=a[5];int cx=Integer.parseInt(a[6]),cz=Integer.parseInt(a[7]);
  require(seed==17320110707L&&actorName.equals("BoatBrk403")&&actorName.length()<=16&&observerName.equals("BoatSee403")&&observerName.length()<=16,"remaining-boat-break identity drift");
  Duration timeout=Duration.ofSeconds(90);B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,actorName,timeout),observer=new B173WireClient("127.0.0.1",port,observerName,timeout);
  try{server.boot();B173PlayerSeed.writeInventory(workspace,actorName,4.5D,60D,4.5D,new int[]{0,1},new int[]{333,333},new int[]{1,1},new int[]{0,0});B173PlayerSeed.write(workspace,observerName,4.5D,80D,4.5D);actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==2,"boat inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);BlockPosition water=waterCell(initial,cx,cz);int fluid=initial.blockAt(local(water.x(),cx),water.y(),local(water.z(),cz)).legacyId();require(fluid==9,"still-water 9 fixture drift");observer.connect();observer.synchronizePose();observer.awaitRemoteChunk(cx,cz);
   RemoteObjectSpawn first=place(actor,observer,0);RemoteDroppedItem drop1=B173BoatBreak.attackUntilDrop(actor,observer,first.entityId());require(drop1.item().legacyId()==333||drop1.item().legacyId()==5||drop1.item().legacyId()==280,"first boat Packet21 family drift");
   RemoteObjectSpawn second=place(actor,observer,1);require(second.entityId()!=first.entityId(),"second boat identity drift");RemoteDroppedItem drop2=B173BoatBreak.attackUntilDrop(actor,observer,second.entityId());require(drop2.entityId()!=drop1.entityId(),"second boat Packet21 identity drift");
   RemoteDroppedItem stick=actor.peekDroppedItem(B173BoatBreak.STICK),stickPeer=observer.peekDroppedItem(B173BoatBreak.STICK);require(stick!=null&&stickPeer!=null&&stick.item().legacyId()==280&&stick.item().equals(stickPeer.item()),"stick 280 wreckage absent");
   actor.sustainTicks(5);observer.sustainTicks(5);actor.close();observer.close();awaitPlayers(server,0);server.save();
   String drop="packet21-"+drop1.item().legacyId()+"+packet21-"+drop2.item().legacyId()+"+packet21-280";String evidence="water="+water.x()+":"+water.y()+":"+water.z()+":"+fluid+":0,boats=2,boat=type1+shared-id+packet23+packet7-button1,item=333,drop="+drop+",pose="+first.fixedX()+":"+first.fixedY()+":"+first.fixedZ()+",clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=natural-water"+fluid+"+boat333x2|cause=packet15-dir255-boat333+empty-hand-packet7-button1-attack|wire=packet23-type1+packet7-button1+packet21-5+packet21-280|oracle=two-peer-two-boat-breaks-not-spawn-only-not-craft-not-ride|"+evidence;System.out.println("WORLDLINE_M403_BREAK="+evidence);System.out.println("WORLDLINE_M403_TRACE="+trace);System.out.println("WORLDLINE_M403_SIGNATURE="+sha(trace));
  }finally{actor.close();observer.close();server.close();}
 }
 private static RemoteObjectSpawn place(B173WireClient actor,B173WireClient observer,int slot){actor.selectHeldSlot(slot);actor.look(0F,90F);actor.useSelectedItemInAir();RemoteObjectSpawn spawn=actor.awaitObjectSpawn(1),peer=observer.awaitObjectSpawn(1);require(spawn.equals(peer)&&spawn.type()==1&&spawn.entityId()!=actor.state().entityId()&&spawn.entityId()!=observer.state().entityId(),"peer boat spawn drift");require(Math.abs(spawn.x()-4.5D)<=6D&&Math.abs(spawn.z()-4.5D)<=6D,"boat packet pose escaped player water pose="+spawn.x()+":"+spawn.y()+":"+spawn.z());actor.sustainTicks(20);observer.sustainTicks(5);actor.selectHeldSlot(slot);actor.look(0F,0F);return spawn;}
 private static BlockPosition waterCell(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId())&&q.blockAt(x,60,z).legacyId()==9)return new BlockPosition(cx*16+x,60,cz*16+z);throw new IllegalStateException("no deterministic still-water 9 boat cell");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
