package worldline.smoke.jukeboxb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places official jukebox 84 and proves a gold disc insert through Packet54/61 or Packet103. */
public final class JukeboxSmoke{
 private JukeboxSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: JukeboxSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,box;int column;BlockState live;RemoteNoteEvent click;boolean discGone;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,84,2256},new int[]{32,1,1},new int[]{0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==3,"jukebox inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded jukebox fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);box=place(actor,top,BlockFace.UP,84);actor.selectHeldSlot(2);require(!actor.inventory().slot(38).empty()&&actor.inventory().slot(38).item().equals(new RemoteItemStack(2256,1,0)),"gold disc seed drift");
   actor.useHeldItemOnBlock(box,BlockFace.UP);live=null;click=null;for(int n=0;n<40;n++){live=actor.sustainTicks(1).blockAt(box.x(),box.y(),box.z());if(click==null)click=B173NoteAccess.poll(actor);if(actor.inventory().slot(38).empty()||click!=null)break;}
   discGone=actor.inventory().slot(38).empty();boolean played=click!=null&&(click.packetId()==54||click.packetId()==61)&&click.position().equals(box);require(live!=null&&live.legacyId()==84&&(played||discGone),"official jukebox insert absent: live="+live+",discGone="+discGone+",click="+click);actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(box.x(),cx),box.y(),local(box.z(),cz)).equals(live),"persisted jukebox drift");
   String play=played?"packet"+click.packetId()+":"+click.instrument()+":"+click.pitch():"none";String wire=played?"packet"+click.packetId()+"-instrument"+click.instrument()+"-pitch"+click.pitch():"packet103-slot38-empty";String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,jukebox="+box.x()+":"+box.y()+":"+box.z()+":84:"+live.metadata()+",disc="+(discGone?"2256->empty":"2256->held")+",play="+play+",persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+jukebox84|cause=packet15-item84-place+packet15-disc2256|wire="+wire+"|oracle=official-disc-insert+fresh-login-block84|"+evidence;System.out.println("WORLDLINE_M178_JUKEBOX="+evidence);System.out.println("WORLDLINE_M178_TRACE="+trace);System.out.println("WORLDLINE_M178_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic jukebox foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
