package worldline.smoke.remainingarrowlifesetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Seeds bow 261 plus arrows 262, lands Packet23 type 60, then Packet21/22-collects arrow 262. */
public final class RemainingArrowLifeSetSmoke{
 private static final RemoteItemStack ARROW=new RemoteItemStack(262,1,0);
 private RemainingArrowLifeSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: RemainingArrowLifeSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("ArrowLife436")&&user.length()<=16,"remaining-arrow-life-set identity drift");
  Duration timeout=Duration.ofSeconds(90);B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top;int column;RemoteObjectSpawn arrow;RemoteDroppedItem drop;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3},new int[]{1,261,262,262},new int[]{32,1,1,1},new int[]{0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==4&&has(actor,37,261,1)&&has(actor,38,262,1)&&has(actor,39,262,1),"remaining-arrow-life-set inventory seed drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded remaining-arrow-life-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   BlockPosition west=place(actor,top,BlockFace.WEST,1),east=place(actor,top,BlockFace.EAST,1);place(actor,west,BlockFace.NORTH,1);place(actor,west,BlockFace.SOUTH,1);place(actor,east,BlockFace.NORTH,1);place(actor,east,BlockFace.SOUTH,1);place(actor,top,BlockFace.SOUTH,1);place(actor,top,BlockFace.NORTH,1);
   actor.selectHeldSlot(1);actor.look(0F,0F);actor.useSelectedItemInAir();arrow=actor.awaitObjectSpawn(60);require(arrow.type()==60&&arrow.throwerId()==actor.state().entityId(),"arrow object spawn drift");actor.selectHeldSlot(3);require(has(actor,39,262,1),"arrow 262 collect stack absent");actor.look(0F,90F);actor.dropHeldItem();drop=actor.awaitDroppedItem(ARROW);require(drop.item().equals(ARROW)&&drop.item().legacyId()==262,"arrow Packet21 262 absent");waitEmpty(actor,39);waitCollect(actor);require(has(actor,37,261,1)&&(has(actor,38,262,1)||has(actor,39,262,1)),"bow 261 plus collected arrow 262 drift");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,bow=261,arrow=262,wire=packet23-type60+packet21-262,thrower=actor,pickup=262,collect=true,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+bow261+arrow262|cause=packet15-air-bow261+packet14-drop-262|wire=packet23-type60+packet21-262+packet103-collect-262|oracle=remaining-arrow-life-land-then-pickup|"+evidence;System.out.println("WORLDLINE_M436_SET="+evidence);System.out.println("WORLDLINE_M436_TRACE="+trace);System.out.println("WORLDLINE_M436_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static void waitEmpty(B173WireClient a,int slot)throws Exception{for(int n=0;n<16;n++){if(a.inventory().slot(slot).empty())return;a.sustainTicks(2);}throw new IllegalStateException("held arrow 262 did not empty after Packet14 drop");}
 private static void waitCollect(B173WireClient a)throws Exception{for(int n=0;n<16;n++){a.sustainTicks(5);if(has(a,38,262,1)||has(a,39,262,1))return;}throw new IllegalStateException("arrow 262 collect restore absent");}
 private static boolean has(B173WireClient a,int slot,int id,int count){return !a.inventory().slot(slot).empty()&&a.inventory().slot(slot).item().equals(new RemoteItemStack(id,count,0));}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic remaining-arrow-life-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
