package worldline.smoke.sheepdyesetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Dyes two living type-91 sheep with dyes 351:1 and 351:11, then shears Packet21 wool 35:14 plus 35:4. */
public final class SheepDyeSetSmoke{
 private SheepDyeSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SheepDyeSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("SheepDye406")&&user.length()<=16,"sheep-dye-set identity drift");
  Duration timeout=Duration.ofSeconds(180);B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,red,yellow;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5},new int[]{1,2,52,351,351,359},new int[]{32,48,2,8,8,1},new int[]{0,0,0,1,11,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==6,"sheep-dye-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded sheep-dye-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);red=place(actor,top,BlockFace.UP,52);yellow=place(actor,red,BlockFace.EAST,52);actor.sustainTicks(5);actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.twoSheep(workspace,red);server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()>=3,"sheep-dye-set reload inventory drift");RemoteMobSpawn first=actor.awaitMobSpawn(91),second=actor.awaitMobSpawn(91);require(first.legacyType()==91&&second.legacyType()==91&&first.entityId()!=second.entityId()&&first.entityId()!=actor.state().entityId()&&second.entityId()!=actor.state().entityId(),"sheep Packet24 identity drift");dye(actor,first,1);dye(actor,second,11);RemoteDroppedItem redWool=shear(actor,first,14),yellowWool=shear(actor,second,4);require(redWool.item().legacyId()==35&&redWool.item().damage()==14&&yellowWool.item().legacyId()==35&&yellowWool.item().damage()==4,"dyed-sheep Packet21 wool damages absent");require(B173ShearsAccess.peekDeath(actor,first.entityId())==null&&B173ShearsAccess.peekDeath(actor,second.entityId())==null,"Packet38 status 3 death after dye shears");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass,red="+red.x()+":"+red.y()+":"+red.z()+":52:0,yellow="+yellow.x()+":"+yellow.y()+":"+yellow.z()+":52:0,mobs=type91+type91,dyes=351:1+351:11,shears=359,drops=packet21-35:14+packet21-35:4,death=no-packet38-status3,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+two-sheep-spawner52|cause=packet7-dye351:1+packet7-dye351:11+packet7-interact-shears359|wire=packet24-type91+packet21-35:14+packet21-35:4+no-packet38-status3|oracle=dyed-sheep-wool-set|"+evidence;System.out.println("WORLDLINE_M406_SET="+evidence);System.out.println("WORLDLINE_M406_TRACE="+trace);System.out.println("WORLDLINE_M406_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static void dye(B173WireClient a,RemoteMobSpawn spawn,int damage)throws Exception{int slot=find(a.inventory(),351,damage);require(slot>=36,"dye 351:"+damage+" absent from hotbar");a.selectHeldSlot(slot-36);approach(a,spawn);slot=find(a.inventory(),351,damage);require(slot>=36,"dye 351:"+damage+" lost before use");a.selectHeldSlot(slot-36);B173ShearsAccess.dyeMob(a,spawn.entityId());a.sustainTicks(10);}
 private static RemoteDroppedItem shear(B173WireClient a,RemoteMobSpawn spawn,int wool)throws Exception{int slot=find(a.inventory(),359,-1);require(slot>=36,"shears absent from hotbar");a.selectHeldSlot(slot-36);approach(a,spawn);slot=find(a.inventory(),359,-1);require(slot>=36,"shears lost before use");a.selectHeldSlot(slot-36);B173ShearsAccess.useOnMob(a,spawn.entityId());a.sustainTicks(20);RemoteDroppedItem drop=a.peekDroppedItem(new RemoteItemStack(35,1,wool));require(drop!=null&&drop.item().legacyId()==35&&drop.item().damage()==wool,"shears Packet21 wool 35:"+wool+" absent");return drop;}
 private static int find(RemoteInventoryView view,int id,int damage){for(int slot=36;slot<=44;slot++)if(!view.slot(slot).empty()&&view.slot(slot).item().legacyId()==id&&(damage<0||view.slot(slot).item().damage()==damage))return slot;return -1;}
 private static void approach(B173WireClient a,RemoteMobSpawn spawn){for(int step=0;step<16;step++){PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=spawn.x()-here.x(),dy=spawn.y()+1.0D-here.y(),dz=spawn.z()-1.5D-here.z(),dist=Math.sqrt(dx*dx+dy*dy+dz*dz);if(dist<=2.5D)return;double s=Math.min(1D,9.0D/dist);a.moveAndObserve(dx*s,dy*s,dz*s,2);}}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic sheep-dye-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
