package worldline.smoke.crosschunkrecoveryb173;

import java.nio.ByteBuffer;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;
import worldline.api.*;import worldline.b173server.*;

/** Adds and removes one official edge source across two observed chunks. */
public final class CrossChunkLightRecoverySmoke{
 private CrossChunkLightRecoverySmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=11)throw new IllegalArgumentException("usage: CrossChunkLightRecoverySmoke server.jar workspace port seed actor observer sourceX neighborX chunkZ sourceId settle");Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]),sourceX=Integer.parseInt(a[6]),neighborX=Integer.parseInt(a[7]),chunkZ=Integer.parseInt(a[8]),sourceId=Integer.parseInt(a[9]),settle=Integer.parseInt(a[10]);long seed=Long.parseLong(a[3]);String user=a[4],observer=a[5];require(neighborX==sourceX+1,"M124 requires east seam");Duration timeout=Duration.ofSeconds(90);B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),witness=null,reader=null;RemoteChunkSnapshot left0,right0,left1,right1,left2,right2;BlockPosition support,target;int z;
  try{server.boot();B173PlayerSeed.writeHolding(workspace,user,sourceX*16+15.5D,120D,chunkZ*16+8.5D,sourceId,1,0);B173PlayerSeed.write(workspace,observer,sourceX*16+15.5D,120D,chunkZ*16+8.5D);actor.connect();PlayerPose pose=actor.synchronizePose();require(actor.awaitInventory().slot(36).item().equals(new RemoteItemStack(sourceId,1,0)),"source inventory drift");RemoteWorldView world=actor.awaitRemoteChunk(sourceX,chunkZ);actor.sustainTicks(20);world=actor.awaitRemoteChunk(neighborX,chunkZ);left0=world.chunkAt(sourceX,chunkZ);right0=world.chunkAt(neighborX,chunkZ);support=support(left0,right0,sourceX,chunkZ);target=BlockFace.UP.adjacent(support);z=target.z()-chunkZ*16;pose=actor.moveAndObserve(target.x()+0.5D-pose.x(),0D,target.z()+0.5D-pose.z(),3).resulting();while(pose.y()>target.y()+3D){MovementOutcome move=actor.moveAndObserve(0D,-1D,0D,1);pose=move.resulting();require(!move.corrected()||pose.y()<=target.y()+4D,"descent corrected above source");}actor.selectHeldSlot(0);actor.placeHeldBlock(support,BlockFace.UP);actor.awaitBlock(target,new BlockState(sourceId,0));actor.sustainTicks(settle);witness=new B173WireClient("127.0.0.1",port,observer,timeout);witness.connect();witness.synchronizePose();witness.sustainTicks(20);RemoteWorldView lit=witness.awaitRemoteChunk(sourceX,chunkZ);lit=witness.awaitRemoteChunk(neighborX,chunkZ);left1=lit.chunkAt(sourceX,chunkZ);right1=lit.chunkAt(neighborX,chunkZ);require(left1.blockLightAt(15,target.y(),z)==15&&right1.blockLightAt(0,target.y(),z)==12,"lit phase absent");witness.close();witness=null;actor.beginBreak(target);Thread.sleep(3000L);actor.finishBreak(target);actor.awaitBlock(target,new BlockState(0,0));actor.sustainTicks(settle);actor.close();awaitPlayers(server,0);server.save();reader=new B173WireClient("127.0.0.1",port,observer,timeout);reader.connect();reader.synchronizePose();reader.sustainTicks(20);RemoteWorldView recovered=reader.awaitRemoteChunk(sourceX,chunkZ);recovered=reader.awaitRemoteChunk(neighborX,chunkZ);left2=recovered.chunkAt(sourceX,chunkZ);right2=recovered.chunkAt(neighborX,chunkZ);}finally{actor.close();if(witness!=null)witness.close();if(reader!=null)reader.close();server.close();}
  Delta upLeft=delta(left0,left1),upRight=delta(right0,right1),downLeft=delta(left1,left2),downRight=delta(right1,right2),residualLeft=delta(left0,left2),residualRight=delta(right0,right2);int y=target.y();require(left2.blockLightAt(15,y,z)==0&&right2.blockLightAt(0,y,z)==0&&residualLeft.changed==0&&residualRight.changed==0,"cross-chunk light did not recover");BlockState finalSource=left2.blockAt(15,y,z);String evidence="source="+target.x()+":"+y+":"+target.z()+":89:0->"+finalSource.legacyId()+":"+finalSource.metadata()+",samples=15->0/12->0,upLeft="+upLeft+",upRight="+upRight+",downLeft="+downLeft+",downRight="+downRight+",residualLeft="+residualLeft+",residualRight="+residualRight;String trace="v1|server=official-b1.7.3|seed="+seed+"|seam=chunks-"+sourceX+":"+neighborX+","+chunkZ+"|precondition=m123-edge-glowstone-lit|intervention=packet14-remove-source|confirmation=packet53-air|settle="+settle+"ticks|observation=lit+recovered-fresh-packet51-both-chunks|"+evidence+"|disconnect=clean";System.out.println("WORLDLINE_M124_LIGHT="+evidence);System.out.println("WORLDLINE_M124_TRACE="+trace);System.out.println("WORLDLINE_M124_SIGNATURE="+sha(trace));
 }
 private static BlockPosition support(RemoteChunkSnapshot left,RemoteChunkSnapshot right,int cx,int cz){for(int z=2;z<=13;z++)for(int y=126;y>=1;y--)if(solid(left.blockAt(15,y,z).legacyId())&&replaceable(left.blockAt(15,y+1,z).legacyId())&&replaceable(right.blockAt(0,y+1,z).legacyId())&&left.blockLightAt(15,y+1,z)==0&&right.blockLightAt(0,y+1,z)==0)return new BlockPosition(cx*16+15,y,cz*16+z);throw new IllegalStateException("no seam source support");}
 private static Delta delta(RemoteChunkSnapshot before,RemoteChunkSnapshot after)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");ByteBuffer row=ByteBuffer.allocate(8);int changed=0,increased=0,decreased=0,max=0;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=0;y<128;y++){int a=before.blockLightAt(x,y,z),b=after.blockLightAt(x,y,z);if(a!=b){changed++;if(b>a)increased++;else decreased++;max=Math.max(max,Math.abs(b-a));row.clear();row.putShort((short)x).putShort((short)y).putShort((short)z).put((byte)a).put((byte)b);d.update(row.array());}}return new Delta(changed,increased,decreased,max,hex(d.digest()));}
 private static boolean solid(int id){return id!=0&&id!=8&&id!=9&&id!=10&&id!=11&&id!=31&&id!=37&&id!=38&&id!=39&&id!=40&&id!=78;}private static boolean replaceable(int id){return id==0||id==8||id==9||id==10||id==11||id==78;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long end=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<end){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{return hex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte v:b)s.append(String.format("%02x",v&255));return s.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static final class Delta{final int changed,increased,decreased,max;final String hash;Delta(int c,int i,int d,int m,String h){changed=c;increased=i;decreased=d;max=m;hash=h;}public String toString(){return changed+":"+increased+":"+decreased+":"+max+":"+hash;}}
}
