package worldline.smoke.cactusadjacentbreaksetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places official cactus on raised sand, then a horizontally adjacent solid so the cactus pops to item 81. */
public final class CactusAdjacentBreakSetSmoke{
 private CactusAdjacentBreakSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: CactusAdjacentBreakSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  require(seed==17320110707L&&user.equals("CactBreak578")&&user.length()<=16,"cactus-adjacent-break identity drift");
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,sand,cactus,neighbor;int column;RemoteDroppedItem drop;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,12,81},new int[]{32,1,1},new int[]{0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==3,"cactus-adjacent-break inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded cactus-adjacent-break fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);sand=place(actor,top,BlockFace.UP,12);actor.selectHeldSlot(2);cactus=place(actor,sand,BlockFace.UP,81);require(worldline.test.WorldlineSmokeAwait.observe(actor,5).blockAt(cactus.x(),cactus.y(),cactus.z()).legacyId()==81,"isolated cactus popped");
   neighbor=BlockFace.EAST.adjacent(cactus);actor.look(-90F,0F);actor.selectHeldSlot(0);actor.placeHeldBlock(cactus,BlockFace.EAST);actor.awaitBlock(neighbor,new BlockState(1,0));worldline.test.WorldlineSmokeAwait.awaitBlock(actor,cactus,new BlockState(0,0),20);drop=actor.awaitDroppedItem(new RemoteItemStack(81,1,0));require(drop.item().equals(new RemoteItemStack(81,1,0))&&drop.item().legacyId()==81&&drop.item().count()==1,"Packet21 cactus 81 drop absent");
   actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(sand.x(),cx),sand.y(),local(sand.z(),cz)).equals(new BlockState(12,0))&&after.blockAt(local(cactus.x(),cx),cactus.y(),local(cactus.z(),cz)).equals(new BlockState(0,0))&&after.blockAt(local(neighbor.x(),cx),neighbor.y(),local(neighbor.z(),cz)).equals(new BlockState(1,0)),"persisted cactus-adjacent-break drift");
   String evidence="column="+column+",sand="+sand.x()+":"+sand.y()+":"+sand.z()+":12:0,cactus="+cactus.x()+":"+cactus.y()+":"+cactus.z()+":81:0->0:0,neighbor="+neighbor.x()+":"+neighbor.y()+":"+neighbor.z()+":1:0,drops=packet21-81,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-sand12+cactus81|cause=packet15-item1-east-adjacent-solid|wire=packet53-cactus81->0+packet21-81|oracle=adjacent-solid-pop+fresh-login-air|"+evidence;System.out.println("WORLDLINE_M578_SET="+evidence);System.out.println("WORLDLINE_M578_TRACE="+trace);System.out.println("WORLDLINE_M578_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic cactus-adjacent-break foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
