package worldline.smoke.redstoneinputsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Official lever 69 latch ON/OFF plus stone button 77 pulse in one cycle. */
public final class RedstoneInputSetSmoke{
 private RedstoneInputSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: RedstoneInputSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,69,77},new int[]{32,1,1},new int[]{0,0,0});actor.connect();actor.synchronizePose();actor.look(-90F,0F);require(actor.awaitInventory().occupiedSlots()==3,"input-set inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);BlockPosition top=foundation(initial,cx,cz);int column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded input-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   BlockPosition pad=place(actor,top,BlockFace.SOUTH,1);BlockPosition lever=BlockFace.EAST.adjacent(top),button=BlockFace.EAST.adjacent(pad);
   require(initial.blockAt(local(lever.x(),cx),lever.y(),local(lever.z(),cz)).legacyId()==0&&initial.blockAt(local(button.x(),cx),button.y(),local(button.z(),cz)).legacyId()==0,"lever or button target was not initial air");
   actor.selectHeldSlot(1);actor.placeHeldBlock(top,BlockFace.EAST);BlockState leverOff=actor.awaitBlock(lever,new BlockState(69,1)).blockAt(lever.x(),lever.y(),lever.z());require(leverOff.equals(new BlockState(69,1))&&(leverOff.metadata()&8)==0,"official lever facing drift: "+leverOff);
   actor.selectHeldSlot(2);actor.placeHeldBlock(pad,BlockFace.EAST);BlockState buttonOff=actor.awaitBlock(button,new BlockState(77,1)).blockAt(button.x(),button.y(),button.z());require(buttonOff.equals(new BlockState(77,1))&&(buttonOff.metadata()&8)==0,"official button facing drift: "+buttonOff);
   actor.selectHeldSlot(3);RemoteWorldView settled=worldline.test.WorldlineSmokeAwait.observe(actor,200);require(settled.blockAt(lever.x(),lever.y(),lever.z()).equals(leverOff)&&settled.blockAt(button.x(),button.y(),button.z()).equals(buttonOff),"settled input-set drifted");
   actor.activateBlock(lever,BlockFace.UP);BlockState leverOn=actor.awaitBlock(lever,new BlockState(69,9)).blockAt(lever.x(),lever.y(),lever.z());require(leverOn.equals(new BlockState(69,9))&&(leverOn.metadata()&8)!=0,"lever powered 69:9 absent: "+leverOff+" -> "+leverOn);
   actor.activateBlock(lever,BlockFace.UP);BlockState leverLatched=actor.awaitBlock(lever,new BlockState(69,1)).blockAt(lever.x(),lever.y(),lever.z());require(leverLatched.equals(leverOff),"lever unpowered 69:1 absent: "+leverOn+" -> "+leverLatched);
   actor.activateBlock(button,BlockFace.UP);BlockState buttonOn=actor.awaitBlock(button,new BlockState(77,9)).blockAt(button.x(),button.y(),button.z());require(buttonOn.equals(new BlockState(77,9))&&(buttonOn.metadata()&8)!=0&&(buttonOn.metadata()&7)==(buttonOff.metadata()&7),"stone button power bit absent: "+buttonOff+" -> "+buttonOn);
   require((worldline.test.WorldlineSmokeAwait.observe(actor,1).blockAt(button.x(),button.y(),button.z()).metadata()&8)!=0,"stone button depowered immediately");BlockState released=worldline.test.WorldlineSmokeAwait.observe(actor,20).blockAt(button.x(),button.y(),button.z());require(released.equals(buttonOff)&&released.equals(new BlockState(77,1)),"stone button did not return to 77:1 after 20 ticks: "+released);
   actor.close();awaitPlayers(server,0);server.save();reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);
   require(after.blockAt(local(top.x(),cx),top.y(),local(top.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(pad.x(),cx),pad.y(),local(pad.z(),cz)).equals(new BlockState(1,0)),"persisted support drift");
   require(after.blockAt(local(lever.x(),cx),lever.y(),local(lever.z(),cz)).equals(leverOff)&&after.blockAt(local(button.x(),cx),button.y(),local(button.z(),cz)).equals(buttonOff),"persisted unpowered input-set drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,pad="+pad.x()+":"+pad.y()+":"+pad.z()+":1:0,lever="+lever.x()+":"+lever.y()+":"+lever.z()+":69:1->9->1,button="+button.x()+":"+button.y()+":"+button.z()+":77:1->9->1,settle=200ticks,delay=20ticks,persisted=69:1+77:1,clients=2,disconnect=clean";
   String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+lever69-east+button77-east|cause=empty-hand-packet15-lever-on-off+empty-hand-packet15-button-press|wire=packet53-lever69:1->9->1+packet53-button77:1->9->1|oracle=lever-latch-on-off+button-pulse+fresh-login-unpowered|"+evidence;
   System.out.println("WORLDLINE_M340_SET="+evidence);System.out.println("WORLDLINE_M340_TRACE="+trace);System.out.println("WORLDLINE_M340_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic input-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
