package worldline.smoke.tamedwolfassistsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Tames Packet24 wolf type 95 with bone 352, then one Packet7 sword 276 on sheep 91 for tamed assist. */
public final class TamedWolfAssistSetSmoke{
 private TamedWolfAssistSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: TamedWolfAssistSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("WolfHelp468")&&user.length()<=16,"tamed-wolf-assist-set identity drift");
  Duration timeout=Duration.ofSeconds(180);B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,wolf,sheep;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4},new int[]{1,2,52,352,276},new int[]{32,48,2,64,1},new int[]{0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==5,"tamed-wolf-assist-set inventory drift");worldline.test.WorldlineSmokeAwait.observe(actor,5);RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded tamed-wolf-assist-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);wolf=place(actor,top,BlockFace.UP,52);sheep=place(actor,wolf,BlockFace.EAST,52);worldline.test.WorldlineSmokeAwait.observe(actor,5);actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  Thread.sleep(1000L);B173WolfAssistAccess.retarget(workspace,sheep,wolf);server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()>=3,"tamed-wolf-assist-set reload inventory drift");worldline.test.WorldlineSmokeAwait.observe(actor,5);RemoteMobSpawn tame=actor.awaitMobSpawn(95);require(tame.legacyType()==95&&tame.entityId()!=actor.state().entityId(),"wolf Packet24 type 95 identity drift");int status=B173WolfAssistAccess.tame(actor,tame);require(status==7,"wolf Packet38 status 7 tame drift");require(B173ShearsAccess.peekDeath(actor,tame.entityId())==null,"Packet38 status 3 after bone tame");B173WolfAssistAccess.discardPending(actor,91);RemoteMobSpawn target=actor.awaitMobSpawn(91);require(target.legacyType()==91&&target.entityId()!=tame.entityId()&&target.entityId()!=actor.state().entityId(),"sheep Packet24 type 91 identity drift");require(B173ShearsAccess.peekDeath(actor,target.entityId())==null,"Packet38 status 3 before assist strike");B173WolfAssistAccess.unsit(actor,tame.entityId());worldline.test.WorldlineSmokeAwait.observe(actor,20);RemoteMobDeath death=B173WolfAssistAccess.strikeOnceAndAssist(actor,target);require(death.entityId()==target.entityId()&&death.deathStatus()==3&&death.hurtObserved()&&death.destroyPacket()==29,"tamed wolf assist death drift");require(B173ShearsAccess.peekDeath(actor,tame.entityId())==null,"tamed wolf died during assist");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass,wolf="+cell(wolf)+",sheep="+cell(sheep)+",mobs=type95+type91,bone=352,tame=packet38-status7,unsit=packet7-button0,sword=276,player-hits=1,hurt=packet38-status2,assist=packet38-status3-not-player-only,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+wolf-spawner52+sheep-spawner52|cause=packet7-button0-bone352+packet7-button0-unsit+one-packet7-button1-sword276|wire=packet24-type95+packet24-type91+packet38-status7+packet38-status2+packet38-status3-not-player-only|oracle=tamed-wolf-type95-assist-sheep91-not-m420-collar-dye-not-m449-pack-anger|"+evidence;System.out.println("WORLDLINE_M468_SET="+evidence);System.out.println("WORLDLINE_M468_TRACE="+trace);System.out.println("WORLDLINE_M468_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic tamed-wolf-assist-set foundation");}
 private static String cell(BlockPosition p){return p.x()+":"+p.y()+":"+p.z()+":52:0";}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
