schema=2
slo.hot.millis=4000
slo.cold.millis=240000
sample.count=2
sample.1.date=2026-08-24
sample.1.mode=cold
sample.1.millis=132624
sample.2.date=2026-08-24
sample.2.mode=hot
sample.2.millis=2176
stage.count=6
stage.1.name=smoke-discovery
stage.1.baseline.millis=807
stage.2.name=release
stage.2.baseline.millis=10
stage.3.name=release-artifacts
stage.3.baseline.millis=75
stage.4.name=modules
stage.4.baseline.millis=900
stage.5.name=tests
stage.5.baseline.millis=400
stage.6.name=csm-suite
stage.6.baseline.millis=40
