package worldline.smoke.itemdespawnsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Drops cobble Packet21, advances Age through NBT, then official Packet29 without Packet22. */
public final class ItemDespawnSetSmoke{
 private static final RemoteItemStack COBBLE=new RemoteItemStack(4,1,0);private static final int AGE=5900;
 private ItemDespawnSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: ItemDespawnSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("ItemDesp568")&&user.length()<=16,"item-despawn-set identity drift");
  Duration timeout=Duration.ofSeconds(420);B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top=null;int column=0;RemoteDroppedItem live;int ix=Integer.MIN_VALUE,iz=Integer.MIN_VALUE;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1},new int[]{1,4},new int[]{32,1},new int[]{0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==2&&has(actor,36,1,32)&&has(actor,37,4,1),"item-despawn-set inventory seed drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);actor.look(0F,90F);actor.moveAndObserve(0D,-4D,0D,2);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded item-despawn-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   BlockPosition west=place(actor,top,BlockFace.WEST,1),east=place(actor,top,BlockFace.EAST,1);place(actor,west,BlockFace.NORTH,1);place(actor,west,BlockFace.SOUTH,1);place(actor,east,BlockFace.NORTH,1);place(actor,east,BlockFace.SOUTH,1);place(actor,top,BlockFace.SOUTH,1);place(actor,top,BlockFace.NORTH,1);BlockPosition walk=east;for(int step=0;step<4;step++)walk=place(actor,walk,BlockFace.EAST,1);
   actor.selectHeldSlot(1);actor.look(0F,90F);actor.dropHeldItem();RemoteDroppedItem drop=actor.awaitDroppedItem(COBBLE);require(drop.item().equals(COBBLE)&&drop.item().legacyId()==4,"cobble Packet21 absent");waitEmpty(actor,37);require(!B173ItemDespawn.held(actor),"cobble remained in inventory after drop");actor.moveAndObserve(4D,0D,0D,4);require(actor.inventory().occupiedSlots()>=1&&!B173ItemDespawn.held(actor),"dropped cobble was collected before save");ix=(int)Math.floor(drop.x());iz=(int)Math.floor(drop.z());actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  require(ix!=Integer.MIN_VALUE&&iz!=Integer.MIN_VALUE,"dropped-item chunk position absent");B173ItemDespawn.age(workspace,ix,iz,AGE);server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()>=1&&!B173ItemDespawn.held(actor),"item-despawn-set reload inventory drift");live=actor.awaitDroppedItem(COBBLE);require(live.item().equals(COBBLE)&&live.entityId()>0,"reloaded cobble Packet21 absent");B173ItemDespawn.await(actor,live);require(B173ItemDespawn.finished(actor,live)&&!B173ItemDespawn.held(actor),"Packet29 despawn without collector drifted");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,item=4,age="+AGE+",age-limit=6000,wire=packet21-4+packet29,collect=false,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone-pad+east-walk+item4|cause=packet14-drop-4+nbt-age-5900|wire=packet21-4+packet29-no-packet22|oracle=item-despawn-age-6000-not-m52-collect-not-m51-spawn-only-not-m436-arrow|"+evidence;System.out.println("WORLDLINE_M568_SET="+evidence);System.out.println("WORLDLINE_M568_TRACE="+trace);System.out.println("WORLDLINE_M568_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static void waitEmpty(B173WireClient a,int slot)throws Exception{for(int n=0;n<16;n++){if(a.inventory().slot(slot).empty())return;a.sustainTicks(2);}throw new IllegalStateException("held cobble did not empty after Packet14 drop");}
 private static boolean has(B173WireClient a,int slot,int id,int count){return !a.inventory().slot(slot).empty()&&a.inventory().slot(slot).item().equals(new RemoteItemStack(id,count,0));}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic item-despawn-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
