package worldline.smoke.foodcraftsb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Crafts sugar in 2x2 then stew 282, bread 297, cookies 357, and cake 354 on a workbench. */
public final class FoodCraftsSmoke{
 private FoodCraftsSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: FoodCraftsSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  require(user.length()<=16&&B173FoodSugarClick.SUGAR.legacyId()==353&&B173FoodWorkbenchClick.STEW.legacyId()==282&&B173FoodWorkbenchClick.BREAD.legacyId()==297&&B173FoodWorkbenchClick.COOKIE.legacyId()==357&&B173FoodWorkbenchClick.CAKE.legacyId()==354,"food craft identities drifted");
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,bench;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5,6,7,8,9,10,11},new int[]{1,58,296,351,338,344,39,40,281,335,335,335},new int[]{32,1,8,1,2,1,1,1,1,1,1,1},new int[]{0,0,0,3,0,0,0,0,0,0,0,0});actor.connect();actor.synchronizePose();RemoteInventoryView inv=actor.awaitInventory();require(inv.occupiedSlots()==12&&inv.slot(36).item().equals(new RemoteItemStack(1,32,0))&&inv.slot(38).item().equals(new RemoteItemStack(296,8,0))&&inv.slot(39).item().equals(new RemoteItemStack(351,1,3))&&inv.slot(40).item().equals(B173FoodSugarClick.CANE2)&&inv.slot(42).item().equals(new RemoteItemStack(39,1,0)),"food inventory seed drift");
   RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded food-craft fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   B173FoodSugarClick.apply(actor);require(actor.inventory().slot(12).item().equals(B173FoodSugarClick.SUGAR)&&actor.inventory().slot(13).item().equals(B173FoodSugarClick.SUGAR)&&B173FoodSugarClick.emptyCraft(actor.inventory()),"live sugar 353 2x2 drifted");
   actor.selectHeldSlot(1);bench=BlockFace.UP.adjacent(top);actor.placeHeldBlock(top,BlockFace.UP);actor.awaitBlock(bench,new BlockState(58,0));actor.sustainTicks(5);actor.selectHeldSlot(1);actor.openWorkbench(bench,BlockFace.UP);B173FoodWorkbenchClick.apply(actor);requireFoods(actor.inventory());actor.closeWindow();actor.close();awaitPlayers(server,0);server.save();require(server.player(user).inventoryItems()==8,"food craft persistence count drift");
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();requireFoods(reader.awaitInventory());RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(top.x(),cx),top.y(),local(top.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(bench.x(),cx),bench.y(),local(bench.z(),cz)).equals(new BlockState(58,0)),"persisted workbench 58:0 drift");
   String evidence="stew=282,bread=297,cookie=357x8,cake=354,buckets=325x3,column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,workbench="+bench.x()+":"+bench.y()+":"+bench.z()+":58:0,grid=2x2+3x3,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=personal-2x2-reed338-sugar353+workbench58-stew282-bread297-cookie357-cake354|cause=packet102-window0-cane-to-sugar+packet102-workbench-matrix+result-take|wire=packet106-accepted+packet200-craft-stat|oracle=food-family-282-297-357-354+fresh-login|"+evidence;System.out.println("WORLDLINE_M327_CRAFTS="+evidence);System.out.println("WORLDLINE_M327_TRACE="+trace);System.out.println("WORLDLINE_M327_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static void requireFoods(RemoteInventoryView view){require(view.slot(42).item().equals(B173FoodWorkbenchClick.STEW)&&view.slot(43).item().equals(B173FoodWorkbenchClick.BREAD)&&view.slot(44).item().equals(B173FoodWorkbenchClick.COOKIE)&&view.slot(40).item().equals(B173FoodWorkbenchClick.CAKE)&&view.slot(9).item().equals(B173FoodWorkbenchClick.BUCKET)&&view.slot(10).item().equals(B173FoodWorkbenchClick.BUCKET)&&view.slot(11).item().equals(B173FoodWorkbenchClick.BUCKET)&&view.occupiedSlots()==8,"food crafted inventory drift");}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic food-craft foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
