package worldline.smoke.hostiledropssetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Kills spawned zombie type 54 and skeleton type 51 and collects Packet21 feather 288 plus arrow 262. */
public final class HostileDropsSetSmoke{
 private static final RemoteItemStack FEATHER=new RemoteItemStack(288,1,0),ARROW=new RemoteItemStack(262,1,0);
 private HostileDropsSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: HostileDropsSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(180);
  B173DedicatedServer server=B173DedicatedServer.monsters(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,first,second;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4,5,6,7,8,9,10},new int[]{1,2,52,52,276,320,322,298,299,300,301},new int[]{32,48,1,1,1,8,4,1,1,1,1},new int[]{0,0,0,0,0,0,0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==11,"hostile-drops inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded hostile-drops fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);first=place(actor,top,BlockFace.UP,52);actor.selectHeldSlot(3);second=place(actor,first,BlockFace.EAST,52);actor.sustainTicks(5);actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.entity(workspace,first,"Zombie");B173SpawnerSeed.entity(workspace,second,"Skeleton");server=B173DedicatedServer.monsters(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==11,"hostile-drops reload inventory drift");armor(actor);RemoteDroppedItem feather=null,arrow=null;int kills=0;
   go(actor,second);server.setTime(14000L);
   while(arrow==null){require(++kills<=8,"official skeleton arrow drop absent after bounded kills");RemoteMobSpawn skeleton=near(actor,51,second);require(skeleton.legacyType()==51&&skeleton.entityId()!=actor.state().entityId()&&skeleton.legacyType()!=90,"skeleton Packet24 identity drift");kill(actor,skeleton);heal(actor);actor.sustainTicks(20);arrow=actor.peekDroppedItem(ARROW);}
   heal(actor);go(actor,first);heal(actor);kills=0;
   while(feather==null){require(++kills<=8,"official zombie feather drop absent after bounded kills");RemoteMobSpawn zombie=near(actor,54,first);require(zombie.legacyType()==54&&zombie.entityId()!=actor.state().entityId()&&zombie.legacyType()!=90,"zombie Packet24 identity drift");kill(actor,zombie);actor.sustainTicks(20);feather=actor.peekDroppedItem(FEATHER);}
   require(feather.item().legacyId()==288&&arrow.item().legacyId()==262,"hostile Packet21 drop id drift");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass,spawners="+cell(first)+"+"+cell(second)+",entityid=Zombie+Skeleton,mobs=type54+type51,night=14000,sword=276,survival=leather298-301,drops=packet21-288+packet21-262,kills<=8,clients=1,disconnect=clean";String trace="v2|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+two-spawner52+leather-armor298-301|cause=nbt-entityid-zombie+skeleton+time-14000+personal-window-equip+diamond-sword-packet7|wire=packet24-type54+packet24-type51+packet106-armor-equip+packet38-status3+packet29+packet21-288+packet21-262|oracle=hostile-zombie-feather-and-skeleton-arrow-drops|"+evidence;System.out.println("WORLDLINE_M388_DROPS="+evidence);System.out.println("WORLDLINE_M388_TRACE="+trace);System.out.println("WORLDLINE_M388_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static RemoteMobSpawn near(B173WireClient a,int type,BlockPosition p){for(int n=0;n<32;n++){RemoteMobSpawn s=a.awaitMobSpawn(type);double dx=s.x()-(p.x()+0.5D),dz=s.z()-(p.z()+0.5D);if(dx*dx+dz*dz<=100D&&Math.abs(s.y()-p.y())<=6D)return s;}throw new IllegalStateException("nearby hostile type "+type+" absent");}
 private static void armor(B173WireClient a){a.equipLeatherArmor(43,RemoteArmorSlot.HELMET);a.equipLeatherArmor(44,RemoteArmorSlot.CHESTPLATE);a.equipLeatherArmor(9,RemoteArmorSlot.LEGGINGS);a.equipLeatherArmor(10,RemoteArmorSlot.BOOTS);}
 private static void go(B173WireClient a,BlockPosition p){approach(a,p.x()+0.5D,p.y()+1.0D,p.z()-1.5D,2.0D);}
 private static void kill(B173WireClient a,RemoteMobSpawn spawn){int entity=spawn.entityId();heal(a);approach(a,spawn.x(),spawn.y()+1.0D,spawn.z()-1.5D,2.5D);for(int hit=0;hit<4;hit++){if(B173ShearsAccess.peekDeath(a,entity)!=null)break;strike(a,entity);}for(int hit=0;hit<8&&B173ShearsAccess.peekDeath(a,entity)==null;hit++){RemoteMobMovement m=a.awaitMobMovement(entity);heal(a);approach(a,m.toX(),m.toY()+1.0D,m.toZ()-1.5D,2.5D);strike(a,entity);}RemoteMobDeath death=a.awaitMobDeath(entity);require(death.entityId()==entity&&death.hurtObserved(),"hostile death drift");}
 private static void approach(B173WireClient a,double x,double y,double z,double reach){for(int step=0;step<16;step++){heal(a);PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=x-here.x(),dy=y-here.y(),dz=z-here.z(),dist=Math.sqrt(dx*dx+dy*dy+dz*dz);if(dist<=reach)return;double s=Math.min(1D,9.0D/dist);a.moveAndObserve(dx*s,dy*s,dz*s,2);}}
 private static void strike(B173WireClient a,int entity){heal(a);int sword=find(a.inventory(),276);require(sword>=36,"diamond sword lost");a.selectHeldSlot(sword-36);a.attackMob(entity);a.sustainTicks(20);heal(a);}
 private static void heal(B173WireClient a){int h=a.health();if(h==0)throw new IllegalStateException("actor died during hostile drops");if(h>=20)return;int food=find(a.inventory(),322);if(food<36)food=find(a.inventory(),320);if(food<36)return;a.selectHeldSlot(food-36);a.useSelectedItemInAir();a.sustainTicks(5);}
 private static int find(RemoteInventoryView view,int id){for(int slot=36;slot<=44;slot++)if(!view.slot(slot).empty()&&view.slot(slot).item().legacyId()==id)return slot;return -1;}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic hostile-drops foundation");}
 private static String cell(BlockPosition p){return p.x()+":"+p.y()+":"+p.z()+":52:0";}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
