package worldline.smoke.irondoorplaceb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places official iron door item 330 as BlockDoor 71 halves and reloads them. */
public final class IronDoorPlaceSmoke{
 private IronDoorPlaceSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: IronDoorPlaceSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,lower,upper;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1},new int[]{1,330},new int[]{32,1},new int[]{0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==2,"iron door inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded iron door fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   lower=BlockFace.UP.adjacent(top);upper=BlockFace.UP.adjacent(lower);require(initial.blockAt(local(lower.x(),cx),lower.y(),local(lower.z(),cz)).legacyId()==0&&initial.blockAt(local(upper.x(),cx),upper.y(),local(upper.z(),cz)).legacyId()==0,"iron door cells were not initial air");
   actor.look(-90F,0F);actor.selectHeldSlot(1);actor.useHeldItemOnBlock(top,BlockFace.UP);awaitDoor(actor,lower,upper,0,8);actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(lower.x(),cx),lower.y(),local(lower.z(),cz)).equals(new BlockState(71,0))&&after.blockAt(local(upper.x(),cx),upper.y(),local(upper.z(),cz)).equals(new BlockState(71,8)),"persisted iron door drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,lower="+lower.x()+":"+lower.y()+":"+lower.z()+":71:0,upper="+upper.x()+":"+upper.y()+":"+upper.z()+":71:8,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+irondoor71|cause=packet15-item330-place|wire=packet53-door71:0/8|oracle=irondoor-place+fresh-login|"+evidence;System.out.println("WORLDLINE_M241_DOOR="+evidence);System.out.println("WORLDLINE_M241_TRACE="+trace);System.out.println("WORLDLINE_M241_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static void awaitDoor(B173WireClient a,BlockPosition lower,BlockPosition upper,int lowMeta,int highMeta)throws Exception{RemoteWorldView v=a.awaitBlock(lower,new BlockState(71,lowMeta));if(!v.blockAt(upper.x(),upper.y(),upper.z()).equals(new BlockState(71,highMeta)))v=a.awaitBlock(upper,new BlockState(71,highMeta));BlockState low=v.blockAt(lower.x(),lower.y(),lower.z()),high=v.blockAt(upper.x(),upper.y(),upper.z());require(low.equals(new BlockState(71,lowMeta))&&high.equals(new BlockState(71,highMeta)),"iron door cells "+low+" / "+high);}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic iron door foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
