package worldline.smoke.skeletonrangedaisetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places one Skeleton spawner and observes Packet24 type 51 plus two Packet23 type 60 arrows. */
public final class SkeletonRangedAiSetSmoke{
 private SkeletonRangedAiSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SkeletonRangedAiSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("SkelRange445")&&user.length()<=16,"skeleton-ranged identity drift");
  Duration timeout=Duration.ofSeconds(180);B173DedicatedServer server=B173DedicatedServer.monsters(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,spawner;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,2,52},new int[]{32,48,1},new int[]{0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==3,"skeleton-ranged inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded skeleton-ranged fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);spawner=place(actor,top,BlockFace.UP,52);actor.sustainTicks(5);actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.entity(workspace,spawner,"Skeleton");B173PlayerSeed.writeInventory(workspace,user,top.x()+0.5D,top.y()+1.0D,top.z()-2.5D,new int[]{0,1},new int[]{322,320},new int[]{4,8},new int[]{0,0});server=B173DedicatedServer.monsters(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==2,"skeleton-ranged reload inventory drift");server.setTime(14000L);RemoteMobSpawn skeleton=near(actor,spawner);require(skeleton.legacyType()==51&&skeleton.entityId()!=actor.state().entityId()&&skeleton.legacyType()!=90,"skeleton Packet24 identity drift");go(actor,skeleton,top);RemoteObjectSpawn first=B173HostileAccess.arrow(actor,skeleton.entityId()),second=B173HostileAccess.arrow(actor,skeleton.entityId());require(first.type()==60&&second.type()==60&&first.throwerId()==skeleton.entityId()&&second.throwerId()==skeleton.entityId()&&first.entityId()!=second.entityId()&&first.entityId()!=actor.state().entityId()&&second.entityId()!=actor.state().entityId(),"skeleton Packet23 arrow identity drift");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass,spawner="+cell(spawner)+",entityid=Skeleton,mob=type51,night=14000,arrows=2,arrow=type60,thrower=skeleton,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+spawner52|cause=nbt-entityid-skeleton+time-14000+skeleton-los|wire=packet24-type51+packet23-type60-thrower-skeleton+packet23-type60-thrower-skeleton|oracle=skeleton-ranged-ai-two-arrows|"+evidence;System.out.println("WORLDLINE_M445_SET="+evidence);System.out.println("WORLDLINE_M445_TRACE="+trace);System.out.println("WORLDLINE_M445_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static RemoteMobSpawn near(B173WireClient a,BlockPosition p){for(int n=0;n<32;n++){RemoteMobSpawn s=B173HostileAccess.skeleton(a);double dx=s.x()-(p.x()+0.5D),dz=s.z()-(p.z()+0.5D);if(dx*dx+dz*dz<=100D&&Math.abs(s.y()-p.y())<=6D)return s;}throw new IllegalStateException("nearby skeleton type 51 absent");}
 private static void go(B173WireClient a,RemoteMobSpawn s,BlockPosition t){double x=clamp(s.x(),t.x()-2.5D,t.x()+3.5D),z=clamp(s.z()-1.5D,t.z()-2.5D,t.z()+3.5D);step(a,x,t.y()+1.0D,z);}
 private static void step(B173WireClient a,double x,double y,double z){for(int n=0;n<16;n++){PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=x-here.x(),dy=y-here.y(),dz=z-here.z(),dist=Math.sqrt(dx*dx+dy*dy+dz*dz);if(dist<=2.5D)return;double cap=Math.min(1D,9.0D/dist);a.moveAndObserve(dx*cap,dy*cap,dz*cap,2);}}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic skeleton-ranged foundation");}
 private static String cell(BlockPosition p){return p.x()+":"+p.y()+":"+p.z()+":52:0";}private static double clamp(double v,double lo,double hi){return Math.max(lo,Math.min(hi,v));}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
