package worldline.smoke.spruceleavesb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places official spruce leaves 18:1 beside spruce log 17:1 and freezes persisted 18:9. */
public final class SpruceLeavesSmoke{
 private static final BlockState OAK_LEAVES=new BlockState(18,8),SPRUCE_LOG=new BlockState(17,1),SPRUCE_LEAVES=new BlockState(18,9);
 private SpruceLeavesSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: SpruceLeavesSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,log,leaf;int column;BlockState placed;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2},new int[]{1,17,18},new int[]{32,1,1},new int[]{0,1,1});actor.connect();actor.synchronizePose();RemoteInventoryView inventory=actor.awaitInventory();require(inventory.occupiedSlots()==3&&new RemoteItemStack(17,1,1).equals(inventory.slot(37).item())&&new RemoteItemStack(18,1,1).equals(inventory.slot(38).item()),"spruce leaves inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded spruce leaves fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);log=placeMeta(actor,top,BlockFace.EAST,SPRUCE_LOG);actor.selectHeldSlot(2);leaf=BlockFace.UP.adjacent(top);actor.placeHeldBlock(top,BlockFace.UP);placed=SPRUCE_LEAVES;actor.awaitBlock(leaf,placed);require(actor.sustainTicks(5).blockAt(leaf.x(),leaf.y(),leaf.z()).equals(placed)&&!placed.equals(OAK_LEAVES)&&placed.metadata()!=8,"live spruce leaves drift");actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);require(after.blockAt(local(top.x(),cx),top.y(),local(top.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(log.x(),cx),log.y(),local(log.z(),cz)).equals(SPRUCE_LOG)&&after.blockAt(local(leaf.x(),cx),leaf.y(),local(leaf.z(),cz)).equals(placed)&&!placed.equals(OAK_LEAVES),"persisted spruce leaves drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,log="+log.x()+":"+log.y()+":"+log.z()+":17:"+SPRUCE_LOG.metadata()+",leaves="+leaf.x()+":"+leaf.y()+":"+leaf.z()+":18:"+placed.metadata()+",persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+spruce17:1+leaves18:1|cause=packet15-item18:1|wire=packet53-leaves18:"+placed.metadata()+"|oracle=live-block18:9+fresh-login|"+evidence;System.out.println("WORLDLINE_M291_LEAVES="+evidence);System.out.println("WORLDLINE_M291_TRACE="+trace);System.out.println("WORLDLINE_M291_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{return placeMeta(a,support,face,new BlockState(id,0));}
 private static BlockPosition placeMeta(B173WireClient a,BlockPosition support,BlockFace face,BlockState state)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,state);return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic spruce leaves foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
