package worldline.smoke.remainingmobdropsrestb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Kills official pig 90 and sheep 91 and observes Packet21 pork 319 plus undyed wool 35:0. */
public final class RemainingMobDropsRestSmoke{
 private static final RemoteItemStack PORK=new RemoteItemStack(319,1,0),WOOL=new RemoteItemStack(35,1,0);
 private RemainingMobDropsRestSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: RemainingMobDropsRestSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("DropRest444")&&user.length()<=16,"remaining-mob-drops-rest identity drift");
  Duration timeout=Duration.ofSeconds(180);B173DedicatedServer server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout);BlockPosition top,sheep,pig;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3},new int[]{1,2,52,276},new int[]{32,48,2,1},new int[]{0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==4,"remaining-mob-drops-rest inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded remaining-mob-drops-rest fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   actor.selectHeldSlot(1);for(int r=1;r<=3;r++){for(int z=-r+1;z<r;z++){grass(actor,new BlockPosition(top.x()-r+1,top.y(),top.z()+z),BlockFace.WEST);grass(actor,new BlockPosition(top.x()+r-1,top.y(),top.z()+z),BlockFace.EAST);}for(int x=-r+1;x<r;x++){grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+x,top.y(),top.z()+r-1),BlockFace.SOUTH);}grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()-r,top.y(),top.z()+r-1),BlockFace.SOUTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()-r+1),BlockFace.NORTH);grass(actor,new BlockPosition(top.x()+r,top.y(),top.z()+r-1),BlockFace.SOUTH);}
   actor.selectHeldSlot(2);sheep=place(actor,top,BlockFace.UP,52);pig=place(actor,sheep,BlockFace.EAST,52);actor.sustainTicks(5);actor.close();awaitPlayers(server,0);server.save();
  }finally{actor.close();server.close();}
  Thread.sleep(1000L);B173SpawnerSeed.pigAndSheep(workspace,sheep);server=B173DedicatedServer.animals(jar,workspace,port,seed,timeout,3,true);actor=new B173WireClient("127.0.0.1",port,user,timeout);
  try{server.boot();actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()>=1,"remaining-mob-drops-rest reload inventory drift");RemoteDroppedItem pork=killUntil(actor,90,PORK),wool=killUntil(actor,91,WOOL);require(pork.item().equals(PORK)&&pork.item().legacyId()==319,"pig Packet21 pork 319 absent");require(wool.item().equals(WOOL)&&wool.item().legacyId()==35&&wool.item().damage()==0,"sheep Packet21 wool 35:0 absent");actor.close();awaitPlayers(server,0);server.save();
   String evidence="column="+column+",platform=7x7-48grass,sheep="+sheep.x()+":"+sheep.y()+":"+sheep.z()+":52:0,pig="+pig.x()+":"+pig.y()+":"+pig.z()+":52:0,mobs=type90+type91,death=packet7-sword276+packet38-status3+packet29,drops=packet21-319+packet21-35:0,kills<=8,clients=1,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-7x7-grass-platform+sheep-spawner52+pig-spawner52|cause=nbt-entityid-sheep+default-pig+official-diamond-sword-packet7|wire=packet24-type90+packet24-type91+packet38-status3+packet29+packet21-pork319+packet21-wool35:0|oracle=pig-pork-and-sheep-wool-death-drops-not-m388-zombie-feather|"+evidence;System.out.println("WORLDLINE_M444_SET="+evidence);System.out.println("WORLDLINE_M444_TRACE="+trace);System.out.println("WORLDLINE_M444_SIGNATURE="+sha(trace));
  }finally{actor.close();server.close();}
 }
 private static RemoteDroppedItem killUntil(B173WireClient a,int type,RemoteItemStack drop){RemoteDroppedItem found=null;int kills=0;while(found==null){require(++kills<=8,"official remaining death drop absent after bounded kills");RemoteMobSpawn spawn=a.awaitMobSpawn(type);require(spawn.legacyType()==type&&spawn.entityId()!=a.state().entityId()&&spawn.legacyType()!=54&&spawn.legacyType()!=51&&spawn.legacyType()!=52&&spawn.legacyType()!=57&&spawn.legacyType()!=92&&spawn.legacyType()!=93,"remaining Packet24 identity collapsed to hashed drop family");int entity=spawn.entityId();approach(a,spawn.x(),spawn.y()+1.0D,spawn.z()-1.5D);for(int hit=0;hit<8;hit++){if(B173ShearsAccess.peekDeath(a,entity)!=null)break;int sword=find(a.inventory(),276);require(sword>=36,"diamond sword lost");a.selectHeldSlot(sword-36);a.attackMob(entity);a.sustainTicks(20);}RemoteMobDeath death=a.awaitMobDeath(entity);require(death.entityId()==entity&&death.deathStatus()==3&&death.destroyPacket()==29,"remaining Packet38/29 death drift");a.sustainTicks(20);found=a.peekDroppedItem(drop);}require(found.item().equals(drop)&&found.item().legacyId()!=288,"remaining Packet21 drop drift");return found;}
 private static int find(RemoteInventoryView view,int id){for(int slot=36;slot<=44;slot++)if(!view.slot(slot).empty()&&view.slot(slot).item().legacyId()==id)return slot;return -1;}
 private static void approach(B173WireClient a,double x,double y,double z){for(int step=0;step<16;step++){PlayerPose here=a.moveAndObserve(0D,0D,0D,1).resulting();double dx=x-here.x(),dy=y-here.y(),dz=z-here.z(),dist=Math.sqrt(dx*dx+dy*dy+dz*dz);if(dist<=2.5D)return;double s=Math.min(1D,9.0D/dist);a.moveAndObserve(dx*s,dy*s,dz*s,2);}}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}private static void grass(B173WireClient a,BlockPosition support,BlockFace face)throws Exception{place(a,support,face,2);}private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic remaining-mob-drops-rest foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
