id=betavault-item-reference
aero.path=../aero-model-lib
aero.repository=https://github.com/lucasrgt/aero-model-lib.git
aero.revision=72fc01b101cdbd9369d974219a0363127843daaa
betavault.path=../betavault
betavault.revision=22d28a06f1baf431365f0951f8a352d8995d734b
betaenergistics.path=../beta-energistics
betaenergistics.revision=8bb6b0e5110df21fbe1da746d1b1a8eef7dba573
timeout.seconds=600
username=VaultCell
world.seed=81373
