package worldline.smoke.furnacecartmotionsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Spawns furnace-minecart Packet23 type 12 on rail 66, fuels with coal 263, and proves powered motion. */
public final class FurnaceCartMotionSetSmoke{
 private FurnaceCartMotionSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: FurnaceCartMotionSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);
  require(seed==17320110707L&&user.equals("FurnMot424")&&user.length()<=16,"furnace-cart-motion-set identity drift");
  Duration timeout=Duration.ofSeconds(90);B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;
  BlockPosition top,northPad,wall,southPad,detectorPad,bumperPad,bumper,westPad,rail,mid,detector;int column;BlockState idleDetector,liveDetector;RemoteObjectSpawn cart;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3,4},new int[]{1,66,28,343,263},new int[]{32,8,1,1,1},new int[]{0,0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==5,"furnace-cart-motion-set inventory drift");
   RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded furnace-cart-motion-set fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   northPad=place(actor,top,BlockFace.NORTH,1);wall=place(actor,northPad,BlockFace.UP,1);southPad=place(actor,top,BlockFace.SOUTH,1);detectorPad=place(actor,southPad,BlockFace.SOUTH,1);bumperPad=place(actor,detectorPad,BlockFace.SOUTH,1);bumper=place(actor,bumperPad,BlockFace.UP,1);westPad=place(actor,top,BlockFace.WEST,1);place(actor,westPad,BlockFace.NORTH,1);
   actor.selectHeldSlot(1);rail=BlockFace.UP.adjacent(top);actor.placeHeldBlock(top,BlockFace.UP);actor.awaitBlock(rail,new BlockState(66,0));mid=BlockFace.UP.adjacent(southPad);actor.placeHeldBlock(southPad,BlockFace.UP);actor.awaitBlock(mid,new BlockState(66,0));
   actor.selectHeldSlot(2);detector=BlockFace.UP.adjacent(detectorPad);actor.placeHeldBlock(detectorPad,BlockFace.UP);idleDetector=new BlockState(28,0);actor.awaitBlock(detector,idleDetector);
   require(rail.x()==mid.x()&&mid.x()==detector.x()&&mid.z()==rail.z()+1&&detector.z()==mid.z()+1&&wall.z()==rail.z()-1&&bumper.z()==detector.z()+1&&(idleDetector.metadata()&8)==0,"north-south rail66 track drift");
   actor.moveAndObserve(-1D,0D,0D,1);actor.selectHeldSlot(3);actor.useHeldItemOnBlock(rail,BlockFace.UP);cart=actor.awaitObjectSpawn(12);
   require(cart.type()==12&&cart.type()!=10&&cart.type()!=11&&cart.throwerId()==0&&cart.velocityX()==0&&cart.velocityY()==0&&cart.velocityZ()==0&&cart.fixedX()==rail.x()*32+16&&cart.fixedY()==rail.y()*32+27&&cart.fixedZ()==rail.z()*32+16&&cart.fixedZ()!=detector.z()*32+16,"furnace-minecart packet23 type12 spawn bounds drift");
   require(actor.sustainTicks(10).blockAt(detector.x(),detector.y(),detector.z()).equals(idleDetector)&&(idleDetector.metadata()&8)==0,"unfueled furnace cart launched on rail 66");
   actor.moveAndObserve(0D,0D,-1D,1);actor.look(180F,0F);actor.selectHeldSlot(4);B173FurnaceCartFuel.use(actor,cart.entityId());B173FurnaceCartFuel.awaitConsumed(actor);liveDetector=new BlockState(28,8);actor.awaitBlock(detector,liveDetector);
   require((liveDetector.metadata()&8)!=0&&!liveDetector.equals(idleDetector)&&actor.sustainTicks(5).blockAt(detector.x(),detector.y(),detector.z()).equals(liveDetector),"fueled furnace-cart motion or detector occupancy drift");
   actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();reader.awaitBlock(rail,new BlockState(66,0));reader.awaitBlock(mid,new BlockState(66,0));reader.awaitBlock(detector,liveDetector);RemoteChunkSnapshot after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);
   require(after.blockAt(local(rail.x(),cx),rail.y(),local(rail.z(),cz)).equals(new BlockState(66,0))&&after.blockAt(local(mid.x(),cx),mid.y(),local(mid.z(),cz)).equals(new BlockState(66,0))&&after.blockAt(local(detector.x(),cx),detector.y(),local(detector.z(),cz)).equals(liveDetector)&&(after.blockAt(local(detector.x(),cx),detector.y(),local(detector.z(),cz)).metadata()&8)!=0&&after.blockAt(local(wall.x(),cx),wall.y(),local(wall.z(),cz)).equals(new BlockState(1,0))&&after.blockAt(local(bumper.x(),cx),bumper.y(),local(bumper.z(),cz)).equals(new BlockState(1,0)),"persisted furnace-cart-motion-set drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,wall="+wall.x()+":"+wall.y()+":"+wall.z()+":1:0,bumper="+bumper.x()+":"+bumper.y()+":"+bumper.z()+":1:0,rail="+rail.x()+":"+rail.y()+":"+rail.z()+":66:0,track="+mid.x()+":"+mid.y()+":"+mid.z()+":66:0,detector="+detector.x()+":"+detector.y()+":"+detector.z()+":28:"+idleDetector.metadata()+"->"+liveDetector.metadata()+",cart=type12+thrower0+fixed"+cart.fixedX()+":"+cart.fixedY()+":"+cart.fixedZ()+",coal=263:1->0,unfueled-hold=idle,fueled=1,persisted=true,clients=2,disconnect=clean";
   String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+wall+rail66+detector28+bumper+furnace-minecart343+coal263|cause=packet15-item66+packet15-furnace-minecart343+packet7-coal263|wire=packet23-type12+thrower0+packet103-coal263-consume+packet53-detector28:0->8|oracle=unfueled-hold-idle+fueled-launch-on-rail66+fresh-login|"+evidence;
   System.out.println("WORLDLINE_M424_SET="+evidence);System.out.println("WORLDLINE_M424_TRACE="+trace);System.out.println("WORLDLINE_M424_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic furnace-cart-motion-set foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
