package worldline.smoke.cakefulleatsetb173;

import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.Duration;import worldline.api.*;import worldline.b173server.*;

/** Places uneaten cake 92:0, then Packet15-eats remaining BlockCake slices through air. */
public final class CakeFullEatSetSmoke{
 private CakeFullEatSetSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=7)throw new IllegalArgumentException("usage: CakeFullEatSetSmoke server.jar workspace port seed username chunkX chunkZ");
  Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;BlockPosition top,cake;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1},new int[]{1,354},new int[]{32,1},new int[]{0,0},1);actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==2,"cake-full inventory drift");require(actor.awaitHealth(1)==1,"seeded cake-full health drift");RemoteChunkSnapshot initial=chunk(actor,cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(initial.blockAt(local(top.x(),cx),top.y()+1,local(top.z(),cz)).legacyId())){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded cake-full fixture");}for(int lift=0;lift<8;lift++){top=place(actor,top,BlockFace.UP,1);actor.moveAndObserve(0D,1D,0D,1);column++;}
   cake=BlockFace.UP.adjacent(top);actor.selectHeldSlot(1);actor.useHeldItemOnBlock(top,BlockFace.UP);require(actor.awaitBlock(cake,new BlockState(92,0)).blockAt(cake.x(),cake.y(),cake.z()).equals(new BlockState(92,0)),"placed BlockCake 92:0 absent");require(actor.health()<4,"pre-bite health "+actor.health()+" cannot take remaining slices");actor.selectHeldSlot(2);bite(actor,cake,92,1);bite(actor,cake,92,2);bite(actor,cake,92,3);bite(actor,cake,92,4);bite(actor,cake,92,5);bite(actor,cake,0,0);actor.close();awaitPlayers(server,0);server.save();
   reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();RemoteChunkSnapshot after=chunk(reader,cx,cz);require(after.blockAt(local(cake.x(),cx),cake.y(),local(cake.z(),cz)).equals(new BlockState(0,0)),"persisted cake-full air drift");
   String evidence="column="+column+",support="+top.x()+":"+top.y()+":"+top.z()+":1:0,cake="+cake.x()+":"+cake.y()+":"+cake.z()+":92:0->1->2->3->4->5->0,slices=6,bites=6,air=true,persisted=true,clients=2,disconnect=clean";String trace="v1|server=official-b1.7.3|seed="+seed+"|fixture=raised-stone+blockcake92|cause=packet15-item354-place+empty-hand-packet15-remaining-slices|wire=packet53-cake92:0->1->2->3->4->5->0|oracle=blockcake-full-eat-metadata+fresh-login|"+evidence;System.out.println("WORLDLINE_M369_SET="+evidence);System.out.println("WORLDLINE_M369_TRACE="+trace);System.out.println("WORLDLINE_M369_SIGNATURE="+sha(trace));
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
 }
 private static RemoteChunkSnapshot chunk(B173WireClient a,int cx,int cz)throws Exception{return worldline.test.WorldlineSmokeAwait.awaitWorld(a,w->w.containsChunk(cx,cz),"cake-full chunk",600).chunkAt(cx,cz);}
 private static void bite(B173WireClient a,BlockPosition cake,int id,int meta)throws Exception{require(a.health()<20,"cake-full health capped before "+id+":"+meta+" health="+a.health());a.activateBlock(cake,BlockFace.UP);require(a.awaitBlock(cake,new BlockState(id,meta)).blockAt(cake.x(),cake.y(),cake.z()).equals(new BlockState(id,meta)),"BlockCake bite "+id+":"+meta+" absent");}
 private static BlockPosition place(B173WireClient a,BlockPosition support,BlockFace face,int id)throws Exception{BlockPosition target=face.adjacent(support);a.placeHeldBlock(support,face);a.awaitBlock(target,new BlockState(id,0));return target;}
 private static BlockPosition foundation(RemoteChunkSnapshot q,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(q.blockAt(x,y,z).legacyId()==3&&water(q.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic cake-full foundation");}
 private static boolean water(int id){return id==8||id==9;}private static int local(int v,int c){return v-c*16;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String sha(String s)throws Exception{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder v=new StringBuilder();for(byte x:b)v.append(String.format("%02x",x&255));return v.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}
}
