package worldline.smoke.pistonlimitb173;

import java.nio.*;import java.nio.charset.*;import java.nio.file.*;import java.security.*;import java.time.*;
import worldline.api.*;import worldline.b173server.*;

/** Tests one alternating vertical payload at the official piston limit boundary. */
public final class PistonPushLimitSmoke{
 private PistonPushLimitSmoke(){}
 public static void main(String[]a)throws Exception{
  if(a.length!=10)throw new IllegalArgumentException("usage: PistonPushLimitSmoke server.jar workspace port seed username chunkX chunkZ fixtureTicks signalTicks payloadCount");Path jar=Paths.get(a[0]),workspace=Paths.get(a[1]);int port=Integer.parseInt(a[2]);long seed=Long.parseLong(a[3]);String user=a[4];int cx=Integer.parseInt(a[5]),cz=Integer.parseInt(a[6]),fixture=Integer.parseInt(a[7]),signal=Integer.parseInt(a[8]),count=Integer.parseInt(a[9]);Duration timeout=Duration.ofSeconds(90);
  B173DedicatedServer server=new B173DedicatedServer(jar,workspace,port,seed,timeout,3,true);B173WireClient actor=new B173WireClient("127.0.0.1",port,user,timeout),reader=null;RemoteChunkSnapshot before,after;BlockPosition top,piston,lever,first,destination;BlockState leverOff,leverOn,pistonOff,pistonOn;int column;
  try{server.boot();B173PlayerSeed.writeInventory(workspace,user,4.5D,60D,4.5D,new int[]{0,1,2,3},new int[]{1,33,69,4},new int[]{64,1,1,16},new int[]{0,0,0,0});actor.connect();actor.synchronizePose();require(actor.awaitInventory().occupiedSlots()==4,"push-limit inventory drift");RemoteChunkSnapshot initial=actor.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);top=foundation(initial,cx,cz);column=0;actor.selectHeldSlot(0);
   while(water(at(initial,BlockFace.UP.adjacent(top),cx,cz).legacyId())){actor.placeHeldBlock(top,BlockFace.UP);top=BlockFace.UP.adjacent(top);actor.awaitBlock(top,new BlockState(1,0));actor.moveAndObserve(0D,1D,0D,1);require(++column<=15,"water column exceeded fixture stack");}
   actor.placeHeldBlock(top,BlockFace.UP);top=BlockFace.UP.adjacent(top);actor.awaitBlock(top,new BlockState(1,0));actor.moveAndObserve(0D,3D,0D,3);column++;piston=BlockFace.UP.adjacent(top);lever=BlockFace.EAST.adjacent(top);first=BlockFace.UP.adjacent(piston);destination=piston;for(int i=0;i<=count;i++)destination=BlockFace.UP.adjacent(destination);require(at(initial,piston,cx,cz).legacyId()==0&&at(initial,destination,cx,cz).legacyId()==0,"vertical targets were not initial air");
   actor.selectHeldSlot(2);actor.placeHeldBlock(top,BlockFace.EAST);leverOff=actor.sustainTicks(5).blockAt(lever.x(),lever.y(),lever.z());require(leverOff.equals(new BlockState(69,1)),"lever absent");actor.selectHeldSlot(1);actor.placeHeldBlock(top,BlockFace.UP);pistonOff=actor.sustainTicks(5).blockAt(piston.x(),piston.y(),piston.z());require(pistonOff.equals(new BlockState(33,1)),"up piston absent: "+pistonOff);
   BlockPosition placed=piston;for(int i=0;i<count;i++){int id=(i&1)==0?1:4;actor.selectHeldSlot((i&1)==0?0:3);actor.placeHeldBlock(placed,BlockFace.UP);placed=BlockFace.UP.adjacent(placed);actor.awaitBlock(placed,new BlockState(id,0));actor.moveAndObserve(0D,1D,0D,1);}actor.moveAndObserve(2D,0D,0D,2);for(int i=0;i<count;i++)actor.moveAndObserve(0D,-1D,0D,1);actor.selectHeldSlot(4);
   before=actor.sustainTicks(fixture).chunkAt(cx,cz);require(at(before,first,cx,cz).equals(new BlockState(1,0))&&at(before,destination,cx,cz).equals(new BlockState(0,0)),"vertical chain precondition drift");actor.activateBlock(lever,BlockFace.UP);RemoteWorldView live=actor.sustainTicks(signal);leverOn=live.blockAt(lever.x(),lever.y(),lever.z());pistonOn=live.blockAt(piston.x(),piston.y(),piston.z());BlockState firstLive=live.blockAt(first.x(),first.y(),first.z()),destinationLive=live.blockAt(destination.x(),destination.y(),destination.z());require(leverOn.equals(new BlockState(69,9)),"lever did not power");if(count==12)require(pistonOn.equals(new BlockState(33,9))&&firstLive.equals(new BlockState(34,1)),"twelve-block extension absent: "+pistonOn+"/"+firstLive+"/"+destinationLive);else require(count==13&&pistonOn.equals(pistonOff)&&firstLive.equals(new BlockState(1,0))&&destinationLive.equals(new BlockState(0,0)),"thirteen-block rejection absent: "+pistonOn+"/"+firstLive+"/"+destinationLive);
   actor.close();awaitPlayers(server,0);server.save();reader=new B173WireClient("127.0.0.1",port,user,timeout);reader.connect();reader.synchronizePose();after=reader.awaitRemoteChunk(cx,cz).chunkAt(cx,cz);BlockState destinationFresh=at(after,destination,cx,cz);require(at(after,lever,cx,cz).equals(leverOn)&&at(after,piston,cx,cz).equals(pistonOn)&&(count==12?destinationFresh.equals(new BlockState(4,0)):destinationFresh.equals(new BlockState(0,0))),"fresh limit control drift: "+destinationFresh);
  }finally{actor.close();if(reader!=null)reader.close();server.close();}
  Delta chain=chain(before,after,piston,count),raised=delta(before,after,top.y());int expected=count==12?15:1;require(raised.changed==expected&&chain.changed==(count==12?count+1:0),"limit delta drift: "+raised.cells);String component="blocks="+count+",column="+column+",lever="+leverOff.metadata()+"->"+leverOn.metadata()+",piston="+pistonOff.metadata()+"->"+pistonOn.metadata()+",chain="+chain+",raised="+raised;System.out.println("WORLDLINE_M147_SIGNAL="+component);System.out.println("WORLDLINE_M147_COMPONENT="+component);
 }
 private static BlockPosition foundation(RemoteChunkSnapshot c,int cx,int cz){for(int x=4;x<=11;x++)for(int z=4;z<=11;z++)for(int y=126;y>=1;y--)if(c.blockAt(x,y,z).legacyId()==3&&water(c.blockAt(x,y+1,z).legacyId()))return new BlockPosition(cx*16+x,y,cz*16+z);throw new IllegalStateException("no deterministic piston foundation");}private static BlockState at(RemoteChunkSnapshot c,BlockPosition p,int cx,int cz){return c.blockAt(p.x()-cx*16,p.y(),p.z()-cz*16);}
 private static Delta chain(RemoteChunkSnapshot a,RemoteChunkSnapshot b,BlockPosition piston,int count)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");int n=0;StringBuilder cells=new StringBuilder();for(int i=1;i<=count+1;i++){BlockPosition p=piston;for(int j=0;j<i;j++)p=BlockFace.UP.adjacent(p);BlockState q=a.blockAt(p.x()&15,p.y(),p.z()&15),r=b.blockAt(p.x()&15,p.y(),p.z()&15);if(!q.equals(r)){n++;add(d,cells,p.x()&15,p.y(),p.z()&15,q,r);}}return new Delta(n,hex(d.digest()),cells.toString());}
 private static Delta delta(RemoteChunkSnapshot a,RemoteChunkSnapshot b,int minY)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");StringBuilder cells=new StringBuilder();int n=0;for(int x=0;x<16;x++)for(int z=0;z<16;z++)for(int y=minY;y<128;y++){BlockState q=a.blockAt(x,y,z),r=b.blockAt(x,y,z);if(!q.equals(r)){n++;add(d,cells,x,y,z,q,r);}}return new Delta(n,hex(d.digest()),cells.toString());}private static void add(MessageDigest d,StringBuilder s,int x,int y,int z,BlockState q,BlockState r){if(s.length()>0)s.append(';');s.append(x).append(':').append(y).append(':').append(z).append(':').append(q).append('>').append(r);ByteBuffer row=ByteBuffer.allocate(10);row.putShort((short)x).putShort((short)y).putShort((short)z).put((byte)q.legacyId()).put((byte)q.metadata()).put((byte)r.legacyId()).put((byte)r.metadata());d.update(row.array());}
 private static boolean water(int id){return id==8||id==9;}private static void awaitPlayers(B173DedicatedServer s,int n)throws Exception{long e=System.currentTimeMillis()+5000;while(System.currentTimeMillis()<e){if(s.players().size()==n)return;Thread.sleep(100);}throw new IllegalStateException("player count drift");}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte v:b)s.append(String.format("%02x",v&255));return s.toString();}private static void require(boolean v,String m){if(!v)throw new IllegalStateException(m);}private static final class Delta{final int changed;final String hash,cells;Delta(int c,String h,String x){changed=c;hash=h;cells=x;}public String toString(){return changed+":"+hash;}}
}
